// Code generated by cmd/gen-sqlstate from postgres/src/backend/utils/errcodes.txt. DO NOT EDIT.

package errcodes

// Severity is the upstream classification (E=error, W=warning, S=success).
type Severity byte

const (
	SeverityError   Severity = 'E'
	SeverityWarning Severity = 'W'
	SeveritySuccess Severity = 'S'
)

// Code is a 5-character SQLSTATE string. The named constants below are
// generated from upstream's errcodes.txt; new codes must be added there
// (and re-generated) rather than introduced ad hoc.
type Code string

const (

	// Class 00 - Successful Completion
	SuccessfulCompletion Code = "00000" // successful_completion

	// Class 01 - Warning
	Warning                                 Code = "01000" // warning
	WarningNullValueEliminatedInSetFunction Code = "01003" // null_value_eliminated_in_set_function
	WarningStringDataRightTruncation        Code = "01004" // string_data_right_truncation
	WarningPrivilegeNotRevoked              Code = "01006" // privilege_not_revoked
	WarningPrivilegeNotGranted              Code = "01007" // privilege_not_granted
	WarningImplicitZeroBitPadding           Code = "01008" // implicit_zero_bit_padding
	WarningDynamicResultSetsReturned        Code = "0100C" // dynamic_result_sets_returned
	WarningDeprecatedFeature                Code = "01P01" // deprecated_feature

	// Class 02 - No Data (this is also a warning class per the SQL standard)
	NoData                                Code = "02000" // no_data
	NoAdditionalDynamicResultSetsReturned Code = "02001" // no_additional_dynamic_result_sets_returned

	// Class 03 - SQL Statement Not Yet Complete
	SQLStatementNotYetComplete Code = "03000" // sql_statement_not_yet_complete

	// Class 08 - Connection Exception
	ConnectionException                           Code = "08000" // connection_exception
	SqlclientUnableToEstablishSqlconnection       Code = "08001" // sqlclient_unable_to_establish_sqlconnection
	ConnectionDoesNotExist                        Code = "08003" // connection_does_not_exist
	SqlserverRejectedEstablishmentOfSqlconnection Code = "08004" // sqlserver_rejected_establishment_of_sqlconnection
	ConnectionFailure                             Code = "08006" // connection_failure
	TransactionResolutionUnknown                  Code = "08007" // transaction_resolution_unknown
	ProtocolViolation                             Code = "08P01" // protocol_violation

	// Class 09 - Triggered Action Exception
	TriggeredActionException Code = "09000" // triggered_action_exception

	// Class 0A - Feature Not Supported
	FeatureNotSupported Code = "0A000" // feature_not_supported

	// Class 0B - Invalid Transaction Initiation
	InvalidTransactionInitiation Code = "0B000" // invalid_transaction_initiation

	// Class 0F - Locator Exception
	LocatorException       Code = "0F000" // locator_exception
	LEInvalidSpecification Code = "0F001" // invalid_locator_specification

	// Class 0L - Invalid Grantor
	InvalidGrantor        Code = "0L000" // invalid_grantor
	InvalidGrantOperation Code = "0LP01" // invalid_grant_operation

	// Class 0P - Invalid Role Specification
	InvalidRoleSpecification Code = "0P000" // invalid_role_specification

	// Class 0Z - Diagnostics Exception
	DiagnosticsException                           Code = "0Z000" // diagnostics_exception
	StackedDiagnosticsAccessedWithoutActiveHandler Code = "0Z002" // stacked_diagnostics_accessed_without_active_handler

	// Class 10 - XQuery Error
	InvalidArgumentForXquery Code = "10608" // invalid_argument_for_xquery

	// Class 20 - Case Not Found
	CaseNotFound Code = "20000" // case_not_found

	// Class 21 - Cardinality Violation
	CardinalityViolation Code = "21000" // cardinality_violation

	// Class 22 - Data Exception
	DataException                             Code = "22000" // data_exception
	StringDataRightTruncation                 Code = "22001" // string_data_right_truncation
	NullValueNoIndicatorParameter             Code = "22002" // null_value_no_indicator_parameter
	NumericValueOutOfRange                    Code = "22003" // numeric_value_out_of_range
	NullValueNotAllowed                       Code = "22004" // null_value_not_allowed
	ErrorInAssignment                         Code = "22005" // error_in_assignment
	InvalidDatetimeFormat                     Code = "22007" // invalid_datetime_format
	DatetimeFieldOverflow                     Code = "22008" // datetime_field_overflow
	DatetimeValueOutOfRange                   Code = "22008" // (no spec name)
	InvalidTimeZoneDisplacementValue          Code = "22009" // invalid_time_zone_displacement_value
	EscapeCharacterConflict                   Code = "2200B" // escape_character_conflict
	InvalidUseOfEscapeCharacter               Code = "2200C" // invalid_use_of_escape_character
	InvalidEscapeOctet                        Code = "2200D" // invalid_escape_octet
	ZeroLengthCharacterString                 Code = "2200F" // zero_length_character_string
	MostSpecificTypeMismatch                  Code = "2200G" // most_specific_type_mismatch
	SequenceGeneratorLimitExceeded            Code = "2200H" // sequence_generator_limit_exceeded
	NotAnXmlDocument                          Code = "2200L" // not_an_xml_document
	InvalidXmlDocument                        Code = "2200M" // invalid_xml_document
	InvalidXmlContent                         Code = "2200N" // invalid_xml_content
	InvalidXmlComment                         Code = "2200S" // invalid_xml_comment
	InvalidXmlProcessingInstruction           Code = "2200T" // invalid_xml_processing_instruction
	InvalidIndicatorParameterValue            Code = "22010" // invalid_indicator_parameter_value
	SubstringError                            Code = "22011" // substring_error
	DivisionByZero                            Code = "22012" // division_by_zero
	InvalidPrecedingOrFollowingSize           Code = "22013" // invalid_preceding_or_following_size
	InvalidArgumentForNtile                   Code = "22014" // invalid_argument_for_ntile_function
	IntervalFieldOverflow                     Code = "22015" // interval_field_overflow
	InvalidArgumentForNthValue                Code = "22016" // invalid_argument_for_nth_value_function
	InvalidCharacterValueForCast              Code = "22018" // invalid_character_value_for_cast
	InvalidEscapeCharacter                    Code = "22019" // invalid_escape_character
	InvalidRegularExpression                  Code = "2201B" // invalid_regular_expression
	InvalidArgumentForLog                     Code = "2201E" // invalid_argument_for_logarithm
	InvalidArgumentForPowerFunction           Code = "2201F" // invalid_argument_for_power_function
	InvalidArgumentForWidthBucketFunction     Code = "2201G" // invalid_argument_for_width_bucket_function
	InvalidRowCountInLimitClause              Code = "2201W" // invalid_row_count_in_limit_clause
	InvalidRowCountInResultOffsetClause       Code = "2201X" // invalid_row_count_in_result_offset_clause
	CharacterNotInRepertoire                  Code = "22021" // character_not_in_repertoire
	IndicatorOverflow                         Code = "22022" // indicator_overflow
	InvalidParameterValue                     Code = "22023" // invalid_parameter_value
	UnterminatedCString                       Code = "22024" // unterminated_c_string
	InvalidEscapeSequence                     Code = "22025" // invalid_escape_sequence
	StringDataLengthMismatch                  Code = "22026" // string_data_length_mismatch
	TrimError                                 Code = "22027" // trim_error
	ArrayElementError                         Code = "2202E" // (no spec name)
	ArraySubscriptError                       Code = "2202E" // array_subscript_error
	InvalidTablesampleRepeat                  Code = "2202G" // invalid_tablesample_repeat
	InvalidTablesampleArgument                Code = "2202H" // invalid_tablesample_argument
	DuplicateJSONObjectKeyValue               Code = "22030" // duplicate_json_object_key_value
	InvalidArgumentForSQLJSONDatetimeFunction Code = "22031" // invalid_argument_for_sql_json_datetime_function
	InvalidJSONText                           Code = "22032" // invalid_json_text
	InvalidSQLJSONSubscript                   Code = "22033" // invalid_sql_json_subscript
	MoreThanOneSQLJSONItem                    Code = "22034" // more_than_one_sql_json_item
	NoSQLJSONItem                             Code = "22035" // no_sql_json_item
	NonNumericSQLJSONItem                     Code = "22036" // non_numeric_sql_json_item
	NonUniqueKeysInAJSONObject                Code = "22037" // non_unique_keys_in_a_json_object
	SingletonSQLJSONItemRequired              Code = "22038" // singleton_sql_json_item_required
	SQLJSONArrayNotFound                      Code = "22039" // sql_json_array_not_found
	SQLJSONMemberNotFound                     Code = "2203A" // sql_json_member_not_found
	SQLJSONNumberNotFound                     Code = "2203B" // sql_json_number_not_found
	SQLJSONObjectNotFound                     Code = "2203C" // sql_json_object_not_found
	TooManyJSONArrayElements                  Code = "2203D" // too_many_json_array_elements
	TooManyJSONObjectMembers                  Code = "2203E" // too_many_json_object_members
	SQLJSONScalarRequired                     Code = "2203F" // sql_json_scalar_required
	SQLJSONItemCannotBeCastToTargetType       Code = "2203G" // sql_json_item_cannot_be_cast_to_target_type
	FloatingPointException                    Code = "22P01" // floating_point_exception
	InvalidTextRepresentation                 Code = "22P02" // invalid_text_representation
	InvalidBinaryRepresentation               Code = "22P03" // invalid_binary_representation
	BadCopyFileFormat                         Code = "22P04" // bad_copy_file_format
	UntranslatableCharacter                   Code = "22P05" // untranslatable_character
	NonstandardUseOfEscapeCharacter           Code = "22P06" // nonstandard_use_of_escape_character

	// Class 23 - Integrity Constraint Violation
	IntegrityConstraintViolation Code = "23000" // integrity_constraint_violation
	RestrictViolation            Code = "23001" // restrict_violation
	NotNullViolation             Code = "23502" // not_null_violation
	ForeignKeyViolation          Code = "23503" // foreign_key_violation
	UniqueViolation              Code = "23505" // unique_violation
	CheckViolation               Code = "23514" // check_violation
	ExclusionViolation           Code = "23P01" // exclusion_violation

	// Class 24 - Invalid Cursor State
	InvalidCursorState Code = "24000" // invalid_cursor_state

	// Class 25 - Invalid Transaction State
	InvalidTransactionState                         Code = "25000" // invalid_transaction_state
	ActiveSQLTransaction                            Code = "25001" // active_sql_transaction
	BranchTransactionAlreadyActive                  Code = "25002" // branch_transaction_already_active
	InappropriateAccessModeForBranchTransaction     Code = "25003" // inappropriate_access_mode_for_branch_transaction
	InappropriateIsolationLevelForBranchTransaction Code = "25004" // inappropriate_isolation_level_for_branch_transaction
	NoActiveSQLTransactionForBranchTransaction      Code = "25005" // no_active_sql_transaction_for_branch_transaction
	ReadOnlySQLTransaction                          Code = "25006" // read_only_sql_transaction
	SchemaAndDataStatementMixingNotSupported        Code = "25007" // schema_and_data_statement_mixing_not_supported
	HeldCursorRequiresSameIsolationLevel            Code = "25008" // held_cursor_requires_same_isolation_level
	NoActiveSQLTransaction                          Code = "25P01" // no_active_sql_transaction
	InFailedSQLTransaction                          Code = "25P02" // in_failed_sql_transaction
	IdleInTransactionSessionTimeout                 Code = "25P03" // idle_in_transaction_session_timeout
	TransactionTimeout                              Code = "25P04" // transaction_timeout

	// Class 26 - Invalid SQL Statement Name
	InvalidSQLStatementName Code = "26000" // invalid_sql_statement_name

	// Class 42 - Syntax Error or Access Rule Violation
	UndefinedPstatement Code = "26000" // (no spec name)

	// Class 27 - Triggered Data Change Violation
	TriggeredDataChangeViolation Code = "27000" // triggered_data_change_violation

	// Class 28 - Invalid Authorization Specification
	InvalidAuthorizationSpecification Code = "28000" // invalid_authorization_specification
	InvalidPassword                   Code = "28P01" // invalid_password

	// Class 2B - Dependent Privilege Descriptors Still Exist
	DependentPrivilegeDescriptorsStillExist Code = "2B000" // dependent_privilege_descriptors_still_exist
	DependentObjectsStillExist              Code = "2BP01" // dependent_objects_still_exist

	// Class 2D - Invalid Transaction Termination
	InvalidTransactionTermination Code = "2D000" // invalid_transaction_termination

	// Class 2F - SQL Routine Exception
	SQLRoutineException                  Code = "2F000" // sql_routine_exception
	SREModifyingSQLDataNotPermitted      Code = "2F002" // modifying_sql_data_not_permitted
	SREProhibitedSQLStatementAttempted   Code = "2F003" // prohibited_sql_statement_attempted
	SREReadingSQLDataNotPermitted        Code = "2F004" // reading_sql_data_not_permitted
	SREFunctionExecutedNoReturnStatement Code = "2F005" // function_executed_no_return_statement

	// Class 34 - Invalid Cursor Name
	InvalidCursorName Code = "34000" // invalid_cursor_name

	// Class 42 - Syntax Error or Access Rule Violation
	UndefinedCursor Code = "34000" // (no spec name)

	// Class 38 - External Routine Exception
	ExternalRoutineException           Code = "38000" // external_routine_exception
	EREContainingSQLNotPermitted       Code = "38001" // containing_sql_not_permitted
	EREModifyingSQLDataNotPermitted    Code = "38002" // modifying_sql_data_not_permitted
	EREProhibitedSQLStatementAttempted Code = "38003" // prohibited_sql_statement_attempted
	EREReadingSQLDataNotPermitted      Code = "38004" // reading_sql_data_not_permitted

	// Class 39 - External Routine Invocation Exception
	ExternalRoutineInvocationException Code = "39000" // external_routine_invocation_exception
	ERIEInvalidSqlstateReturned        Code = "39001" // invalid_sqlstate_returned
	ERIENullValueNotAllowed            Code = "39004" // null_value_not_allowed
	ERIETriggerProtocolViolated        Code = "39P01" // trigger_protocol_violated
	ERIESRFProtocolViolated            Code = "39P02" // srf_protocol_violated
	ERIEEventTriggerProtocolViolated   Code = "39P03" // event_trigger_protocol_violated

	// Class 3B - Savepoint Exception
	SavepointException     Code = "3B000" // savepoint_exception
	SEInvalidSpecification Code = "3B001" // invalid_savepoint_specification

	// Class 3D - Invalid Catalog Name
	InvalidCatalogName Code = "3D000" // invalid_catalog_name

	// Class 42 - Syntax Error or Access Rule Violation
	UndefinedDatabase Code = "3D000" // (no spec name)

	// Class 3F - Invalid Schema Name
	InvalidSchemaName Code = "3F000" // invalid_schema_name

	// Class 42 - Syntax Error or Access Rule Violation
	UndefinedSchema Code = "3F000" // (no spec name)

	// Class 40 - Transaction Rollback
	TransactionRollback            Code = "40000" // transaction_rollback
	TRSerializationFailure         Code = "40001" // serialization_failure
	TRIntegrityConstraintViolation Code = "40002" // transaction_integrity_constraint_violation
	TRStatementCompletionUnknown   Code = "40003" // statement_completion_unknown
	TRDeadlockDetected             Code = "40P01" // deadlock_detected

	// Class 42 - Syntax Error or Access Rule Violation
	SyntaxErrorOrAccessRuleViolation Code = "42000" // syntax_error_or_access_rule_violation
	InsufficientPrivilege            Code = "42501" // insufficient_privilege
	SyntaxError                      Code = "42601" // syntax_error
	InvalidName                      Code = "42602" // invalid_name
	InvalidColumnDefinition          Code = "42611" // invalid_column_definition
	NameTooLong                      Code = "42622" // name_too_long
	DuplicateColumn                  Code = "42701" // duplicate_column
	AmbiguousColumn                  Code = "42702" // ambiguous_column
	UndefinedColumn                  Code = "42703" // undefined_column
	UndefinedObject                  Code = "42704" // undefined_object
	DuplicateObject                  Code = "42710" // duplicate_object
	DuplicateAlias                   Code = "42712" // duplicate_alias
	DuplicateFunction                Code = "42723" // duplicate_function
	AmbiguousFunction                Code = "42725" // ambiguous_function
	GroupingError                    Code = "42803" // grouping_error
	DatatypeMismatch                 Code = "42804" // datatype_mismatch
	WrongObjectType                  Code = "42809" // wrong_object_type
	InvalidForeignKey                Code = "42830" // invalid_foreign_key
	CannotCoerce                     Code = "42846" // cannot_coerce
	UndefinedFunction                Code = "42883" // undefined_function
	GeneratedAlways                  Code = "428C9" // generated_always
	ReservedName                     Code = "42939" // reserved_name
	UndefinedTable                   Code = "42P01" // undefined_table
	UndefinedParameter               Code = "42P02" // undefined_parameter
	DuplicateCursor                  Code = "42P03" // duplicate_cursor
	DuplicateDatabase                Code = "42P04" // duplicate_database
	DuplicatePstatement              Code = "42P05" // duplicate_prepared_statement
	DuplicateSchema                  Code = "42P06" // duplicate_schema
	DuplicateTable                   Code = "42P07" // duplicate_table
	AmbiguousParameter               Code = "42P08" // ambiguous_parameter
	AmbiguousAlias                   Code = "42P09" // ambiguous_alias
	InvalidColumnReference           Code = "42P10" // invalid_column_reference
	InvalidCursorDefinition          Code = "42P11" // invalid_cursor_definition
	InvalidDatabaseDefinition        Code = "42P12" // invalid_database_definition
	InvalidFunctionDefinition        Code = "42P13" // invalid_function_definition
	InvalidPstatementDefinition      Code = "42P14" // invalid_prepared_statement_definition
	InvalidSchemaDefinition          Code = "42P15" // invalid_schema_definition
	InvalidTableDefinition           Code = "42P16" // invalid_table_definition
	InvalidObjectDefinition          Code = "42P17" // invalid_object_definition
	IndeterminateDatatype            Code = "42P18" // indeterminate_datatype
	InvalidRecursion                 Code = "42P19" // invalid_recursion
	WindowingError                   Code = "42P20" // windowing_error
	CollationMismatch                Code = "42P21" // collation_mismatch
	IndeterminateCollation           Code = "42P22" // indeterminate_collation

	// Class 44 - WITH CHECK OPTION Violation
	WithCheckOptionViolation Code = "44000" // with_check_option_violation

	// Class 53 - Insufficient Resources
	InsufficientResources      Code = "53000" // insufficient_resources
	DiskFull                   Code = "53100" // disk_full
	OutOfMemory                Code = "53200" // out_of_memory
	TooManyConnections         Code = "53300" // too_many_connections
	ConfigurationLimitExceeded Code = "53400" // configuration_limit_exceeded

	// Class 54 - Program Limit Exceeded
	ProgramLimitExceeded Code = "54000" // program_limit_exceeded
	StatementTooComplex  Code = "54001" // statement_too_complex
	TooManyColumns       Code = "54011" // too_many_columns
	TooManyArguments     Code = "54023" // too_many_arguments

	// Class 55 - Object Not In Prerequisite State
	ObjectNotInPrerequisiteState Code = "55000" // object_not_in_prerequisite_state
	ObjectInUse                  Code = "55006" // object_in_use
	CantChangeRuntimeParam       Code = "55P02" // cant_change_runtime_param
	LockNotAvailable             Code = "55P03" // lock_not_available
	UnsafeNewEnumValueUsage      Code = "55P04" // unsafe_new_enum_value_usage

	// Class 57 - Operator Intervention
	OperatorIntervention Code = "57000" // operator_intervention
	QueryCanceled        Code = "57014" // query_canceled
	AdminShutdown        Code = "57P01" // admin_shutdown
	CrashShutdown        Code = "57P02" // crash_shutdown
	CannotConnectNow     Code = "57P03" // cannot_connect_now
	DatabaseDropped      Code = "57P04" // database_dropped
	IdleSessionTimeout   Code = "57P05" // idle_session_timeout

	// Class 58 - System Error (errors external to PostgreSQL itself)
	SystemError     Code = "58000" // system_error
	IOError         Code = "58030" // io_error
	UndefinedFile   Code = "58P01" // undefined_file
	DuplicateFile   Code = "58P02" // duplicate_file
	FileNameTooLong Code = "58P03" // file_name_too_long

	// Class F0 - Configuration File Error
	ConfigFileError Code = "F0000" // config_file_error
	LockFileExists  Code = "F0001" // lock_file_exists

	// Class HV - Foreign Data Wrapper Error (SQL/MED)
	FDWError                             Code = "HV000" // fdw_error
	FDWOutOfMemory                       Code = "HV001" // fdw_out_of_memory
	FDWDynamicParameterValueNeeded       Code = "HV002" // fdw_dynamic_parameter_value_needed
	FDWInvalidDataType                   Code = "HV004" // fdw_invalid_data_type
	FDWColumnNameNotFound                Code = "HV005" // fdw_column_name_not_found
	FDWInvalidDataTypeDescriptors        Code = "HV006" // fdw_invalid_data_type_descriptors
	FDWInvalidColumnName                 Code = "HV007" // fdw_invalid_column_name
	FDWInvalidColumnNumber               Code = "HV008" // fdw_invalid_column_number
	FDWInvalidUseOfNullPointer           Code = "HV009" // fdw_invalid_use_of_null_pointer
	FDWInvalidStringFormat               Code = "HV00A" // fdw_invalid_string_format
	FDWInvalidHandle                     Code = "HV00B" // fdw_invalid_handle
	FDWInvalidOptionIndex                Code = "HV00C" // fdw_invalid_option_index
	FDWInvalidOptionName                 Code = "HV00D" // fdw_invalid_option_name
	FDWOptionNameNotFound                Code = "HV00J" // fdw_option_name_not_found
	FDWReplyHandle                       Code = "HV00K" // fdw_reply_handle
	FDWUnableToCreateExecution           Code = "HV00L" // fdw_unable_to_create_execution
	FDWUnableToCreateReply               Code = "HV00M" // fdw_unable_to_create_reply
	FDWUnableToEstablishConnection       Code = "HV00N" // fdw_unable_to_establish_connection
	FDWNoSchemas                         Code = "HV00P" // fdw_no_schemas
	FDWSchemaNotFound                    Code = "HV00Q" // fdw_schema_not_found
	FDWTableNotFound                     Code = "HV00R" // fdw_table_not_found
	FDWFunctionSequenceError             Code = "HV010" // fdw_function_sequence_error
	FDWTooManyHandles                    Code = "HV014" // fdw_too_many_handles
	FDWInconsistentDescriptorInformation Code = "HV021" // fdw_inconsistent_descriptor_information
	FDWInvalidAttributeValue             Code = "HV024" // fdw_invalid_attribute_value
	FDWInvalidStringLengthOrBufferLength Code = "HV090" // fdw_invalid_string_length_or_buffer_length
	FDWInvalidDescriptorFieldIdentifier  Code = "HV091" // fdw_invalid_descriptor_field_identifier

	// Class P0 - PL/pgSQL Error
	PlpgsqlError   Code = "P0000" // plpgsql_error
	RaiseException Code = "P0001" // raise_exception
	NoDataFound    Code = "P0002" // no_data_found
	TooManyRows    Code = "P0003" // too_many_rows
	AssertFailure  Code = "P0004" // assert_failure

	// Class XX - Internal Error
	InternalError  Code = "XX000" // internal_error
	DataCorrupted  Code = "XX001" // data_corrupted
	IndexCorrupted Code = "XX002" // index_corrupted
)

var severities = map[Code]Severity{
	SuccessfulCompletion:                            'S',
	Warning:                                         'W',
	WarningNullValueEliminatedInSetFunction:         'W',
	WarningStringDataRightTruncation:                'W',
	WarningPrivilegeNotRevoked:                      'W',
	WarningPrivilegeNotGranted:                      'W',
	WarningImplicitZeroBitPadding:                   'W',
	WarningDynamicResultSetsReturned:                'W',
	WarningDeprecatedFeature:                        'W',
	NoData:                                          'W',
	NoAdditionalDynamicResultSetsReturned:           'W',
	SQLStatementNotYetComplete:                      'E',
	ConnectionException:                             'E',
	SqlclientUnableToEstablishSqlconnection:         'E',
	ConnectionDoesNotExist:                          'E',
	SqlserverRejectedEstablishmentOfSqlconnection:   'E',
	ConnectionFailure:                               'E',
	TransactionResolutionUnknown:                    'E',
	ProtocolViolation:                               'E',
	TriggeredActionException:                        'E',
	FeatureNotSupported:                             'E',
	InvalidTransactionInitiation:                    'E',
	LocatorException:                                'E',
	LEInvalidSpecification:                          'E',
	InvalidGrantor:                                  'E',
	InvalidGrantOperation:                           'E',
	InvalidRoleSpecification:                        'E',
	DiagnosticsException:                            'E',
	StackedDiagnosticsAccessedWithoutActiveHandler:  'E',
	InvalidArgumentForXquery:                        'E',
	CaseNotFound:                                    'E',
	CardinalityViolation:                            'E',
	DataException:                                   'E',
	StringDataRightTruncation:                       'E',
	NullValueNoIndicatorParameter:                   'E',
	NumericValueOutOfRange:                          'E',
	NullValueNotAllowed:                             'E',
	ErrorInAssignment:                               'E',
	InvalidDatetimeFormat:                           'E',
	DatetimeFieldOverflow:                           'E',
	InvalidTimeZoneDisplacementValue:                'E',
	EscapeCharacterConflict:                         'E',
	InvalidUseOfEscapeCharacter:                     'E',
	InvalidEscapeOctet:                              'E',
	ZeroLengthCharacterString:                       'E',
	MostSpecificTypeMismatch:                        'E',
	SequenceGeneratorLimitExceeded:                  'E',
	NotAnXmlDocument:                                'E',
	InvalidXmlDocument:                              'E',
	InvalidXmlContent:                               'E',
	InvalidXmlComment:                               'E',
	InvalidXmlProcessingInstruction:                 'E',
	InvalidIndicatorParameterValue:                  'E',
	SubstringError:                                  'E',
	DivisionByZero:                                  'E',
	InvalidPrecedingOrFollowingSize:                 'E',
	InvalidArgumentForNtile:                         'E',
	IntervalFieldOverflow:                           'E',
	InvalidArgumentForNthValue:                      'E',
	InvalidCharacterValueForCast:                    'E',
	InvalidEscapeCharacter:                          'E',
	InvalidRegularExpression:                        'E',
	InvalidArgumentForLog:                           'E',
	InvalidArgumentForPowerFunction:                 'E',
	InvalidArgumentForWidthBucketFunction:           'E',
	InvalidRowCountInLimitClause:                    'E',
	InvalidRowCountInResultOffsetClause:             'E',
	CharacterNotInRepertoire:                        'E',
	IndicatorOverflow:                               'E',
	InvalidParameterValue:                           'E',
	UnterminatedCString:                             'E',
	InvalidEscapeSequence:                           'E',
	StringDataLengthMismatch:                        'E',
	TrimError:                                       'E',
	ArrayElementError:                               'E',
	InvalidTablesampleRepeat:                        'E',
	InvalidTablesampleArgument:                      'E',
	DuplicateJSONObjectKeyValue:                     'E',
	InvalidArgumentForSQLJSONDatetimeFunction:       'E',
	InvalidJSONText:                                 'E',
	InvalidSQLJSONSubscript:                         'E',
	MoreThanOneSQLJSONItem:                          'E',
	NoSQLJSONItem:                                   'E',
	NonNumericSQLJSONItem:                           'E',
	NonUniqueKeysInAJSONObject:                      'E',
	SingletonSQLJSONItemRequired:                    'E',
	SQLJSONArrayNotFound:                            'E',
	SQLJSONMemberNotFound:                           'E',
	SQLJSONNumberNotFound:                           'E',
	SQLJSONObjectNotFound:                           'E',
	TooManyJSONArrayElements:                        'E',
	TooManyJSONObjectMembers:                        'E',
	SQLJSONScalarRequired:                           'E',
	SQLJSONItemCannotBeCastToTargetType:             'E',
	FloatingPointException:                          'E',
	InvalidTextRepresentation:                       'E',
	InvalidBinaryRepresentation:                     'E',
	BadCopyFileFormat:                               'E',
	UntranslatableCharacter:                         'E',
	NonstandardUseOfEscapeCharacter:                 'E',
	IntegrityConstraintViolation:                    'E',
	RestrictViolation:                               'E',
	NotNullViolation:                                'E',
	ForeignKeyViolation:                             'E',
	UniqueViolation:                                 'E',
	CheckViolation:                                  'E',
	ExclusionViolation:                              'E',
	InvalidCursorState:                              'E',
	InvalidTransactionState:                         'E',
	ActiveSQLTransaction:                            'E',
	BranchTransactionAlreadyActive:                  'E',
	InappropriateAccessModeForBranchTransaction:     'E',
	InappropriateIsolationLevelForBranchTransaction: 'E',
	NoActiveSQLTransactionForBranchTransaction:      'E',
	ReadOnlySQLTransaction:                          'E',
	SchemaAndDataStatementMixingNotSupported:        'E',
	HeldCursorRequiresSameIsolationLevel:            'E',
	NoActiveSQLTransaction:                          'E',
	InFailedSQLTransaction:                          'E',
	IdleInTransactionSessionTimeout:                 'E',
	TransactionTimeout:                              'E',
	InvalidSQLStatementName:                         'E',
	TriggeredDataChangeViolation:                    'E',
	InvalidAuthorizationSpecification:               'E',
	InvalidPassword:                                 'E',
	DependentPrivilegeDescriptorsStillExist:         'E',
	DependentObjectsStillExist:                      'E',
	InvalidTransactionTermination:                   'E',
	SQLRoutineException:                             'E',
	SREModifyingSQLDataNotPermitted:                 'E',
	SREProhibitedSQLStatementAttempted:              'E',
	SREReadingSQLDataNotPermitted:                   'E',
	SREFunctionExecutedNoReturnStatement:            'E',
	InvalidCursorName:                               'E',
	ExternalRoutineException:                        'E',
	EREContainingSQLNotPermitted:                    'E',
	EREModifyingSQLDataNotPermitted:                 'E',
	EREProhibitedSQLStatementAttempted:              'E',
	EREReadingSQLDataNotPermitted:                   'E',
	ExternalRoutineInvocationException:              'E',
	ERIEInvalidSqlstateReturned:                     'E',
	ERIENullValueNotAllowed:                         'E',
	ERIETriggerProtocolViolated:                     'E',
	ERIESRFProtocolViolated:                         'E',
	ERIEEventTriggerProtocolViolated:                'E',
	SavepointException:                              'E',
	SEInvalidSpecification:                          'E',
	InvalidCatalogName:                              'E',
	InvalidSchemaName:                               'E',
	TransactionRollback:                             'E',
	TRSerializationFailure:                          'E',
	TRIntegrityConstraintViolation:                  'E',
	TRStatementCompletionUnknown:                    'E',
	TRDeadlockDetected:                              'E',
	SyntaxErrorOrAccessRuleViolation:                'E',
	InsufficientPrivilege:                           'E',
	SyntaxError:                                     'E',
	InvalidName:                                     'E',
	InvalidColumnDefinition:                         'E',
	NameTooLong:                                     'E',
	DuplicateColumn:                                 'E',
	AmbiguousColumn:                                 'E',
	UndefinedColumn:                                 'E',
	UndefinedObject:                                 'E',
	DuplicateObject:                                 'E',
	DuplicateAlias:                                  'E',
	DuplicateFunction:                               'E',
	AmbiguousFunction:                               'E',
	GroupingError:                                   'E',
	DatatypeMismatch:                                'E',
	WrongObjectType:                                 'E',
	InvalidForeignKey:                               'E',
	CannotCoerce:                                    'E',
	UndefinedFunction:                               'E',
	GeneratedAlways:                                 'E',
	ReservedName:                                    'E',
	UndefinedTable:                                  'E',
	UndefinedParameter:                              'E',
	DuplicateCursor:                                 'E',
	DuplicateDatabase:                               'E',
	DuplicatePstatement:                             'E',
	DuplicateSchema:                                 'E',
	DuplicateTable:                                  'E',
	AmbiguousParameter:                              'E',
	AmbiguousAlias:                                  'E',
	InvalidColumnReference:                          'E',
	InvalidCursorDefinition:                         'E',
	InvalidDatabaseDefinition:                       'E',
	InvalidFunctionDefinition:                       'E',
	InvalidPstatementDefinition:                     'E',
	InvalidSchemaDefinition:                         'E',
	InvalidTableDefinition:                          'E',
	InvalidObjectDefinition:                         'E',
	IndeterminateDatatype:                           'E',
	InvalidRecursion:                                'E',
	WindowingError:                                  'E',
	CollationMismatch:                               'E',
	IndeterminateCollation:                          'E',
	WithCheckOptionViolation:                        'E',
	InsufficientResources:                           'E',
	DiskFull:                                        'E',
	OutOfMemory:                                     'E',
	TooManyConnections:                              'E',
	ConfigurationLimitExceeded:                      'E',
	ProgramLimitExceeded:                            'E',
	StatementTooComplex:                             'E',
	TooManyColumns:                                  'E',
	TooManyArguments:                                'E',
	ObjectNotInPrerequisiteState:                    'E',
	ObjectInUse:                                     'E',
	CantChangeRuntimeParam:                          'E',
	LockNotAvailable:                                'E',
	UnsafeNewEnumValueUsage:                         'E',
	OperatorIntervention:                            'E',
	QueryCanceled:                                   'E',
	AdminShutdown:                                   'E',
	CrashShutdown:                                   'E',
	CannotConnectNow:                                'E',
	DatabaseDropped:                                 'E',
	IdleSessionTimeout:                              'E',
	SystemError:                                     'E',
	IOError:                                         'E',
	UndefinedFile:                                   'E',
	DuplicateFile:                                   'E',
	FileNameTooLong:                                 'E',
	ConfigFileError:                                 'E',
	LockFileExists:                                  'E',
	FDWError:                                        'E',
	FDWOutOfMemory:                                  'E',
	FDWDynamicParameterValueNeeded:                  'E',
	FDWInvalidDataType:                              'E',
	FDWColumnNameNotFound:                           'E',
	FDWInvalidDataTypeDescriptors:                   'E',
	FDWInvalidColumnName:                            'E',
	FDWInvalidColumnNumber:                          'E',
	FDWInvalidUseOfNullPointer:                      'E',
	FDWInvalidStringFormat:                          'E',
	FDWInvalidHandle:                                'E',
	FDWInvalidOptionIndex:                           'E',
	FDWInvalidOptionName:                            'E',
	FDWOptionNameNotFound:                           'E',
	FDWReplyHandle:                                  'E',
	FDWUnableToCreateExecution:                      'E',
	FDWUnableToCreateReply:                          'E',
	FDWUnableToEstablishConnection:                  'E',
	FDWNoSchemas:                                    'E',
	FDWSchemaNotFound:                               'E',
	FDWTableNotFound:                                'E',
	FDWFunctionSequenceError:                        'E',
	FDWTooManyHandles:                               'E',
	FDWInconsistentDescriptorInformation:            'E',
	FDWInvalidAttributeValue:                        'E',
	FDWInvalidStringLengthOrBufferLength:            'E',
	FDWInvalidDescriptorFieldIdentifier:             'E',
	PlpgsqlError:                                    'E',
	RaiseException:                                  'E',
	NoDataFound:                                     'E',
	TooManyRows:                                     'E',
	AssertFailure:                                   'E',
	InternalError:                                   'E',
	DataCorrupted:                                   'E',
	IndexCorrupted:                                  'E',
}

// Lookup returns the Severity classification for the given code, or
// (0, false) if the code is not a known upstream entry.
func Lookup(code Code) (Severity, bool) {
	s, ok := severities[code]
	return s, ok
}

// Class returns the SQL class — the leading two characters of a SQLSTATE.
// Returns the empty string for malformed codes.
func Class(code Code) string {
	if len(code) < 2 {
		return ""
	}
	return string(code[:2])
}
