// gen-sqlstate parses upstream PostgreSQL's errcodes.txt and emits
// internal/sqlstate/codes.go. The generator preserves three properties so
// the generated file is auditable:
//
//  1. Every SQLSTATE goopg ever emits comes from this table. Hand-rolled
//     codes are not allowed; if a code is missing here, the generator must
//     be re-run.
//  2. Identifiers come from upstream's `errcode_macro_name` field with the
//     ERRCODE_ prefix stripped and the rest converted to UpperCamelCase.
//     This keeps Go names obviously cross-referenceable to upstream.
//  3. The generator emits a Class table and a Severity helper so other
//     packages don't have to re-parse the SQLSTATE string.
//
// Run with:
//
//	go run ./cmd/gen-sqlstate -in postgres/src/backend/utils/errcodes.txt -out internal/sqlstate/codes.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"
)

type entry struct {
	SQLState string
	Severity byte // E / W / S
	Macro    string
	Spec     string
	Section  string
}

func main() {
	in := flag.String("in", "postgres/src/backend/utils/errcodes.txt", "path to upstream errcodes.txt")
	out := flag.String("out", "internal/utils/errcodes/codes.go", "path to write the generated Go file")
	pkg := flag.String("package", "errcodes", "package name to generate")
	flag.Parse()

	src, err := os.ReadFile(*in)
	if err != nil {
		log.Fatalf("read %s: %v", *in, err)
	}

	entries, err := parse(string(src))
	if err != nil {
		log.Fatalf("parse %s: %v", *in, err)
	}

	body := emit(*pkg, *in, entries)
	formatted, err := format.Source(body)
	if err != nil {
		log.Fatalf("gofmt generated source: %v\n--- generated ---\n%s", err, body)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
}

func parse(s string) ([]entry, error) {
	var (
		entries []entry
		section string
	)
	for lineno, line := range strings.Split(s, "\n") {
		raw := strings.TrimSpace(line)
		if raw == "" || strings.HasPrefix(raw, "#") {
			continue
		}
		if rest, ok := strings.CutPrefix(raw, "Section:"); ok {
			section = strings.TrimSpace(rest)
			continue
		}
		fields := strings.Fields(raw)
		if len(fields) < 3 {
			return nil, fmt.Errorf("line %d: short entry %q", lineno+1, raw)
		}
		state := fields[0]
		if len(state) != 5 {
			return nil, fmt.Errorf("line %d: SQLSTATE %q is not 5 chars", lineno+1, state)
		}
		sev := fields[1]
		if len(sev) != 1 || (sev[0] != 'E' && sev[0] != 'W' && sev[0] != 'S') {
			return nil, fmt.Errorf("line %d: severity %q invalid", lineno+1, sev)
		}
		macro := fields[2]
		spec := ""
		if len(fields) >= 4 {
			spec = fields[3]
		}
		entries = append(entries, entry{
			SQLState: state,
			Severity: sev[0],
			Macro:    macro,
			Spec:     spec,
			Section:  section,
		})
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("no entries parsed")
	}
	return entries, nil
}

// goName turns "ERRCODE_FEATURE_NOT_SUPPORTED" into "FeatureNotSupported".
// Identifiers that would otherwise start with a digit are prefixed with
// "Code" (none currently exist; the rule is a defensive guard).
func goName(macro string) string {
	core := strings.TrimPrefix(macro, "ERRCODE_")
	parts := strings.Split(core, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		// Preserve all-letter parts cased; digits stay as-is; otherwise title-case.
		switch p {
		case "SQL", "SRF", "FDW", "JSON", "OID", "DBA", "IO":
			b.WriteString(p)
		default:
			b.WriteString(strings.ToUpper(p[:1]))
			b.WriteString(strings.ToLower(p[1:]))
		}
	}
	name := b.String()
	if name == "" {
		return "Unknown"
	}
	if name[0] >= '0' && name[0] <= '9' {
		name = "Code" + name
	}
	return name
}

func emit(pkg, srcPath string, entries []entry) []byte {
	// Stable ordering by SQLSTATE.
	sort.SliceStable(entries, func(i, j int) bool { return entries[i].SQLState < entries[j].SQLState })

	// Deduplicate by Go identifier — upstream macros are unique, but be defensive.
	seen := map[string]int{}
	for i := range entries {
		base := goName(entries[i].Macro)
		n := seen[base]
		seen[base] = n + 1
		if n > 0 {
			base = fmt.Sprintf("%s_%d", base, n+1)
		}
		entries[i].Macro = base
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by cmd/gen-sqlstate from %s. DO NOT EDIT.\n\n", srcPath)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString(`// Severity is the upstream classification (E=error, W=warning, S=success).
type Severity byte

const (
	SeverityError   Severity = 'E'
	SeverityWarning Severity = 'W'
	SeveritySuccess Severity = 'S'
)

// Code is a 5-character SQLSTATE string. The named constants below are
// generated from upstream's errcodes.txt; new codes must be added there
// (and re-generated) rather than introduced ad hoc.
type Code string

`)
	fmt.Fprintf(&b, "const (\n")
	prevSection := ""
	for _, e := range entries {
		if e.Section != prevSection {
			fmt.Fprintf(&b, "\n\t// %s\n", e.Section)
			prevSection = e.Section
		}
		comment := e.Spec
		if comment == "" {
			comment = "(no spec name)"
		}
		fmt.Fprintf(&b, "\t%s Code = %q // %s\n", e.Macro, e.SQLState, comment)
	}
	fmt.Fprintf(&b, ")\n\n")

	// Severity table — keyed by SQLSTATE, deduplicated. Some upstream macros
	// share a SQLSTATE (e.g. ERRCODE_ARRAY_ELEMENT_ERROR and
	// ERRCODE_ARRAY_SUBSCRIPT_ERROR both map to "2202E"); we keep both as
	// named constants but emit only one map entry per code.
	b.WriteString(`var severities = map[Code]Severity{` + "\n")
	emitted := map[string]bool{}
	for _, e := range entries {
		if emitted[e.SQLState] {
			continue
		}
		emitted[e.SQLState] = true
		fmt.Fprintf(&b, "\t%s: %q,\n", e.Macro, e.Severity)
	}
	b.WriteString("}\n\n")
	b.WriteString(`// Lookup returns the Severity classification for the given code, or
// (0, false) if the code is not a known upstream entry.
func Lookup(code Code) (Severity, bool) {
	s, ok := severities[code]
	return s, ok
}

// Class returns the SQL class — the leading two characters of a SQLSTATE.
// Returns the empty string for malformed codes.
func Class(code Code) string {
	if len(code) < 2 {
		return ""
	}
	return string(code[:2])
}
`)
	return b.Bytes()
}
