package optimizer

// M0127-P5.9-h — a bound-less index scan reads the whole relation.
//
// `EstimateRows` answered 1 for EVERY `*IndexScan` / `*IndexOnlyScan`, on the
// convention that such a node is an equality probe. The PG-shaped join search
// (`GOOPG_PGSHAPED_DP`) introduced the second shape PG has always had — an
// index path with an empty indexclauses list, "a full index scan"
// (pathnodes.h:1817), generated by `addOneOrderedIndexPath` so a merge join
// above it can skip a sort — and for that node the answer is the relation's
// cardinality, not 1.
//
// The defect these tests pin was measured, not hypothesised: at M0127-P5.9
// run 3 all six of the flag's §4 parity violations were joins over such a
// leaf, each estimated at 1 against actuals of 5 869–1 999 080. The
// reproducer, TPC-H Q12, planned `Index Scan using orders_pk on orders` with
// no Index Cond, `rows=1`, over 1 500 000 actual rows, and the Merge Join
// above it inherited the 1
// (`analysis/leftdeep-joins/2026-08-05-p59run3-audit-on.plans.txt`).
//
// Both halves are asserted, because only together do they say anything: the
// full-scan arm returns the relation (the fix) AND the probe arm still returns
// 1 (the blast radius — every index scan the flag-off planner emits binds an
// Index Cond, so none of them may move).

import (
	"testing"

	"github.com/goopg/goopg/internal/catalog"
)

func TestEstimateRowsFullIndexScan(t *testing.T) {
	tbl := statsTable("orders", 1500000, 1500000)
	col := &ColumnRef{Name: "c"}

	cases := []struct {
		name string
		node Node
		want int64
	}{
		// The Q12 leaf: no Key, no Keys, no bounds — the executor
		// RangeScans the whole index and every heap tuple comes out.
		{"IndexScan/full", &IndexScan{Table: tbl}, 1500000},
		// planner.go's sort-avoidance rewrite builds exactly this with
		// the flag OFF, so the arm is not search-only.
		{"IndexOnlyScan/full", &IndexOnlyScan{Table: tbl}, 1500000},

		// Every shape that binds the index keeps the probe convention.
		{"IndexScan/key", &IndexScan{Table: tbl, Key: col}, 1},
		{"IndexScan/keys", &IndexScan{Table: tbl, Keys: []Expr{col}}, 1},
		{"IndexScan/lowKey", &IndexScan{Table: tbl, LowKey: col}, 1},
		{"IndexScan/highKey", &IndexScan{Table: tbl, HighKey: col}, 1},
		{"IndexOnlyScan/key", &IndexOnlyScan{Table: tbl, Key: col}, 1},

		// No ANALYZE: 1, not 0. Zero means "no estimate available" to
		// every caller and would zero every node above this one — the
		// M0125-0038 propagation shape — which is a worse answer than
		// the one being replaced.
		{"IndexScan/full/noStats", &IndexScan{Table: &catalog.Table{Name: "t"}}, 1},
		{"IndexScan/full/noTable", &IndexScan{}, 1},
	}
	for _, tc := range cases {
		if got := EstimateRows(tc.node); got != tc.want {
			t.Errorf("%s: EstimateRows = %d, want %d", tc.name, got, tc.want)
		}
	}
}

// TestEstimateRowsFullIndexScanPropagates is the half that made the defect
// expensive rather than cosmetic: `EstimateRows` is read by the hash-table
// sizer (operators_join_agg.go), the join-algorithm choice (planner.go) and
// the Memoize decision (memoize.go), so a leaf that under-reports by the size
// of the table under-reports every join above it too.
func TestEstimateRowsFullIndexScanPropagates(t *testing.T) {
	orders := statsTable("orders", 1500000, 1500000)
	lineitem := statsTable("lineitem", 5997241, 1500000)

	// Q12's shape: Merge Join over a full index scan of orders and a
	// filtered seq scan of lineitem.
	join := &Join{
		Type:  JoinTypeInner,
		Left:  &IndexScan{Table: orders},
		Right: &SeqScan{Table: lineitem},
	}
	got := EstimateRows(join)
	if got <= 1 {
		t.Fatalf("join over a full index scan estimates %d; the leaf's collapse propagated", got)
	}

	// The same join with a seq-scanned outer is what the flag-off arm
	// plans, and the two must now agree — the access method chosen for a
	// relation cannot change how many rows that relation has.
	seqSide := &Join{
		Type:  JoinTypeInner,
		Left:  &SeqScan{Table: orders},
		Right: &SeqScan{Table: lineitem},
	}
	if want := EstimateRows(seqSide); got != want {
		t.Errorf("full-index-scan outer estimates %d but seq-scan outer estimates %d; the same relation read two ways", got, want)
	}
}
