package optimizer

// M0127-P5.9-h — a bound-less index scan reads the whole relation.
//
// `EstimateRows` answered 1 for EVERY `*IndexScan` / `*IndexOnlyScan`, on the
// convention that such a node is an equality probe. The PG-shaped join search
// (`GOOPG_PGSHAPED_DP`) introduced the second shape PG has always had — an
// index path with an empty indexclauses list, "a full index scan"
// (pathnodes.h:1817), generated by `addOneOrderedIndexPath` so a merge join
// above it can skip a sort — and for that node the answer is the relation's
// cardinality, not 1.
//
// The defect these tests pin was measured, not hypothesised: at M0127-P5.9
// run 3 all six of the flag's §4 parity violations were joins over such a
// leaf, each estimated at 1 against actuals of 5 869–1 999 080. The
// reproducer, TPC-H Q12, planned `Index Scan using orders_pk on orders` with
// no Index Cond, `rows=1`, over 1 500 000 actual rows, and the Merge Join
// above it inherited the 1
// (`analysis/leftdeep-joins/2026-08-05-p59run3-audit-on.plans.txt`).
//
// Both halves are asserted, because only together do they say anything: the
// full-scan arm returns the relation (the original fix) AND the bound arms
// return what their selectivity says.
//
// UPDATED by pg-plan-parity item 0. This test used to assert that EVERY bound
// shape returns 1 — described here as "the blast radius … none of them may
// move". That guard was itself the defect: a flat 1 is right only for a UNIQUE
// index fully bound by equality, and on a non-unique index it was wrong by
// orders of magnitude (goopg 1 vs PG 378 rows for `s_nationkey = 5` over
// 10 000 rows). Because EstimateRows also sizes hash tables and picks join
// algorithms, that constant is the one underneath both the "bitmap never wins"
// and "nested loop 1 vs 25" plan gaps. The unique-equality case below still
// asserts 1; the others now assert selectivity × reltuples.

import (
	"testing"

	"github.com/goopg/goopg/internal/catalog"
)

func TestEstimateRowsFullIndexScan(t *testing.T) {
	tbl := statsTable("orders", 1500000, 1500000)
	col := &ColumnRef{Name: "c"}
	uniqueIdx := &catalog.Index{Name: "orders_pk", Columns: []string{"c"}, Unique: true}

	cases := []struct {
		name string
		node Node
		want int64
	}{
		// The Q12 leaf: no Key, no Keys, no bounds — the executor
		// RangeScans the whole index and every heap tuple comes out.
		{"IndexScan/full", &IndexScan{Table: tbl}, 1500000},
		// planner.go's sort-avoidance rewrite builds exactly this with
		// the flag OFF, so the arm is not search-only.
		{"IndexOnlyScan/full", &IndexOnlyScan{Table: tbl}, 1500000},

		// A UNIQUE index with every column bound by equality is the one
		// shape the old flat-1 convention was really right about, and it
		// keeps that answer. This is the PK probe, i.e. most of them.
		{"IndexScan/unique/key", &IndexScan{Table: tbl, Index: uniqueIdx, Key: col}, 1},

		// Every OTHER bound shape is now selectivity × reltuples, not 1
		// (pg-plan-parity item 0). These nodes carry no Index, so there are
		// no column statistics to consult and the per-column equality
		// selectivity falls back to PG's DEFAULT_NUM_DISTINCT = 200:
		// 1 500 000 / 200 = 7 500.
		{"IndexScan/key", &IndexScan{Table: tbl, Key: col}, 7500},
		{"IndexScan/keys", &IndexScan{Table: tbl, Keys: []Expr{col}}, 7500},
		{"IndexOnlyScan/key", &IndexOnlyScan{Table: tbl, Key: col}, 7500},
		// One inequality bound is PG's DEFAULT_INEQ_SEL = 1/3.
		{"IndexScan/lowKey", &IndexScan{Table: tbl, LowKey: col}, 500000},
		{"IndexScan/highKey", &IndexScan{Table: tbl, HighKey: col}, 500000},

		// No ANALYZE: 1, not 0. Zero means "no estimate available" to
		// every caller and would zero every node above this one — the
		// M0125-0038 propagation shape — which is a worse answer than
		// the one being replaced.
		{"IndexScan/full/noStats", &IndexScan{Table: &catalog.Table{Name: "t"}}, 1},
		{"IndexScan/full/noTable", &IndexScan{}, 1},
	}
	for _, tc := range cases {
		if got := EstimateRows(tc.node); got != tc.want {
			t.Errorf("%s: EstimateRows = %d, want %d", tc.name, got, tc.want)
		}
	}
}

// TestEstimateRowsFullIndexScanPropagates is the half that made the defect
// expensive rather than cosmetic: `EstimateRows` is read by the hash-table
// sizer (operators_join_agg.go), the join-algorithm choice (planner.go) and
// the Memoize decision (memoize.go), so a leaf that under-reports by the size
// of the table under-reports every join above it too.
func TestEstimateRowsFullIndexScanPropagates(t *testing.T) {
	orders := statsTable("orders", 1500000, 1500000)
	lineitem := statsTable("lineitem", 5997241, 1500000)

	// Q12's shape: Merge Join over a full index scan of orders and a
	// filtered seq scan of lineitem.
	join := &Join{
		Type:  JoinTypeInner,
		Left:  &IndexScan{Table: orders},
		Right: &SeqScan{Table: lineitem},
	}
	got := EstimateRows(join)
	if got <= 1 {
		t.Fatalf("join over a full index scan estimates %d; the leaf's collapse propagated", got)
	}

	// The same join with a seq-scanned outer is what the flag-off arm
	// plans, and the two must now agree — the access method chosen for a
	// relation cannot change how many rows that relation has.
	seqSide := &Join{
		Type:  JoinTypeInner,
		Left:  &SeqScan{Table: orders},
		Right: &SeqScan{Table: lineitem},
	}
	if want := EstimateRows(seqSide); got != want {
		t.Errorf("full-index-scan outer estimates %d but seq-scan outer estimates %d; the same relation read two ways", got, want)
	}
}
