// Command gen-kwlist-go transcribes PostgreSQL's keyword list into a Go data
// table for the goyacc parser front end.
//
// Input : postgres/src/include/parser/kwlist.h  (PG_KEYWORD 4-tuple rows:
//
//	text, terminal name, category, label kind)
//
// Output: internal/sqlparser/keywords_gen.go
//
// The generated table deliberately stores the TERMINAL NAME as a string, not
// its numeric value: token numbers are assigned by goyacc when the grammar
// (grammar/pg_grammar.y) is compiled, and the lexer adapter resolves names
// through the generated parser's yyToknames at init time. This keeps the
// table valid across grammar regenerations without re-running this generator.
//
// Provenance: rows are transcribed verbatim from the read-only oracle tree;
// this program never runs at production runtime. Regenerate with:
//
//	go run ./cmd/gen-kwlist-go
package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
)

var rowRe = regexp.MustCompile(
	`^PG_KEYWORD\("([^"]+)",\s*([A-Z_0-9]+),\s*` +
		`(UNRESERVED_KEYWORD|COL_NAME_KEYWORD|TYPE_FUNC_NAME_KEYWORD|RESERVED_KEYWORD),\s*` +
		`(BARE_LABEL|AS_LABEL)\)`)

type row struct {
	text, token string
	cat, label  string
}

func main() {
	kwlist := flag.String("kwlist", "postgres/src/include/parser/kwlist.h",
		"path to the read-only oracle kwlist.h")
	out := flag.String("out", "internal/sqlparser/keywords_gen.go",
		"output Go file path")
	tokensOut := flag.String("tokens-out", "",
		"optional path for a goyacc %token <str> declaration block (grammar/tokens_gen.y)")
	kwlistsOut := flag.String("kwlists-out", "",
		"optional path for the five keyword-list nonterminals (grammar/kwlists_gen.y)")
	flag.Parse()

	src, err := os.ReadFile(*kwlist)
	if err != nil {
		fail("read %s: %v", *kwlist, err)
	}

	var rows []row
	for i, line := range strings.Split(string(src), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "PG_KEYWORD(") {
			continue
		}
		m := rowRe.FindStringSubmatch(line)
		if m == nil {
			fail("%s:%d: unrecognized PG_KEYWORD row: %q", *kwlist, i+1, line)
		}
		rows = append(rows, row{text: m[1], token: m[2], cat: m[3], label: m[4]})
	}
	if len(rows) == 0 {
		fail("no PG_KEYWORD rows found in %s", *kwlist)
	}

	seenText, seenTok := map[string]bool{}, map[string]bool{}
	for _, r := range rows {
		if seenText[r.text] {
			fail("duplicate keyword text %q", r.text)
		}
		if seenTok[r.token] {
			fail("duplicate terminal name %q", r.token)
		}
		seenText[r.text], seenTok[r.token] = true, true
	}

	var b strings.Builder
	b.WriteString(`// Code generated by cmd/gen-kwlist-go FROM postgres/src/include/parser/kwlist.h. DO NOT EDIT.
//
// Provenance: read-only PostgreSQL oracle (18.3), file
// postgres/src/include/parser/kwlist.h — see docs/design/not_ralph/.
// Regenerate: go run ./cmd/gen-kwlist-go

package sqlparser

// KeywordCategory mirrors kwlist.h's four category codes. Categories are
// GRAMMATICAL metadata (upstream encodes them via the five list-nonterminals
// unreserved_keyword / col_name_keyword / type_func_name_keyword /
// reserved_keyword / bare_label_keyword); the lexer itself returns the
// keyword token regardless of category.
type KeywordCategory uint8

const (
	CatUnreserved   KeywordCategory = iota // UNRESERVED_KEYWORD
	CatColName                             // COL_NAME_KEYWORD
	CatTypeFuncName                        // TYPE_FUNC_NAME_KEYWORD
	CatReserved                            // RESERVED_KEYWORD
)

// KeywordLabel mirrors kwlist.h's fourth column (where the word may appear
// as a bare label).
type KeywordLabel uint8

const (
	LabelNone KeywordLabel = iota // not listed as a label keyword
	LabelBare                     // BARE_LABEL   -> bare_label_keyword
	LabelAs                       // AS_LABEL     -> as_label_keyword
)

// keywordDef is one transcribed kwlist.h row. Token holds the TERMINAL NAME
// (e.g. "BEGIN_P"); the lexer adapter resolves it to goyacc-assigned number
// via yyToknames at init time — never edit numbers by hand here.
type keywordDef struct {
	Text     string
	Token    string
	Category KeywordCategory
	Label    KeywordLabel
}

`)
	fmt.Fprintf(&b, "// %d rows, source order preserved.\n", len(rows))
	b.WriteString("var keywordDefs = []keywordDef{\n")
	catMap := map[string]string{
		"UNRESERVED_KEYWORD":     "CatUnreserved",
		"COL_NAME_KEYWORD":       "CatColName",
		"TYPE_FUNC_NAME_KEYWORD": "CatTypeFuncName",
		"RESERVED_KEYWORD":       "CatReserved",
	}
	labelMap := map[string]string{
		"BARE_LABEL": "LabelBare",
		"AS_LABEL":   "LabelAs",
	}
	for _, r := range rows {
		fmt.Fprintf(&b, "\t{Text: %q, Token: %q, Category: %s, Label: %s},\n",
			r.text, r.token, catMap[r.cat], labelMap[r.label])
	}
	b.WriteString("}\n")

	if err := os.MkdirAll(dirOf(*out), 0o755); err != nil {
		fail("mkdir: %v", err)
	}
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fail("write %s: %v", *out, err)
	}
	fmt.Fprintf(os.Stderr, "gen-kwlist-go: wrote %d keyword defs to %s\n", len(rows), *out)
	if *tokensOut != "" {
		writeTokensY(*tokensOut, rows)
	}
	if *kwlistsOut != "" {
		writeKwlistsY(*kwlistsOut, rows)
	}
}

// writeKwlistsY emits the five keyword-list nonterminals upstream defines as
// grammar-side enumerations (02-grammar-porting-guide §4): the four category
// lists plus bare_label_keyword / as_label_keyword derived from kwlist.h's
// fourth column. Upstream keeps these hand-written near gram.y :17685-18330;
// generating them keeps kwlist.h the single source of truth.
func writeKwlistsY(path string, rows []row) {
	lists := []struct {
		name string
		want func(r row) bool
	}{
		{"unreserved_keyword", func(r row) bool { return r.cat == "UNRESERVED_KEYWORD" }},
		{"col_name_keyword", func(r row) bool { return r.cat == "COL_NAME_KEYWORD" }},
		{"type_func_name_keyword", func(r row) bool { return r.cat == "TYPE_FUNC_NAME_KEYWORD" }},
		{"reserved_keyword", func(r row) bool { return r.cat == "RESERVED_KEYWORD" }},
		{"bare_label_keyword", func(r row) bool { return r.label == "BARE_LABEL" }},
		{"as_label_keyword", func(r row) bool { return r.label == "AS_LABEL" }},
	}
	var b strings.Builder
	b.WriteString("/* Code generated by cmd/gen-kwlist-go FROM postgres/src/include/parser/kwlist.h. DO NOT EDIT.\n")
	b.WriteString("   Mirrors gram.y :17685-18330 keyword-list nonterminals (names identical). */\n\n")
	for _, l := range lists {
		b.WriteString(l.name + ":\n")
		first := true
		for _, r := range rows {
			if !l.want(r) {
				continue
			}
			if first {
				b.WriteString("\t\t\t\t" + r.token + "\n")
				first = false
				continue
			}
			b.WriteString("\t\t\t| " + r.token + "\n")
		}
		if first {
			fail("keyword list %s came out empty — kwlist.h regression?", l.name)
		}
		b.WriteString("\t\t\t;\n\n")
	}
	if err := os.MkdirAll(dirOf(path), 0o755); err != nil {
		fail("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		fail("write %s: %v", path, err)
	}
	fmt.Fprintf(os.Stderr, "gen-kwlist-go: wrote %d keyword lists to %s\n", len(lists), path)
}

// writeTokensY emits the goyacc keyword-token declaration block. Upstream
// declares the same set inside gram.y (:700-795); we generate it instead so
// kwlist.h stays the single source of truth for names (docs/design/not_ralph/
// 02-grammar-porting-guide.md §2). The ported gram.y keeps every OTHER
// declaration verbatim.
func writeTokensY(path string, rows []row) {
	var b strings.Builder
	b.WriteString("/* Code generated by cmd/gen-kwlist-go FROM postgres/src/include/parser/kwlist.h. DO NOT EDIT.\n")
	b.WriteString("   Replaces gram.y %token <keyword> block (:700-795); names identical. */\n\n")
	const perLine = 6
	for i, r := range rows {
		switch {
		case i%perLine == 0:
			if i > 0 {
				b.WriteString("\n")
			}
			b.WriteString("%token <str> ")
		default:
			b.WriteString(" ")
		}
		b.WriteString(r.token)
	}
	b.WriteString("\n")
	if err := os.MkdirAll(dirOf(path), 0o755); err != nil {
		fail("mkdir: %v", err)
	}
	b.WriteString("\n/* keyword-list nonterminal value types (union field str). */\n")
	for _, l := range []string{"unreserved_keyword", "col_name_keyword", "type_func_name_keyword", "reserved_keyword", "bare_label_keyword", "as_label_keyword"} {
		b.WriteString("%type <str> " + l + "\n")
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		fail("write %s: %v", path, err)
	}
	fmt.Fprintf(os.Stderr, "gen-kwlist-go: wrote %d %%token decls to %s\n", len(rows), path)
}

func dirOf(p string) string {
	if i := strings.LastIndexByte(p, '/'); i >= 0 {
		return p[:i]
	}
	return "."
}

func fail(f string, a ...any) {
	fmt.Fprintf(os.Stderr, "gen-kwlist-go: "+f+"\n", a...)
	os.Exit(1)
}
