// Command gen-kwlist-go transcribes PostgreSQL's keyword list into a Go data
// table for the goyacc parser front end.
//
// Input : postgres/src/include/parser/kwlist.h  (PG_KEYWORD 4-tuple rows:
//
//	text, terminal name, category, label kind)
//
// Output: internal/sqlparser/keywords_gen.go
//
// The generated table deliberately stores the TERMINAL NAME as a string, not
// its numeric value: token numbers are assigned by goyacc when the grammar
// (grammar/pg_grammar.y) is compiled, and the lexer adapter resolves names
// through the generated parser's yyToknames at init time. This keeps the
// table valid across grammar regenerations without re-running this generator.
//
// Provenance: rows are transcribed verbatim from the read-only oracle tree;
// this program never runs at production runtime. Regenerate with:
//
//	go run ./cmd/gen-kwlist-go
package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
)

var rowRe = regexp.MustCompile(
	`^PG_KEYWORD\("([^"]+)",\s*([A-Z_0-9]+),\s*` +
		`(UNRESERVED_KEYWORD|COL_NAME_KEYWORD|TYPE_FUNC_NAME_KEYWORD|RESERVED_KEYWORD),\s*` +
		`(BARE_LABEL|AS_LABEL)\)`)

type row struct {
	text, token string
	cat, label  string
}

func main() {
	kwlist := flag.String("kwlist", "postgres/src/include/parser/kwlist.h",
		"path to the read-only oracle kwlist.h")
	out := flag.String("out", "internal/sqlparser/keywords_gen.go",
		"output Go file path")
	flag.Parse()

	src, err := os.ReadFile(*kwlist)
	if err != nil {
		fail("read %s: %v", *kwlist, err)
	}

	var rows []row
	for i, line := range strings.Split(string(src), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "PG_KEYWORD(") {
			continue
		}
		m := rowRe.FindStringSubmatch(line)
		if m == nil {
			fail("%s:%d: unrecognized PG_KEYWORD row: %q", *kwlist, i+1, line)
		}
		rows = append(rows, row{text: m[1], token: m[2], cat: m[3], label: m[4]})
	}
	if len(rows) == 0 {
		fail("no PG_KEYWORD rows found in %s", *kwlist)
	}

	seenText, seenTok := map[string]bool{}, map[string]bool{}
	for _, r := range rows {
		if seenText[r.text] {
			fail("duplicate keyword text %q", r.text)
		}
		if seenTok[r.token] {
			fail("duplicate terminal name %q", r.token)
		}
		seenText[r.text], seenTok[r.token] = true, true
	}

	var b strings.Builder
	b.WriteString(`// Code generated by cmd/gen-kwlist-go FROM postgres/src/include/parser/kwlist.h. DO NOT EDIT.
//
// Provenance: read-only PostgreSQL oracle (18.3), file
// postgres/src/include/parser/kwlist.h — see docs/design/not_ralph/.
// Regenerate: go run ./cmd/gen-kwlist-go

package sqlparser

// KeywordCategory mirrors kwlist.h's four category codes. Categories are
// GRAMMATICAL metadata (upstream encodes them via the five list-nonterminals
// unreserved_keyword / col_name_keyword / type_func_name_keyword /
// reserved_keyword / bare_label_keyword); the lexer itself returns the
// keyword token regardless of category.
type KeywordCategory uint8

const (
	CatUnreserved   KeywordCategory = iota // UNRESERVED_KEYWORD
	CatColName                             // COL_NAME_KEYWORD
	CatTypeFuncName                        // TYPE_FUNC_NAME_KEYWORD
	CatReserved                            // RESERVED_KEYWORD
)

// KeywordLabel mirrors kwlist.h's fourth column (where the word may appear
// as a bare label).
type KeywordLabel uint8

const (
	LabelNone KeywordLabel = iota // not listed as a label keyword
	LabelBare                     // BARE_LABEL   -> bare_label_keyword
	LabelAs                       // AS_LABEL     -> as_label_keyword
)

// keywordDef is one transcribed kwlist.h row. Token holds the TERMINAL NAME
// (e.g. "BEGIN_P"); the lexer adapter resolves it to goyacc-assigned number
// via yyToknames at init time — never edit numbers by hand here.
type keywordDef struct {
	Text     string
	Token    string
	Category KeywordCategory
	Label    KeywordLabel
}

`)
	fmt.Fprintf(&b, "// %d rows, source order preserved.\n", len(rows))
	b.WriteString("var keywordDefs = []keywordDef{\n")
	catMap := map[string]string{
		"UNRESERVED_KEYWORD":     "CatUnreserved",
		"COL_NAME_KEYWORD":       "CatColName",
		"TYPE_FUNC_NAME_KEYWORD": "CatTypeFuncName",
		"RESERVED_KEYWORD":       "CatReserved",
	}
	labelMap := map[string]string{
		"BARE_LABEL": "LabelBare",
		"AS_LABEL":   "LabelAs",
	}
	for _, r := range rows {
		fmt.Fprintf(&b, "\t{Text: %q, Token: %q, Category: %s, Label: %s},\n",
			r.text, r.token, catMap[r.cat], labelMap[r.label])
	}
	b.WriteString("}\n")

	if err := os.MkdirAll(dirOf(*out), 0o755); err != nil {
		fail("mkdir: %v", err)
	}
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fail("write %s: %v", *out, err)
	}
	fmt.Fprintf(os.Stderr, "gen-kwlist-go: wrote %d keyword defs to %s\n", len(rows), *out)
}

func dirOf(p string) string {
	if i := strings.LastIndexByte(p, '/'); i >= 0 {
		return p[:i]
	}
	return "."
}

func fail(f string, a ...any) {
	fmt.Fprintf(os.Stderr, "gen-kwlist-go: "+f+"\n", a...)
	os.Exit(1)
}
