package executor

import (
	"fmt"
	"testing"
	"time"

	"github.com/goopg/goopg/internal/catalog"
	"github.com/goopg/goopg/internal/parser"
)

// TestFKConstraintNameAutoGenerated pins the upstream-PG convention for
// auto-generated FK constraint names: `<table>_<col>_fkey`. The error
// message in `assertParentExists` reports this string so isolation-spec
// diffs match the expected text — `violates foreign key constraint
// "<table>_<col>_fkey"`. Regression for the empty-string bug where the
// table-name slot was being passed as "".
func TestFKConstraintNameAutoGenerated(t *testing.T) {
	tbl := &catalog.Table{Name: "fk_parted_pk_2"}
	fk := catalog.ForeignKey{Columns: []string{"a"}, RefTable: "pk_noparted"}
	got := fkConstraintName(tbl, fk)
	want := "fk_parted_pk_2_a_fkey"
	if got != want {
		t.Fatalf("fkConstraintName = %q, want %q", got, want)
	}
}

// TestFKConstraintNameNilTable verifies the synthesised name degrades
// gracefully when the table pointer is nil (defensive — callers should
// pass a real table, but the helper must not panic).
func TestFKConstraintNameNilTable(t *testing.T) {
	fk := catalog.ForeignKey{Columns: []string{"a"}, RefTable: "pk"}
	got := fkConstraintName(nil, fk)
	if got != "_a_fkey" {
		t.Fatalf("fkConstraintName(nil, ...) = %q, want %q", got, "_a_fkey")
	}
}

// TestAttachPartitionFKNameCollisionRenamed pins PG's constraint-name
// disambiguation when ATTACH PARTITION clones a parent FK onto a child that
// already owns a same-named constraint (`parted_fk_naming` in
// postgres/src/test/regress/sql/constraints.sql:447-463): the child
// (`parted_fk_naming_1`) already carries its own CHECK constraint named
// `dummy_constr`, so the cloned FK — which would otherwise also be named
// `dummy_constr` per fkConstraintName's <parent>_<col>_fkey convention only
// when unnamed, but here the parent FK IS explicitly named `dummy_constr` —
// must be renamed to `dummy_constr_1`, mirroring ChooseConstraintName
// (postgres/src/backend/catalog/pg_constraint.c:513), invoked from
// addFkConstraint (postgres/src/backend/commands/tablecmds.c:10748-10760).
// Before the fix, cloneAndValidateAttachPartitionFKs copied the parent FK's
// name onto the clone verbatim with no collision check, so the clone kept
// the colliding name `dummy_constr` instead of becoming `dummy_constr_1`.
func TestAttachPartitionFKNameCollisionRenamed(t *testing.T) {
	ctx, _, cleanup := newDDLFixture(t)
	defer cleanup()

	if err := runDDL(t, ctx, `CREATE TABLE parted_fk_naming (
		id bigint NOT NULL default 1,
		id_abc bigint,
		CONSTRAINT dummy_constr FOREIGN KEY (id_abc)
			REFERENCES parted_fk_naming (id),
		PRIMARY KEY (id)
	) PARTITION BY LIST (id)`); err != nil {
		t.Fatalf("CREATE TABLE parted_fk_naming: %v", err)
	}
	if err := runDDL(t, ctx, `CREATE TABLE parted_fk_naming_1 (
		id bigint NOT NULL default 1,
		id_abc bigint,
		PRIMARY KEY (id),
		CONSTRAINT dummy_constr CHECK (true)
	)`); err != nil {
		t.Fatalf("CREATE TABLE parted_fk_naming_1: %v", err)
	}
	if err := runDDL(t, ctx, `ALTER TABLE parted_fk_naming ATTACH PARTITION parted_fk_naming_1 FOR VALUES IN (1)`); err != nil {
		t.Fatalf("ATTACH PARTITION: %v", err)
	}

	childTbl, ok := ctx.Catalog.LookupTable(parser.ObjectName{Name: "parted_fk_naming_1"})
	if !ok {
		t.Fatal("parted_fk_naming_1 not found")
	}
	if len(childTbl.ForeignKeys) != 1 {
		t.Fatalf("parted_fk_naming_1.ForeignKeys = %d, want 1", len(childTbl.ForeignKeys))
	}
	if got, want := childTbl.ForeignKeys[0].Name, "dummy_constr_1"; got != want {
		t.Errorf("cloned FK name = %q, want %q", got, want)
	}
}

// TestFKValsForDetailFormatsInts pins the DETAIL line value formatting:
// integers render as decimal, strings unquoted, NULLs as "null" — the
// same shape PG uses in `Key (col)=(val) is not present in table "X".`
func TestFKValsForDetailFormatsInts(t *testing.T) {
	vals := []Datum{NewIntDatum(2)}
	got := fkValsForDetail(nil, vals)
	if got != "2" {
		t.Fatalf("fkValsForDetail([2]) = %q, want %q", got, "2")
	}
}

func TestFKValsForDetailFormatsMixedTypes(t *testing.T) {
	vals := []Datum{NewIntDatum(7), NewStringDatum("hello"), NullDatum}
	got := fkValsForDetail(nil, vals)
	want := "7, hello, null"
	if got != want {
		t.Fatalf("fkValsForDetail = %q, want %q", got, want)
	}
}

// TestFKValsForDetailHonorsDateStyle pins the M-NIGHTLY DateStyle follow-up:
// a FK violation's `Key (col)=(val) is not present in table "X".` DETAIL line
// must render a DATE/TIMESTAMP column value through the session's `datestyle`
// GUC exactly like the SELECT/COPY output and CAST-to-text paths already do,
// instead of always calling Datum.Format() (fixed ISO / hardcoded
// Postgres-MDY-only), so the DETAIL text agrees with what the client
// otherwise sees the value rendered as.
func TestFKValsForDetailHonorsDateStyle(t *testing.T) {
	when := time.Date(2026, 7, 14, 9, 5, 3, 0, time.UTC)
	ctx := &Context{GetSetting: func(name string) (string, bool) {
		if name == "datestyle" {
			return "German", true
		}
		return "", false
	}}
	got := fkValsForDetail(ctx, []Datum{NewDateDatum(when)})
	if want := "14.07.2026"; got != want {
		t.Fatalf("fkValsForDetail(German) = %q, want %q", got, want)
	}
	// A nil ctx (no session GUC reachable) falls back to ISO/MDY, matching
	// evalCast's nil-ctx behavior.
	got = fkValsForDetail(nil, []Datum{NewDateDatum(when)})
	if want := "2026-07-14"; got != want {
		t.Fatalf("fkValsForDetail(nil ctx) = %q, want %q", got, want)
	}
}

// TestFKViolationMessageMatchesPGShape composes the message + detail
// pair that assertParentExists builds and pins its byte-shape against
// upstream PG's `insert or update on table "X" violates foreign key
// constraint "Y"\nDETAIL: Key (col)=(val) is not present in table "Z".`
// format. Previous behaviour rendered `on table ""` (empty string slot)
// and a freeform tail that did not match libpq's PQresultErrorField
// MESSAGE / DETAIL split — fk-snapshot.spec L21 surfaced this as a
// load-bearing isolation-test diff.
func TestFKViolationMessageMatchesPGShape(t *testing.T) {
	child := &catalog.Table{Name: "fk_parted_pk_2"}
	fk := catalog.ForeignKey{Columns: []string{"a"}, RefTable: "pk_noparted"}
	msg := fmt.Sprintf("insert or update on table %q violates foreign key constraint %q",
		child.Name, fkConstraintName(child, fk))
	wantMsg := `insert or update on table "fk_parted_pk_2" violates foreign key constraint "fk_parted_pk_2_a_fkey"`
	if msg != wantMsg {
		t.Fatalf("message = %q,\nwant       %q", msg, wantMsg)
	}
	detail := fmt.Sprintf("Key (%s)=(%s) is not present in table %q.",
		"a", fkValsForDetail(nil, []Datum{NewIntDatum(2)}), fk.RefTable)
	wantDetail := `Key (a)=(2) is not present in table "pk_noparted".`
	if detail != wantDetail {
		t.Fatalf("detail = %q,\nwant      %q", detail, wantDetail)
	}
}

// TestFKViolationPartitionRoutedShape pins the dual-source shape used when
// an INSERT into a partitioned parent routes to a leaf partition and that
// leaf's FK check fails: the MESSAGE names the routed leaf
// (`fk_parted_pk_2`), while the constraint name inherits from the
// partitioned parent (`fk_parted_pk_a_fkey`).  This is the L21 expected
// shape in `postgres/src/test/isolation/expected/fk-snapshot.out`.
// Composes the two halves the way assertParentExists does — pinning the
// helper composition without standing up a full executor harness.
// Regression for M0100-0005m (fk-snapshot L21 partition-routed name).
func TestFKViolationPartitionRoutedShape(t *testing.T) {
	parent := &catalog.Table{Name: "fk_parted_pk"}
	leaf := &catalog.Table{Name: "fk_parted_pk_2"}
	fk := catalog.ForeignKey{Columns: []string{"a"}, RefTable: "pk_noparted"}
	msg := fmt.Sprintf("insert or update on table %q violates foreign key constraint %q",
		leaf.Name, fkConstraintName(parent, fk))
	want := `insert or update on table "fk_parted_pk_2" violates foreign key constraint "fk_parted_pk_a_fkey"`
	if msg != want {
		t.Fatalf("partition-routed message = %q,\nwant                       %q", msg, want)
	}
}

