package executor

import (
	"fmt"
	"testing"

	"github.com/goopg/goopg/internal/catalog"
)

// TestFKConstraintNameAutoGenerated pins the upstream-PG convention for
// auto-generated FK constraint names: `<table>_<col>_fkey`. The error
// message in `assertParentExists` reports this string so isolation-spec
// diffs match the expected text — `violates foreign key constraint
// "<table>_<col>_fkey"`. Regression for the empty-string bug where the
// table-name slot was being passed as "".
func TestFKConstraintNameAutoGenerated(t *testing.T) {
	tbl := &catalog.Table{Name: "fk_parted_pk_2"}
	fk := catalog.ForeignKey{Columns: []string{"a"}, RefTable: "pk_noparted"}
	got := fkConstraintName(tbl, fk)
	want := "fk_parted_pk_2_a_fkey"
	if got != want {
		t.Fatalf("fkConstraintName = %q, want %q", got, want)
	}
}

// TestFKConstraintNameNilTable verifies the synthesised name degrades
// gracefully when the table pointer is nil (defensive — callers should
// pass a real table, but the helper must not panic).
func TestFKConstraintNameNilTable(t *testing.T) {
	fk := catalog.ForeignKey{Columns: []string{"a"}, RefTable: "pk"}
	got := fkConstraintName(nil, fk)
	if got != "_a_fkey" {
		t.Fatalf("fkConstraintName(nil, ...) = %q, want %q", got, "_a_fkey")
	}
}

// TestFKValsForDetailFormatsInts pins the DETAIL line value formatting:
// integers render as decimal, strings unquoted, NULLs as "null" — the
// same shape PG uses in `Key (col)=(val) is not present in table "X".`
func TestFKValsForDetailFormatsInts(t *testing.T) {
	vals := []Datum{NewIntDatum(2)}
	got := fkValsForDetail(vals)
	if got != "2" {
		t.Fatalf("fkValsForDetail([2]) = %q, want %q", got, "2")
	}
}

func TestFKValsForDetailFormatsMixedTypes(t *testing.T) {
	vals := []Datum{NewIntDatum(7), NewStringDatum("hello"), NullDatum}
	got := fkValsForDetail(vals)
	want := "7, hello, null"
	if got != want {
		t.Fatalf("fkValsForDetail = %q, want %q", got, want)
	}
}

// TestFKViolationMessageMatchesPGShape composes the message + detail
// pair that assertParentExists builds and pins its byte-shape against
// upstream PG's `insert or update on table "X" violates foreign key
// constraint "Y"\nDETAIL: Key (col)=(val) is not present in table "Z".`
// format. Previous behaviour rendered `on table ""` (empty string slot)
// and a freeform tail that did not match libpq's PQresultErrorField
// MESSAGE / DETAIL split — fk-snapshot.spec L21 surfaced this as a
// load-bearing isolation-test diff.
func TestFKViolationMessageMatchesPGShape(t *testing.T) {
	child := &catalog.Table{Name: "fk_parted_pk_2"}
	fk := catalog.ForeignKey{Columns: []string{"a"}, RefTable: "pk_noparted"}
	msg := fmt.Sprintf("insert or update on table %q violates foreign key constraint %q",
		child.Name, fkConstraintName(child, fk))
	wantMsg := `insert or update on table "fk_parted_pk_2" violates foreign key constraint "fk_parted_pk_2_a_fkey"`
	if msg != wantMsg {
		t.Fatalf("message = %q,\nwant       %q", msg, wantMsg)
	}
	detail := fmt.Sprintf("Key (%s)=(%s) is not present in table %q.",
		"a", fkValsForDetail([]Datum{NewIntDatum(2)}), fk.RefTable)
	wantDetail := `Key (a)=(2) is not present in table "pk_noparted".`
	if detail != wantDetail {
		t.Fatalf("detail = %q,\nwant      %q", detail, wantDetail)
	}
}

