package executor

// sysFKRelationship mirrors PostgreSQL's genbki-generated SysFKRelationship
// (postgres/src/include/catalog/system_fk_info.h) — one row per compiled-in
// foreign-key relationship between two system catalogs. Data transcribed
// verbatim from that header. Backs pg_get_catalog_foreign_keys(), used by
// oidjoins.sql to self-check catalog FK integrity. M0134-0146.
type sysFKRelationship struct {
	FKTable uint32
	PKTable uint32
	FKCols  []string
	PKCols  []string
	IsArray bool
	IsOpt   bool
}

var sysFKRelationships = []sysFKRelationship{
	{FKTable: 1255 /* pg_proc */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"pronamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1255 /* pg_proc */, PKTable: 1260 /* pg_authid */, FKCols: []string{"proowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1255 /* pg_proc */, PKTable: 2612 /* pg_language */, FKCols: []string{"prolang"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1255 /* pg_proc */, PKTable: 1247 /* pg_type */, FKCols: []string{"provariadic"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1255 /* pg_proc */, PKTable: 1255 /* pg_proc */, FKCols: []string{"prosupport"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1255 /* pg_proc */, PKTable: 1247 /* pg_type */, FKCols: []string{"prorettype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1255 /* pg_proc */, PKTable: 1247 /* pg_type */, FKCols: []string{"proargtypes"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: false},
	{FKTable: 1255 /* pg_proc */, PKTable: 1247 /* pg_type */, FKCols: []string{"proallargtypes"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: false},
	{FKTable: 1255 /* pg_proc */, PKTable: 1247 /* pg_type */, FKCols: []string{"protrftypes"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: false},
	{FKTable: 1247 /* pg_type */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"typnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1247 /* pg_type */, PKTable: 1260 /* pg_authid */, FKCols: []string{"typowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1247 /* pg_type */, PKTable: 1259 /* pg_class */, FKCols: []string{"typrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1247 /* pg_type */, PKTable: 1255 /* pg_proc */, FKCols: []string{"typsubscript"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1247 /* pg_type */, PKTable: 1247 /* pg_type */, FKCols: []string{"typelem"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1247 /* pg_type */, PKTable: 1247 /* pg_type */, FKCols: []string{"typarray"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1247 /* pg_type */, PKTable: 1255 /* pg_proc */, FKCols: []string{"typinput"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1247 /* pg_type */, PKTable: 1255 /* pg_proc */, FKCols: []string{"typoutput"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1247 /* pg_type */, PKTable: 1255 /* pg_proc */, FKCols: []string{"typreceive"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1247 /* pg_type */, PKTable: 1255 /* pg_proc */, FKCols: []string{"typsend"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1247 /* pg_type */, PKTable: 1255 /* pg_proc */, FKCols: []string{"typmodin"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1247 /* pg_type */, PKTable: 1255 /* pg_proc */, FKCols: []string{"typmodout"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1247 /* pg_type */, PKTable: 1255 /* pg_proc */, FKCols: []string{"typanalyze"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1247 /* pg_type */, PKTable: 1247 /* pg_type */, FKCols: []string{"typbasetype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1247 /* pg_type */, PKTable: 3456 /* pg_collation */, FKCols: []string{"typcollation"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1249 /* pg_attribute */, PKTable: 1259 /* pg_class */, FKCols: []string{"attrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1249 /* pg_attribute */, PKTable: 1247 /* pg_type */, FKCols: []string{"atttypid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1249 /* pg_attribute */, PKTable: 3456 /* pg_collation */, FKCols: []string{"attcollation"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1259 /* pg_class */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"relnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1259 /* pg_class */, PKTable: 1247 /* pg_type */, FKCols: []string{"reltype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1259 /* pg_class */, PKTable: 1247 /* pg_type */, FKCols: []string{"reloftype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1259 /* pg_class */, PKTable: 1260 /* pg_authid */, FKCols: []string{"relowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1259 /* pg_class */, PKTable: 2601 /* pg_am */, FKCols: []string{"relam"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1259 /* pg_class */, PKTable: 1213 /* pg_tablespace */, FKCols: []string{"reltablespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1259 /* pg_class */, PKTable: 1259 /* pg_class */, FKCols: []string{"reltoastrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1259 /* pg_class */, PKTable: 1259 /* pg_class */, FKCols: []string{"relrewrite"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2604 /* pg_attrdef */, PKTable: 1259 /* pg_class */, FKCols: []string{"adrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2604 /* pg_attrdef */, PKTable: 1249 /* pg_attribute */, FKCols: []string{"adrelid", " adnum"}, PKCols: []string{"attrelid", " attnum"}, IsArray: false, IsOpt: false},
	{FKTable: 2606 /* pg_constraint */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"connamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2606 /* pg_constraint */, PKTable: 1259 /* pg_class */, FKCols: []string{"conrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2606 /* pg_constraint */, PKTable: 1247 /* pg_type */, FKCols: []string{"contypid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2606 /* pg_constraint */, PKTable: 1259 /* pg_class */, FKCols: []string{"conindid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2606 /* pg_constraint */, PKTable: 2606 /* pg_constraint */, FKCols: []string{"conparentid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2606 /* pg_constraint */, PKTable: 1259 /* pg_class */, FKCols: []string{"confrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2606 /* pg_constraint */, PKTable: 2617 /* pg_operator */, FKCols: []string{"conpfeqop"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: false},
	{FKTable: 2606 /* pg_constraint */, PKTable: 2617 /* pg_operator */, FKCols: []string{"conppeqop"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: false},
	{FKTable: 2606 /* pg_constraint */, PKTable: 2617 /* pg_operator */, FKCols: []string{"conffeqop"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: false},
	{FKTable: 2606 /* pg_constraint */, PKTable: 2617 /* pg_operator */, FKCols: []string{"conexclop"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: false},
	{FKTable: 2606 /* pg_constraint */, PKTable: 1249 /* pg_attribute */, FKCols: []string{"conrelid", " conkey"}, PKCols: []string{"attrelid", " attnum"}, IsArray: true, IsOpt: true},
	{FKTable: 2606 /* pg_constraint */, PKTable: 1249 /* pg_attribute */, FKCols: []string{"confrelid", " confkey"}, PKCols: []string{"attrelid", " attnum"}, IsArray: true, IsOpt: false},
	{FKTable: 2611 /* pg_inherits */, PKTable: 1259 /* pg_class */, FKCols: []string{"inhrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2611 /* pg_inherits */, PKTable: 1259 /* pg_class */, FKCols: []string{"inhparent"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2610 /* pg_index */, PKTable: 1259 /* pg_class */, FKCols: []string{"indexrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2610 /* pg_index */, PKTable: 1259 /* pg_class */, FKCols: []string{"indrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2610 /* pg_index */, PKTable: 3456 /* pg_collation */, FKCols: []string{"indcollation"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: true},
	{FKTable: 2610 /* pg_index */, PKTable: 2616 /* pg_opclass */, FKCols: []string{"indclass"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: false},
	{FKTable: 2610 /* pg_index */, PKTable: 1249 /* pg_attribute */, FKCols: []string{"indrelid", " indkey"}, PKCols: []string{"attrelid", " attnum"}, IsArray: true, IsOpt: true},
	{FKTable: 2617 /* pg_operator */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"oprnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2617 /* pg_operator */, PKTable: 1260 /* pg_authid */, FKCols: []string{"oprowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2617 /* pg_operator */, PKTable: 1247 /* pg_type */, FKCols: []string{"oprleft"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2617 /* pg_operator */, PKTable: 1247 /* pg_type */, FKCols: []string{"oprright"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2617 /* pg_operator */, PKTable: 1247 /* pg_type */, FKCols: []string{"oprresult"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2617 /* pg_operator */, PKTable: 2617 /* pg_operator */, FKCols: []string{"oprcom"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2617 /* pg_operator */, PKTable: 2617 /* pg_operator */, FKCols: []string{"oprnegate"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2617 /* pg_operator */, PKTable: 1255 /* pg_proc */, FKCols: []string{"oprcode"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2617 /* pg_operator */, PKTable: 1255 /* pg_proc */, FKCols: []string{"oprrest"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2617 /* pg_operator */, PKTable: 1255 /* pg_proc */, FKCols: []string{"oprjoin"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2753 /* pg_opfamily */, PKTable: 2601 /* pg_am */, FKCols: []string{"opfmethod"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2753 /* pg_opfamily */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"opfnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2753 /* pg_opfamily */, PKTable: 1260 /* pg_authid */, FKCols: []string{"opfowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2616 /* pg_opclass */, PKTable: 2601 /* pg_am */, FKCols: []string{"opcmethod"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2616 /* pg_opclass */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"opcnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2616 /* pg_opclass */, PKTable: 1260 /* pg_authid */, FKCols: []string{"opcowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2616 /* pg_opclass */, PKTable: 2753 /* pg_opfamily */, FKCols: []string{"opcfamily"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2616 /* pg_opclass */, PKTable: 1247 /* pg_type */, FKCols: []string{"opcintype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2616 /* pg_opclass */, PKTable: 1247 /* pg_type */, FKCols: []string{"opckeytype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2601 /* pg_am */, PKTable: 1255 /* pg_proc */, FKCols: []string{"amhandler"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2602 /* pg_amop */, PKTable: 2753 /* pg_opfamily */, FKCols: []string{"amopfamily"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2602 /* pg_amop */, PKTable: 1247 /* pg_type */, FKCols: []string{"amoplefttype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2602 /* pg_amop */, PKTable: 1247 /* pg_type */, FKCols: []string{"amoprighttype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2602 /* pg_amop */, PKTable: 2617 /* pg_operator */, FKCols: []string{"amopopr"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2602 /* pg_amop */, PKTable: 2601 /* pg_am */, FKCols: []string{"amopmethod"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2602 /* pg_amop */, PKTable: 2753 /* pg_opfamily */, FKCols: []string{"amopsortfamily"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2603 /* pg_amproc */, PKTable: 2753 /* pg_opfamily */, FKCols: []string{"amprocfamily"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2603 /* pg_amproc */, PKTable: 1247 /* pg_type */, FKCols: []string{"amproclefttype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2603 /* pg_amproc */, PKTable: 1247 /* pg_type */, FKCols: []string{"amprocrighttype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2603 /* pg_amproc */, PKTable: 1255 /* pg_proc */, FKCols: []string{"amproc"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2612 /* pg_language */, PKTable: 1260 /* pg_authid */, FKCols: []string{"lanowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2612 /* pg_language */, PKTable: 1255 /* pg_proc */, FKCols: []string{"lanplcallfoid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2612 /* pg_language */, PKTable: 1255 /* pg_proc */, FKCols: []string{"laninline"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2612 /* pg_language */, PKTable: 1255 /* pg_proc */, FKCols: []string{"lanvalidator"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2995 /* pg_largeobject_metadata */, PKTable: 1260 /* pg_authid */, FKCols: []string{"lomowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2613 /* pg_largeobject */, PKTable: 2995 /* pg_largeobject_metadata */, FKCols: []string{"loid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 1255 /* pg_proc */, FKCols: []string{"aggfnoid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 1255 /* pg_proc */, FKCols: []string{"aggtransfn"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 1255 /* pg_proc */, FKCols: []string{"aggfinalfn"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 1255 /* pg_proc */, FKCols: []string{"aggcombinefn"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 1255 /* pg_proc */, FKCols: []string{"aggserialfn"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 1255 /* pg_proc */, FKCols: []string{"aggdeserialfn"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 1255 /* pg_proc */, FKCols: []string{"aggmtransfn"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 1255 /* pg_proc */, FKCols: []string{"aggminvtransfn"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 1255 /* pg_proc */, FKCols: []string{"aggmfinalfn"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 2617 /* pg_operator */, FKCols: []string{"aggsortop"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 1247 /* pg_type */, FKCols: []string{"aggtranstype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2600 /* pg_aggregate */, PKTable: 1247 /* pg_type */, FKCols: []string{"aggmtranstype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2619 /* pg_statistic */, PKTable: 1259 /* pg_class */, FKCols: []string{"starelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2619 /* pg_statistic */, PKTable: 2617 /* pg_operator */, FKCols: []string{"staop1"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2619 /* pg_statistic */, PKTable: 2617 /* pg_operator */, FKCols: []string{"staop2"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2619 /* pg_statistic */, PKTable: 2617 /* pg_operator */, FKCols: []string{"staop3"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2619 /* pg_statistic */, PKTable: 2617 /* pg_operator */, FKCols: []string{"staop4"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2619 /* pg_statistic */, PKTable: 2617 /* pg_operator */, FKCols: []string{"staop5"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2619 /* pg_statistic */, PKTable: 3456 /* pg_collation */, FKCols: []string{"stacoll1"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2619 /* pg_statistic */, PKTable: 3456 /* pg_collation */, FKCols: []string{"stacoll2"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2619 /* pg_statistic */, PKTable: 3456 /* pg_collation */, FKCols: []string{"stacoll3"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2619 /* pg_statistic */, PKTable: 3456 /* pg_collation */, FKCols: []string{"stacoll4"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2619 /* pg_statistic */, PKTable: 3456 /* pg_collation */, FKCols: []string{"stacoll5"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2619 /* pg_statistic */, PKTable: 1249 /* pg_attribute */, FKCols: []string{"starelid", " staattnum"}, PKCols: []string{"attrelid", " attnum"}, IsArray: false, IsOpt: false},
	{FKTable: 3381 /* pg_statistic_ext */, PKTable: 1259 /* pg_class */, FKCols: []string{"stxrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3381 /* pg_statistic_ext */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"stxnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3381 /* pg_statistic_ext */, PKTable: 1260 /* pg_authid */, FKCols: []string{"stxowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3381 /* pg_statistic_ext */, PKTable: 1249 /* pg_attribute */, FKCols: []string{"stxrelid", " stxkeys"}, PKCols: []string{"attrelid", " attnum"}, IsArray: true, IsOpt: false},
	{FKTable: 3429 /* pg_statistic_ext_data */, PKTable: 3381 /* pg_statistic_ext */, FKCols: []string{"stxoid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2618 /* pg_rewrite */, PKTable: 1259 /* pg_class */, FKCols: []string{"ev_class"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2620 /* pg_trigger */, PKTable: 1259 /* pg_class */, FKCols: []string{"tgrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2620 /* pg_trigger */, PKTable: 2620 /* pg_trigger */, FKCols: []string{"tgparentid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2620 /* pg_trigger */, PKTable: 1255 /* pg_proc */, FKCols: []string{"tgfoid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2620 /* pg_trigger */, PKTable: 1259 /* pg_class */, FKCols: []string{"tgconstrrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2620 /* pg_trigger */, PKTable: 1259 /* pg_class */, FKCols: []string{"tgconstrindid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2620 /* pg_trigger */, PKTable: 2606 /* pg_constraint */, FKCols: []string{"tgconstraint"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2620 /* pg_trigger */, PKTable: 1249 /* pg_attribute */, FKCols: []string{"tgrelid", " tgattr"}, PKCols: []string{"attrelid", " attnum"}, IsArray: true, IsOpt: false},
	{FKTable: 3466 /* pg_event_trigger */, PKTable: 1260 /* pg_authid */, FKCols: []string{"evtowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3466 /* pg_event_trigger */, PKTable: 1255 /* pg_proc */, FKCols: []string{"evtfoid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2609 /* pg_description */, PKTable: 1259 /* pg_class */, FKCols: []string{"classoid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2605 /* pg_cast */, PKTable: 1247 /* pg_type */, FKCols: []string{"castsource"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2605 /* pg_cast */, PKTable: 1247 /* pg_type */, FKCols: []string{"casttarget"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2605 /* pg_cast */, PKTable: 1255 /* pg_proc */, FKCols: []string{"castfunc"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 3501 /* pg_enum */, PKTable: 1247 /* pg_type */, FKCols: []string{"enumtypid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2615 /* pg_namespace */, PKTable: 1260 /* pg_authid */, FKCols: []string{"nspowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2607 /* pg_conversion */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"connamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2607 /* pg_conversion */, PKTable: 1260 /* pg_authid */, FKCols: []string{"conowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2607 /* pg_conversion */, PKTable: 1255 /* pg_proc */, FKCols: []string{"conproc"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2608 /* pg_depend */, PKTable: 1259 /* pg_class */, FKCols: []string{"classid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2608 /* pg_depend */, PKTable: 1259 /* pg_class */, FKCols: []string{"refclassid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1262 /* pg_database */, PKTable: 1260 /* pg_authid */, FKCols: []string{"datdba"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1262 /* pg_database */, PKTable: 1213 /* pg_tablespace */, FKCols: []string{"dattablespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2964 /* pg_db_role_setting */, PKTable: 1262 /* pg_database */, FKCols: []string{"setdatabase"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2964 /* pg_db_role_setting */, PKTable: 1260 /* pg_authid */, FKCols: []string{"setrole"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1213 /* pg_tablespace */, PKTable: 1260 /* pg_authid */, FKCols: []string{"spcowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1261 /* pg_auth_members */, PKTable: 1260 /* pg_authid */, FKCols: []string{"roleid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1261 /* pg_auth_members */, PKTable: 1260 /* pg_authid */, FKCols: []string{"member"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1261 /* pg_auth_members */, PKTable: 1260 /* pg_authid */, FKCols: []string{"grantor"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1214 /* pg_shdepend */, PKTable: 1262 /* pg_database */, FKCols: []string{"dbid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1214 /* pg_shdepend */, PKTable: 1259 /* pg_class */, FKCols: []string{"classid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1214 /* pg_shdepend */, PKTable: 1259 /* pg_class */, FKCols: []string{"refclassid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2396 /* pg_shdescription */, PKTable: 1259 /* pg_class */, FKCols: []string{"classoid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3602 /* pg_ts_config */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"cfgnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3602 /* pg_ts_config */, PKTable: 1260 /* pg_authid */, FKCols: []string{"cfgowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3602 /* pg_ts_config */, PKTable: 3601 /* pg_ts_parser */, FKCols: []string{"cfgparser"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3603 /* pg_ts_config_map */, PKTable: 3602 /* pg_ts_config */, FKCols: []string{"mapcfg"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3603 /* pg_ts_config_map */, PKTable: 3600 /* pg_ts_dict */, FKCols: []string{"mapdict"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3600 /* pg_ts_dict */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"dictnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3600 /* pg_ts_dict */, PKTable: 1260 /* pg_authid */, FKCols: []string{"dictowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3600 /* pg_ts_dict */, PKTable: 3764 /* pg_ts_template */, FKCols: []string{"dicttemplate"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3601 /* pg_ts_parser */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"prsnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3601 /* pg_ts_parser */, PKTable: 1255 /* pg_proc */, FKCols: []string{"prsstart"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3601 /* pg_ts_parser */, PKTable: 1255 /* pg_proc */, FKCols: []string{"prstoken"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3601 /* pg_ts_parser */, PKTable: 1255 /* pg_proc */, FKCols: []string{"prsend"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3601 /* pg_ts_parser */, PKTable: 1255 /* pg_proc */, FKCols: []string{"prsheadline"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 3601 /* pg_ts_parser */, PKTable: 1255 /* pg_proc */, FKCols: []string{"prslextype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3764 /* pg_ts_template */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"tmplnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3764 /* pg_ts_template */, PKTable: 1255 /* pg_proc */, FKCols: []string{"tmplinit"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 3764 /* pg_ts_template */, PKTable: 1255 /* pg_proc */, FKCols: []string{"tmpllexize"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3079 /* pg_extension */, PKTable: 1260 /* pg_authid */, FKCols: []string{"extowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3079 /* pg_extension */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"extnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3079 /* pg_extension */, PKTable: 1259 /* pg_class */, FKCols: []string{"extconfig"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: false},
	{FKTable: 2328 /* pg_foreign_data_wrapper */, PKTable: 1260 /* pg_authid */, FKCols: []string{"fdwowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2328 /* pg_foreign_data_wrapper */, PKTable: 1255 /* pg_proc */, FKCols: []string{"fdwhandler"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2328 /* pg_foreign_data_wrapper */, PKTable: 1255 /* pg_proc */, FKCols: []string{"fdwvalidator"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1417 /* pg_foreign_server */, PKTable: 1260 /* pg_authid */, FKCols: []string{"srvowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1417 /* pg_foreign_server */, PKTable: 2328 /* pg_foreign_data_wrapper */, FKCols: []string{"srvfdw"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 1418 /* pg_user_mapping */, PKTable: 1260 /* pg_authid */, FKCols: []string{"umuser"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 1418 /* pg_user_mapping */, PKTable: 1417 /* pg_foreign_server */, FKCols: []string{"umserver"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3118 /* pg_foreign_table */, PKTable: 1259 /* pg_class */, FKCols: []string{"ftrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3118 /* pg_foreign_table */, PKTable: 1417 /* pg_foreign_server */, FKCols: []string{"ftserver"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3256 /* pg_policy */, PKTable: 1259 /* pg_class */, FKCols: []string{"polrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3256 /* pg_policy */, PKTable: 1260 /* pg_authid */, FKCols: []string{"polroles"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: true},
	{FKTable: 826 /* pg_default_acl */, PKTable: 1260 /* pg_authid */, FKCols: []string{"defaclrole"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 826 /* pg_default_acl */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"defaclnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 3394 /* pg_init_privs */, PKTable: 1259 /* pg_class */, FKCols: []string{"classoid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3596 /* pg_seclabel */, PKTable: 1259 /* pg_class */, FKCols: []string{"classoid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3592 /* pg_shseclabel */, PKTable: 1259 /* pg_class */, FKCols: []string{"classoid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3456 /* pg_collation */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"collnamespace"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3456 /* pg_collation */, PKTable: 1260 /* pg_authid */, FKCols: []string{"collowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3350 /* pg_partitioned_table */, PKTable: 1259 /* pg_class */, FKCols: []string{"partrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3350 /* pg_partitioned_table */, PKTable: 1259 /* pg_class */, FKCols: []string{"partdefid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 3350 /* pg_partitioned_table */, PKTable: 2616 /* pg_opclass */, FKCols: []string{"partclass"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: false},
	{FKTable: 3350 /* pg_partitioned_table */, PKTable: 3456 /* pg_collation */, FKCols: []string{"partcollation"}, PKCols: []string{"oid"}, IsArray: true, IsOpt: true},
	{FKTable: 3350 /* pg_partitioned_table */, PKTable: 1249 /* pg_attribute */, FKCols: []string{"partrelid", " partattrs"}, PKCols: []string{"attrelid", " attnum"}, IsArray: true, IsOpt: true},
	{FKTable: 3541 /* pg_range */, PKTable: 1247 /* pg_type */, FKCols: []string{"rngtypid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3541 /* pg_range */, PKTable: 1247 /* pg_type */, FKCols: []string{"rngsubtype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3541 /* pg_range */, PKTable: 1247 /* pg_type */, FKCols: []string{"rngmultitypid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3541 /* pg_range */, PKTable: 3456 /* pg_collation */, FKCols: []string{"rngcollation"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 3541 /* pg_range */, PKTable: 2616 /* pg_opclass */, FKCols: []string{"rngsubopc"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3541 /* pg_range */, PKTable: 1255 /* pg_proc */, FKCols: []string{"rngcanonical"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 3541 /* pg_range */, PKTable: 1255 /* pg_proc */, FKCols: []string{"rngsubdiff"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 3576 /* pg_transform */, PKTable: 1247 /* pg_type */, FKCols: []string{"trftype"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3576 /* pg_transform */, PKTable: 2612 /* pg_language */, FKCols: []string{"trflang"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 3576 /* pg_transform */, PKTable: 1255 /* pg_proc */, FKCols: []string{"trffromsql"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 3576 /* pg_transform */, PKTable: 1255 /* pg_proc */, FKCols: []string{"trftosql"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: true},
	{FKTable: 2224 /* pg_sequence */, PKTable: 1259 /* pg_class */, FKCols: []string{"seqrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 2224 /* pg_sequence */, PKTable: 1247 /* pg_type */, FKCols: []string{"seqtypid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 6104 /* pg_publication */, PKTable: 1260 /* pg_authid */, FKCols: []string{"pubowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 6237 /* pg_publication_namespace */, PKTable: 6104 /* pg_publication */, FKCols: []string{"pnpubid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 6237 /* pg_publication_namespace */, PKTable: 2615 /* pg_namespace */, FKCols: []string{"pnnspid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 6106 /* pg_publication_rel */, PKTable: 6104 /* pg_publication */, FKCols: []string{"prpubid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 6106 /* pg_publication_rel */, PKTable: 1259 /* pg_class */, FKCols: []string{"prrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 6100 /* pg_subscription */, PKTable: 1262 /* pg_database */, FKCols: []string{"subdbid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 6100 /* pg_subscription */, PKTable: 1260 /* pg_authid */, FKCols: []string{"subowner"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 6102 /* pg_subscription_rel */, PKTable: 6100 /* pg_subscription */, FKCols: []string{"srsubid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
	{FKTable: 6102 /* pg_subscription_rel */, PKTable: 1259 /* pg_class */, FKCols: []string{"srrelid"}, PKCols: []string{"oid"}, IsArray: false, IsOpt: false},
}
