package executor

// pg_nonimmutable_builtins.go — the set of pg_catalog function NAMES whose
// every pg_proc.dat overload is declared non-IMMUTABLE (provolatile 's' or
// 'v').
//
// Why a name set and not an OID/signature table: goopg's DDL-time expression
// trees (`parser.FuncCall`) are unresolved — there is no overload resolution
// and no argument-type inference at CREATE INDEX / CREATE TABLE … PARTITION BY
// time, so the only key available is the bare function name. PG asks the
// resolved pg_proc row (`func_volatile(funcid) != PROVOLATILE_IMMUTABLE`,
// postgres/src/backend/optimizer/util/clauses.c contain_mutable_functions);
// goopg approximates it by name.
//
// The approximation is deliberately ASYMMETRIC, and the asymmetry is the whole
// design: 31 pg_proc.dat names carry BOTH immutable and non-immutable
// overloads (`date_trunc`, `to_timestamp`, `age`, `length`, `timezone`,
// `extract`, `quote_literal`, …). Listing those would reject index expressions
// PostgreSQL accepts — `date_trunc('day', ts)` on a plain `timestamp` is
// IMMUTABLE — which is a strictly worse failure than missing one, because it
// breaks working DDL rather than admitting DDL PG would have rejected. So a
// mixed-volatility name is EXCLUDED here and treated as immutable; the residual
// false-negative is recorded in `.ralph/deferral_ledger.md` (M0134-0170a).
//
// Derivation (re-derived and asserted by TestNonImmutableBuiltinsMatchPgProcDat
// in index_mutability_test.go, which reads the in-tree oracle directly,
// so this table cannot silently drift from PG 18.3):
//
//	group postgres/src/include/catalog/pg_proc.dat entries by proname;
//	keep a name iff no entry for it has provolatile 'i'
//	(pg_proc.h declares BKI_DEFAULT(i), so an omitted field means 'i').
var nonImmutableBuiltinNames = func() map[string]bool {
	m := make(map[string]bool, len(nonImmutableBuiltinNameList))
	for _, n := range nonImmutableBuiltinNameList {
		m[n] = true
	}
	return m
}()

// nonImmutableBuiltinNameList is the raw, sorted extraction described above.
// Names are compared case-insensitively by the callers (SQL folds unquoted
// identifiers to lower case; the RI_FKey_* trigger functions are the only
// mixed-case entries and are unreachable from an expression anyway).
var nonImmutableBuiltinNameList = []string{
	"RI_FKey_cascade_del", "RI_FKey_cascade_upd", "RI_FKey_check_ins",
	"RI_FKey_check_upd", "RI_FKey_noaction_del", "RI_FKey_noaction_upd",
	"RI_FKey_restrict_del", "RI_FKey_restrict_upd", "RI_FKey_setdefault_del",
	"RI_FKey_setdefault_upd", "RI_FKey_setnull_del", "RI_FKey_setnull_upd",
	"aclexplode", "aclitemin", "aclitemout", "amvalidate", "anyarray_out",
	"anyarray_recv", "anyarray_send", "anycompatiblearray_out",
	"anycompatiblearray_recv", "anycompatiblearray_send",
	"anycompatiblemultirange_in", "anycompatiblemultirange_out",
	"anycompatiblerange_in", "anycompatiblerange_out", "anyenum_out",
	"anymultirange_in", "anymultirange_out", "anyrange_in", "anyrange_out",
	"anytextcat", "areajoinsel", "areasel", "array_in", "array_out",
	"array_recv", "array_sample", "array_send", "array_shuffle",
	"array_to_json", "array_to_string", "array_typanalyze", "arraycontjoinsel",
	"arraycontsel", "bernoulli", "binary_upgrade_add_sub_rel_state",
	"binary_upgrade_create_empty_extension",
	"binary_upgrade_logical_slot_has_caught_up",
	"binary_upgrade_replorigin_advance", "binary_upgrade_set_missing_value",
	"binary_upgrade_set_next_array_pg_type_oid",
	"binary_upgrade_set_next_heap_pg_class_oid",
	"binary_upgrade_set_next_heap_relfilenode",
	"binary_upgrade_set_next_index_pg_class_oid",
	"binary_upgrade_set_next_index_relfilenode",
	"binary_upgrade_set_next_multirange_array_pg_type_oid",
	"binary_upgrade_set_next_multirange_pg_type_oid",
	"binary_upgrade_set_next_pg_authid_oid",
	"binary_upgrade_set_next_pg_enum_oid",
	"binary_upgrade_set_next_pg_tablespace_oid",
	"binary_upgrade_set_next_pg_type_oid",
	"binary_upgrade_set_next_toast_pg_class_oid",
	"binary_upgrade_set_next_toast_relfilenode",
	"binary_upgrade_set_record_init_privs", "bpcharrecv", "bpcharsend",
	"brin_bloom_summary_recv", "brin_bloom_summary_send",
	"brin_desummarize_range", "brin_minmax_multi_summary_recv",
	"brin_minmax_multi_summary_send", "brin_summarize_new_values",
	"brin_summarize_range", "brinhandler", "bthandler", "cash_in", "cash_out",
	"clock_timestamp", "col_description", "concat", "concat_ws", "contjoinsel",
	"contsel", "convert", "convert_from", "convert_to", "cstring_recv",
	"cstring_send", "current_database", "current_query", "current_schema",
	"current_schemas", "current_setting", "current_user", "currtid2",
	"currval", "cursor_to_xml", "cursor_to_xmlschema", "database_to_xml",
	"database_to_xml_and_xmlschema", "database_to_xmlschema",
	"date_cmp_timestamptz", "date_eq_timestamptz", "date_ge_timestamptz",
	"date_gt_timestamptz", "date_in", "date_le_timestamptz",
	"date_lt_timestamptz", "date_ne_timestamptz", "date_out", "domain_in",
	"domain_recv", "enum_first", "enum_in", "enum_last", "enum_out",
	"enum_range", "enum_recv", "enum_send", "eqjoinsel", "eqsel",
	"fmgr_c_validator", "fmgr_internal_validator", "fmgr_sql_validator",
	"format", "format_type", "gen_random_uuid", "get_current_ts_config",
	"getdatabaseencoding", "getpgusername", "gin_clean_pending_list",
	"ginhandler", "gisthandler", "has_any_column_privilege",
	"has_column_privilege", "has_database_privilege",
	"has_foreign_data_wrapper_privilege", "has_function_privilege",
	"has_language_privilege", "has_largeobject_privilege",
	"has_parameter_privilege", "has_schema_privilege",
	"has_sequence_privilege", "has_server_privilege", "has_table_privilege",
	"has_tablespace_privilege", "has_type_privilege", "hashhandler",
	"heap_tableam_handler", "iclikejoinsel", "iclikesel", "icnlikejoinsel",
	"icnlikesel", "icregexeqjoinsel", "icregexeqsel", "icregexnejoinsel",
	"icregexnesel", "inet_client_addr", "inet_client_port", "inet_server_addr",
	"inet_server_port", "interval_in", "interval_out",
	"interval_pl_timestamptz", "json_agg", "json_agg_strict",
	"json_agg_strict_transfn", "json_agg_transfn", "json_build_array",
	"json_build_object", "json_object_agg", "json_object_agg_strict",
	"json_object_agg_strict_transfn", "json_object_agg_transfn",
	"json_object_agg_unique", "json_object_agg_unique_strict",
	"json_object_agg_unique_strict_transfn", "json_object_agg_unique_transfn",
	"json_populate_record", "json_populate_recordset", "json_to_record",
	"json_to_recordset", "jsonb_agg", "jsonb_agg_finalfn", "jsonb_agg_strict",
	"jsonb_agg_strict_transfn", "jsonb_agg_transfn", "jsonb_build_array",
	"jsonb_build_object", "jsonb_object_agg_finalfn",
	"jsonb_object_agg_strict_transfn", "jsonb_object_agg_transfn",
	"jsonb_object_agg_unique_strict_transfn",
	"jsonb_object_agg_unique_transfn", "jsonb_path_exists_tz",
	"jsonb_path_match_tz", "jsonb_path_query_array_tz",
	"jsonb_path_query_first_tz", "jsonb_path_query_tz",
	"jsonb_populate_record", "jsonb_populate_record_valid",
	"jsonb_populate_recordset", "jsonb_to_record", "jsonb_to_recordset",
	"lastval", "likejoinsel", "likesel", "lo_close", "lo_creat", "lo_create",
	"lo_export", "lo_from_bytea", "lo_get", "lo_import", "lo_lseek",
	"lo_lseek64", "lo_open", "lo_put", "lo_tell", "lo_tell64", "lo_truncate",
	"lo_truncate64", "lo_unlink", "loread", "lowrite", "make_timestamptz",
	"matchingjoinsel", "matchingsel", "money", "multirange_in",
	"multirange_out", "multirange_recv", "multirange_send",
	"multirange_typanalyze", "multirangesel", "mxid_age", "namerecv",
	"namesend", "neqjoinsel", "neqsel", "networkjoinsel", "networksel",
	"nextval", "nlikejoinsel", "nlikesel", "now", "obj_description",
	"oidvectortypes", "pg_advisory_lock", "pg_advisory_lock_shared",
	"pg_advisory_unlock", "pg_advisory_unlock_all",
	"pg_advisory_unlock_shared", "pg_advisory_xact_lock",
	"pg_advisory_xact_lock_shared", "pg_available_extension_versions",
	"pg_available_extensions", "pg_available_wal_summaries", "pg_backend_pid",
	"pg_backup_start", "pg_backup_stop", "pg_basetype", "pg_blocking_pids",
	"pg_cancel_backend", "pg_char_to_encoding", "pg_clear_attribute_stats",
	"pg_clear_relation_stats", "pg_client_encoding",
	"pg_collation_actual_version", "pg_collation_for",
	"pg_collation_is_visible", "pg_column_compression",
	"pg_column_is_updatable", "pg_column_size", "pg_column_toast_chunk_id",
	"pg_conf_load_time", "pg_config", "pg_control_checkpoint",
	"pg_control_init", "pg_control_recovery", "pg_control_system",
	"pg_conversion_is_visible", "pg_copy_logical_replication_slot",
	"pg_copy_physical_replication_slot", "pg_create_logical_replication_slot",
	"pg_create_physical_replication_slot", "pg_create_restore_point",
	"pg_current_logfile", "pg_current_snapshot", "pg_current_wal_flush_lsn",
	"pg_current_wal_insert_lsn", "pg_current_wal_lsn", "pg_current_xact_id",
	"pg_current_xact_id_if_assigned", "pg_cursor",
	"pg_database_collation_actual_version", "pg_database_size",
	"pg_dependencies_recv", "pg_dependencies_send", "pg_describe_object",
	"pg_drop_replication_slot", "pg_encoding_to_char",
	"pg_event_trigger_ddl_commands", "pg_event_trigger_dropped_objects",
	"pg_event_trigger_table_rewrite_oid",
	"pg_event_trigger_table_rewrite_reason", "pg_export_snapshot",
	"pg_extension_config_dump", "pg_extension_update_paths",
	"pg_filenode_relation", "pg_function_is_visible", "pg_get_acl",
	"pg_get_aios", "pg_get_backend_memory_contexts",
	"pg_get_catalog_foreign_keys", "pg_get_constraintdef", "pg_get_expr",
	"pg_get_function_arg_default", "pg_get_function_arguments",
	"pg_get_function_identity_arguments", "pg_get_function_result",
	"pg_get_function_sqlbody", "pg_get_functiondef", "pg_get_indexdef",
	"pg_get_keywords", "pg_get_loaded_modules", "pg_get_multixact_members",
	"pg_get_object_address", "pg_get_partition_constraintdef",
	"pg_get_partkeydef", "pg_get_publication_tables",
	"pg_get_replica_identity_index", "pg_get_replication_slots",
	"pg_get_ruledef", "pg_get_sequence_data", "pg_get_serial_sequence",
	"pg_get_shmem_allocations", "pg_get_shmem_allocations_numa",
	"pg_get_statisticsobjdef", "pg_get_statisticsobjdef_columns",
	"pg_get_statisticsobjdef_expressions", "pg_get_triggerdef",
	"pg_get_userbyid", "pg_get_viewdef", "pg_get_wait_events",
	"pg_get_wal_replay_pause_state", "pg_get_wal_resource_managers",
	"pg_get_wal_summarizer_state", "pg_has_role", "pg_hba_file_rules",
	"pg_ident_file_mappings", "pg_identify_object",
	"pg_identify_object_as_address", "pg_import_system_collations",
	"pg_index_column_has_property", "pg_index_has_property",
	"pg_indexam_has_property", "pg_indexes_size", "pg_input_error_info",
	"pg_input_is_valid", "pg_is_in_recovery", "pg_is_other_temp_schema",
	"pg_is_wal_replay_paused", "pg_isolation_test_session_is_blocked",
	"pg_jit_available", "pg_last_committed_xact", "pg_last_wal_receive_lsn",
	"pg_last_wal_replay_lsn", "pg_last_xact_replay_timestamp",
	"pg_listening_channels", "pg_lock_status",
	"pg_log_backend_memory_contexts", "pg_log_standby_snapshot",
	"pg_logical_emit_message", "pg_logical_slot_get_binary_changes",
	"pg_logical_slot_get_changes", "pg_logical_slot_peek_binary_changes",
	"pg_logical_slot_peek_changes", "pg_ls_archive_statusdir", "pg_ls_dir",
	"pg_ls_logdir", "pg_ls_logicalmapdir", "pg_ls_logicalsnapdir",
	"pg_ls_replslotdir", "pg_ls_summariesdir", "pg_ls_tmpdir", "pg_ls_waldir",
	"pg_mcv_list_items", "pg_mcv_list_recv", "pg_mcv_list_send",
	"pg_my_temp_schema", "pg_ndistinct_recv", "pg_ndistinct_send",
	"pg_nextoid", "pg_node_tree_recv", "pg_node_tree_send",
	"pg_notification_queue_usage", "pg_notify", "pg_numa_available",
	"pg_opclass_is_visible", "pg_operator_is_visible",
	"pg_opfamily_is_visible", "pg_options_to_table", "pg_partition_ancestors",
	"pg_partition_tree", "pg_postmaster_start_time", "pg_prepared_statement",
	"pg_prepared_xact", "pg_promote", "pg_read_binary_file", "pg_read_file",
	"pg_relation_filenode", "pg_relation_filepath",
	"pg_relation_is_publishable", "pg_relation_is_updatable",
	"pg_relation_size", "pg_reload_conf", "pg_replication_origin_advance",
	"pg_replication_origin_create", "pg_replication_origin_drop",
	"pg_replication_origin_oid", "pg_replication_origin_progress",
	"pg_replication_origin_session_is_setup",
	"pg_replication_origin_session_progress",
	"pg_replication_origin_session_reset",
	"pg_replication_origin_session_setup", "pg_replication_origin_xact_reset",
	"pg_replication_origin_xact_setup", "pg_replication_slot_advance",
	"pg_restore_attribute_stats", "pg_restore_relation_stats",
	"pg_rotate_logfile", "pg_safe_snapshot_blocking_pids",
	"pg_sequence_last_value", "pg_sequence_parameters",
	"pg_settings_get_flags", "pg_show_all_file_settings",
	"pg_show_all_settings", "pg_show_replication_origin_status", "pg_sleep",
	"pg_sleep_for", "pg_sleep_until", "pg_split_walfile_name",
	"pg_stat_clear_snapshot", "pg_stat_file", "pg_stat_force_next_flush",
	"pg_stat_get_activity", "pg_stat_get_analyze_count",
	"pg_stat_get_archiver", "pg_stat_get_autoanalyze_count",
	"pg_stat_get_autovacuum_count", "pg_stat_get_backend_activity",
	"pg_stat_get_backend_activity_start", "pg_stat_get_backend_client_addr",
	"pg_stat_get_backend_client_port", "pg_stat_get_backend_dbid",
	"pg_stat_get_backend_idset", "pg_stat_get_backend_io",
	"pg_stat_get_backend_pid", "pg_stat_get_backend_start",
	"pg_stat_get_backend_subxact", "pg_stat_get_backend_userid",
	"pg_stat_get_backend_wait_event", "pg_stat_get_backend_wait_event_type",
	"pg_stat_get_backend_wal", "pg_stat_get_backend_xact_start",
	"pg_stat_get_bgwriter_buf_written_clean",
	"pg_stat_get_bgwriter_maxwritten_clean",
	"pg_stat_get_bgwriter_stat_reset_time", "pg_stat_get_blocks_fetched",
	"pg_stat_get_blocks_hit", "pg_stat_get_buf_alloc",
	"pg_stat_get_checkpointer_buffers_written",
	"pg_stat_get_checkpointer_num_performed",
	"pg_stat_get_checkpointer_num_requested",
	"pg_stat_get_checkpointer_num_timed",
	"pg_stat_get_checkpointer_restartpoints_performed",
	"pg_stat_get_checkpointer_restartpoints_requested",
	"pg_stat_get_checkpointer_restartpoints_timed",
	"pg_stat_get_checkpointer_slru_written",
	"pg_stat_get_checkpointer_stat_reset_time",
	"pg_stat_get_checkpointer_sync_time",
	"pg_stat_get_checkpointer_write_time", "pg_stat_get_db_active_time",
	"pg_stat_get_db_blk_read_time", "pg_stat_get_db_blk_write_time",
	"pg_stat_get_db_blocks_fetched", "pg_stat_get_db_blocks_hit",
	"pg_stat_get_db_checksum_failures", "pg_stat_get_db_checksum_last_failure",
	"pg_stat_get_db_conflict_all", "pg_stat_get_db_conflict_bufferpin",
	"pg_stat_get_db_conflict_lock", "pg_stat_get_db_conflict_logicalslot",
	"pg_stat_get_db_conflict_snapshot",
	"pg_stat_get_db_conflict_startup_deadlock",
	"pg_stat_get_db_conflict_tablespace", "pg_stat_get_db_deadlocks",
	"pg_stat_get_db_idle_in_transaction_time", "pg_stat_get_db_numbackends",
	"pg_stat_get_db_parallel_workers_launched",
	"pg_stat_get_db_parallel_workers_to_launch", "pg_stat_get_db_session_time",
	"pg_stat_get_db_sessions", "pg_stat_get_db_sessions_abandoned",
	"pg_stat_get_db_sessions_fatal", "pg_stat_get_db_sessions_killed",
	"pg_stat_get_db_stat_reset_time", "pg_stat_get_db_temp_bytes",
	"pg_stat_get_db_temp_files", "pg_stat_get_db_tuples_deleted",
	"pg_stat_get_db_tuples_fetched", "pg_stat_get_db_tuples_inserted",
	"pg_stat_get_db_tuples_returned", "pg_stat_get_db_tuples_updated",
	"pg_stat_get_db_xact_commit", "pg_stat_get_db_xact_rollback",
	"pg_stat_get_dead_tuples", "pg_stat_get_function_calls",
	"pg_stat_get_function_self_time", "pg_stat_get_function_total_time",
	"pg_stat_get_ins_since_vacuum", "pg_stat_get_io",
	"pg_stat_get_last_analyze_time", "pg_stat_get_last_autoanalyze_time",
	"pg_stat_get_last_autovacuum_time", "pg_stat_get_last_vacuum_time",
	"pg_stat_get_lastscan", "pg_stat_get_live_tuples",
	"pg_stat_get_mod_since_analyze", "pg_stat_get_numscans",
	"pg_stat_get_progress_info", "pg_stat_get_recovery_prefetch",
	"pg_stat_get_replication_slot", "pg_stat_get_slru",
	"pg_stat_get_snapshot_timestamp", "pg_stat_get_subscription",
	"pg_stat_get_subscription_stats", "pg_stat_get_total_analyze_time",
	"pg_stat_get_total_autoanalyze_time", "pg_stat_get_total_autovacuum_time",
	"pg_stat_get_total_vacuum_time", "pg_stat_get_tuples_deleted",
	"pg_stat_get_tuples_fetched", "pg_stat_get_tuples_hot_updated",
	"pg_stat_get_tuples_inserted", "pg_stat_get_tuples_newpage_updated",
	"pg_stat_get_tuples_returned", "pg_stat_get_tuples_updated",
	"pg_stat_get_vacuum_count", "pg_stat_get_wal", "pg_stat_get_wal_receiver",
	"pg_stat_get_wal_senders", "pg_stat_get_xact_blocks_fetched",
	"pg_stat_get_xact_blocks_hit", "pg_stat_get_xact_function_calls",
	"pg_stat_get_xact_function_self_time",
	"pg_stat_get_xact_function_total_time", "pg_stat_get_xact_numscans",
	"pg_stat_get_xact_tuples_deleted", "pg_stat_get_xact_tuples_fetched",
	"pg_stat_get_xact_tuples_hot_updated", "pg_stat_get_xact_tuples_inserted",
	"pg_stat_get_xact_tuples_newpage_updated",
	"pg_stat_get_xact_tuples_returned", "pg_stat_get_xact_tuples_updated",
	"pg_stat_have_stats", "pg_stat_reset", "pg_stat_reset_backend_stats",
	"pg_stat_reset_replication_slot", "pg_stat_reset_shared",
	"pg_stat_reset_single_function_counters",
	"pg_stat_reset_single_table_counters", "pg_stat_reset_slru",
	"pg_stat_reset_subscription_stats", "pg_statistics_obj_is_visible",
	"pg_stop_making_pinned_objects", "pg_switch_wal",
	"pg_sync_replication_slots", "pg_table_is_visible", "pg_table_size",
	"pg_tablespace_databases", "pg_tablespace_location", "pg_tablespace_size",
	"pg_terminate_backend", "pg_timezone_abbrevs_abbrevs",
	"pg_timezone_abbrevs_zone", "pg_timezone_names", "pg_total_relation_size",
	"pg_trigger_depth", "pg_try_advisory_lock", "pg_try_advisory_lock_shared",
	"pg_try_advisory_xact_lock", "pg_try_advisory_xact_lock_shared",
	"pg_ts_config_is_visible", "pg_ts_dict_is_visible",
	"pg_ts_parser_is_visible", "pg_ts_template_is_visible",
	"pg_type_is_visible", "pg_typeof", "pg_wal_replay_pause",
	"pg_wal_replay_resume", "pg_wal_summary_contents",
	"pg_xact_commit_timestamp", "pg_xact_commit_timestamp_origin",
	"pg_xact_status", "positionjoinsel", "positionsel", "prefixjoinsel",
	"prefixsel", "query_to_xml", "query_to_xml_and_xmlschema",
	"query_to_xmlschema", "random", "random_normal", "range_in", "range_out",
	"range_recv", "range_send", "range_typanalyze", "rangesel", "record_in",
	"record_out", "record_recv", "record_send", "regclass", "regclassin",
	"regclassout", "regcollationin", "regcollationout", "regconfigin",
	"regconfigout", "regdictionaryin", "regdictionaryout", "regexeqjoinsel",
	"regexeqsel", "regexnejoinsel", "regexnesel", "regnamespacein",
	"regnamespaceout", "regoperatorin", "regoperatorout", "regoperin",
	"regoperout", "regprocedurein", "regprocedureout", "regprocin",
	"regprocout", "regrolein", "regroleout", "regtypein", "regtypeout",
	"row_security_active", "row_to_json", "scalargejoinsel", "scalargesel",
	"scalargtjoinsel", "scalargtsel", "scalarlejoinsel", "scalarlesel",
	"scalarltjoinsel", "scalarltsel", "schema_to_xml",
	"schema_to_xml_and_xmlschema", "schema_to_xmlschema", "session_user",
	"set_config", "setseed", "setval", "shobj_description", "spghandler",
	"statement_timestamp", "suppress_redundant_updates_trigger", "system",
	"system_user", "table_to_xml", "table_to_xml_and_xmlschema",
	"table_to_xmlschema", "textanycat", "textrecv", "textsend", "time_in",
	"timeofday", "timestamp_cmp_timestamptz", "timestamp_eq_timestamptz",
	"timestamp_ge_timestamptz", "timestamp_gt_timestamptz", "timestamp_in",
	"timestamp_le_timestamptz", "timestamp_lt_timestamptz",
	"timestamp_ne_timestamptz", "timestamp_out", "timestamptz_cmp_date",
	"timestamptz_cmp_timestamp", "timestamptz_eq_date",
	"timestamptz_eq_timestamp", "timestamptz_ge_date",
	"timestamptz_ge_timestamp", "timestamptz_gt_date",
	"timestamptz_gt_timestamp", "timestamptz_in", "timestamptz_le_date",
	"timestamptz_le_timestamp", "timestamptz_lt_date",
	"timestamptz_lt_timestamp", "timestamptz_mi_interval",
	"timestamptz_ne_date", "timestamptz_ne_timestamp", "timestamptz_out",
	"timestamptz_pl_interval", "timetz_in", "to_char", "to_date", "to_json",
	"to_jsonb", "to_number", "to_regclass", "to_regcollation",
	"to_regnamespace", "to_regoper", "to_regoperator", "to_regproc",
	"to_regprocedure", "to_regrole", "to_regtype", "to_regtypemod",
	"transaction_timestamp", "ts_debug", "ts_match_tq", "ts_match_tt",
	"ts_stat", "ts_typanalyze", "tsmatchjoinsel", "tsmatchsel",
	"tsvector_update_trigger", "tsvector_update_trigger_column",
	"txid_current", "txid_current_if_assigned", "txid_current_snapshot",
	"txid_status", "unique_key_recheck", "uuidv4", "uuidv7", "varcharrecv",
	"varcharsend", "version", "xml", "xml_in", "xml_is_well_formed",
	"xml_recv", "xml_send",
}
