package misc

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestAlterSystemSetConfigFile pins M0122-0008: ALTER SYSTEM rewrites
// postgresql.auto.conf exactly as guc.c AlterSystemSetConfigFile does — header,
// `name = 'value'` lines in update order with quotes and backslashes doubled
// (escape_single_quotes_ascii), an existing entry replaced (moved to the end),
// RESET removing it and RESET ALL emptying the file. The expected bytes are
// what a PG 18.3 cluster wrote for the same statements.
func TestAlterSystemSetConfigFile(t *testing.T) {
	r := BuildDefaultRegistry()
	dir := t.TempDir()
	path := filepath.Join(dir, AutoConfFileName)
	read := func() string {
		b, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		return string(b)
	}
	const header = "# Do not edit this file manually!\n# It will be overwritten by the ALTER SYSTEM command.\n"
	must := func(name, value string, set, resetAll bool) {
		t.Helper()
		if err := r.AlterSystemSetConfigFile(dir, name, value, set, resetAll); err != nil {
			t.Fatalf("ALTER SYSTEM %s: %v", name, err)
		}
	}
	must("work_mem", "64MB", true, false)
	must("my.custom_x", "v1", true, false)
	must("application_name", `a'b\c`, true, false)
	must("work_mem", "32MB", true, false) // replaced: moves to the end
	want := header + "my.custom_x = 'v1'\napplication_name = 'a''b\\\\c'\nwork_mem = '32MB'\n"
	if got := read(); got != want {
		t.Fatalf("auto.conf:\n%s\nwant:\n%s", got, want)
	}
	// The file reads back to the original values (DeescapeQuotedString).
	entries, err := AutoConfEntries(dir)
	if err != nil {
		t.Fatal(err)
	}
	vals := map[string]string{}
	for _, e := range entries {
		vals[e.Name] = e.Value
	}
	if vals["application_name"] != `a'b\c` || vals["work_mem"] != "32MB" {
		t.Errorf("round trip: %v", vals)
	}

	must("work_mem", "", false, false) // RESET work_mem
	if got := read(); strings.Contains(got, "work_mem") {
		t.Errorf("RESET left the entry:\n%s", got)
	}
	must("", "", false, true) // RESET ALL
	if got := read(); got != header {
		t.Errorf("RESET ALL: %q", got)
	}
}

// TestAlterSystemRejects pins the validation half of AlterSystemSetConfigFile,
// with PostgreSQL's SQLSTATEs: a parameter that cannot be set in a config file,
// an unknown non-custom name, an invalid value and an embedded newline. None
// of them may touch the file.
func TestAlterSystemRejects(t *testing.T) {
	r := BuildDefaultRegistry()
	dir := t.TempDir()
	for _, c := range []struct {
		name, value string
		code        string
	}{
		{"server_version", "1", "55P02"},
		{"no_such_param", "1", "42704"},
		{"work_mem", "not_a_size", "22023"},
		{"application_name", "a\nb", "22023"},
	} {
		err := r.AlterSystemSetConfigFile(dir, c.name, c.value, true, false)
		aerr, ok := err.(*AlterSystemError)
		if !ok || aerr.Code != c.code {
			t.Errorf("ALTER SYSTEM SET %s = %q: err=%v, want SQLSTATE %s", c.name, c.value, err, c.code)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, AutoConfFileName)); !os.IsNotExist(err) {
		t.Errorf("a rejected ALTER SYSTEM created the file (stat err %v)", err)
	}
}

// TestReadSingleQuotedDeescapes pins the config-file string reader against
// guc-file.l's DeescapeQuotedString: doubled quotes, backslash escapes for
// \b \f \n \r \t, octal, and any other escaped character standing for itself.
func TestReadSingleQuotedDeescapes(t *testing.T) {
	for in, want := range map[string]string{
		`'a''b'`:      `a'b`,
		`'a\\b'`:      `a\b`,
		`'a\'b'`:      `a'b`,
		`'tab\there'`: "tab\there",
		`'\101'`:      "A",
		`'x\qy'`:      "xqy",
	} {
		got, _, err := readSingleQuoted(in, 0)
		if err != nil || got != want {
			t.Errorf("readSingleQuoted(%s) = %q, %v; want %q", in, got, err, want)
		}
	}
}

// TestReloadResetsRemovedFileEntries pins ProcessConfigFile's "parameter %s
// removed from configuration file, reset to default": a value that came from
// the config files and is gone from them on reload reverts to its boot value
// — how ALTER SYSTEM RESET takes effect on pg_reload_conf(). Custom (dotted)
// names are placeholders, never errors or warnings.
func TestReloadResetsRemovedFileEntries(t *testing.T) {
	r := BuildDefaultRegistry()
	if err := r.ApplyConfigEntries([]ConfigEntry{{Name: "work_mem", Value: "64MB"}, {Name: "my.custom_x", Value: "1"}}); err != nil {
		t.Fatalf("boot apply: %v", err)
	}
	v, _ := r.Get("work_mem")
	boot := v.BootVal
	if v.Value == boot {
		t.Fatalf("fixture: work_mem still at its boot value %q", boot)
	}
	res := r.ApplyReloadEntries([]ConfigEntry{{Name: "my.custom_x", Value: "2"}})
	if v.Value != boot || v.Source != SourceDefault {
		t.Errorf("work_mem after its entry was removed: value=%q source=%v, want boot %q", v.Value, v.Source, boot)
	}
	for _, w := range res.Warnings {
		if strings.Contains(w, "my.custom_x") {
			t.Errorf("custom placeholder warned: %s", w)
		}
	}
}
