package misc

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// AutoConfFileName is PG_AUTOCONF_FILENAME: the file ALTER SYSTEM rewrites,
// read after postgresql.conf so its entries win (guc-file.l
// ProcessConfigFileInternal). It always lives in the data directory.
const AutoConfFileName = "postgresql.auto.conf"

// AlterSystemError is an ALTER SYSTEM failure carrying PostgreSQL's SQLSTATE,
// so the executor can surface it unchanged.
type AlterSystemError struct {
	Code string
	Msg  string
	Hint string
}

func (e *AlterSystemError) Error() string { return e.Msg }

// autoFileLock is AutoFileLock: only one backend rewrites the auto file at a
// time, and it holds the lock while reading the old contents.
var autoFileLock sync.Mutex

// AlterSystemSetConfigFile is guc.c's AlterSystemSetConfigFile for one
// statement. value is the flattened SET value when set is true; set false
// means `SET name TO DEFAULT` or `RESET name` (remove the entry); resetAll
// empties the file. Permission checks are the caller's — they depend on the
// session role. The change takes effect on the next configuration reload or
// restart, as in PostgreSQL.
func (r *Registry) AlterSystemSetConfigFile(dataDir, name, value string, set, resetAll bool) error {
	if dataDir == "" {
		// PG_AUTOCONF_FILENAME is always relative to the data directory; a
		// server without one (embedded/test contexts) has no file to rewrite.
		return &AlterSystemError{Code: "0A000", Msg: "ALTER SYSTEM is not supported in this context"}
	}
	if !resetAll {
		if v, ok := r.Get(name); ok {
			// "Don't allow parameters that can't be set in configuration
			// files to be set in PG_AUTOCONF_FILENAME file."
			if v.Context == ContextInternal || v.Flags&FlagDisallowInFile != 0 {
				return &AlterSystemError{Code: "55P02", Msg: fmt.Sprintf("parameter %q cannot be changed", name)}
			}
			if set {
				canon, err := v.canonicalize(value)
				if err == nil && v.CheckFn != nil {
					err = v.CheckFn(canon)
				}
				if err != nil {
					// parse_and_validate_value at ERROR level reports its own
					// message (range, unit, enum list ...).
					if verr, ok := err.(*ValidationError); ok {
						return &AlterSystemError{Code: "22023", Msg: verr.Msg, Hint: verr.Hint}
					}
					return &AlterSystemError{Code: "22023", Msg: err.Error()}
				}
			}
		} else if set || !isCustomGUCName(name) {
			// assignable_custom_variable_name: an unknown name must at least
			// have a custom-variable shape. (goopg tracks no reserved
			// extension prefixes.)
			if !isCustomGUCName(name) {
				return &AlterSystemError{Code: "42704", Msg: fmt.Sprintf("unrecognized configuration parameter %q", name)}
			}
		}
		// The config-file grammar has no escape for an embedded newline.
		if set && strings.ContainsRune(value, '\n') {
			return &AlterSystemError{Code: "22023", Msg: "parameter value for ALTER SYSTEM must not contain a newline"}
		}
	}

	autoFileLock.Lock()
	defer autoFileLock.Unlock()

	path := filepath.Join(dataDir, AutoConfFileName)
	var entries []ConfigEntry
	if !resetAll {
		if _, err := os.Stat(path); err == nil {
			parsed, perr := ParseConfigFile(path)
			if perr != nil {
				return &AlterSystemError{Code: "F0000", Msg: fmt.Sprintf("could not parse contents of file %q", AutoConfFileName)}
			}
			entries = parsed
		}
		entries = replaceAutoConfigValue(entries, name, value, set)
	}
	return writeAutoConfFile(path, entries)
}

// replaceAutoConfigValue is replace_auto_config_value: drop every entry for
// name (case-insensitively — guc_name_compare), then append the new value
// unless the entry is being removed.
func replaceAutoConfigValue(entries []ConfigEntry, name, value string, set bool) []ConfigEntry {
	out := entries[:0]
	for _, e := range entries {
		if !strings.EqualFold(e.Name, name) {
			out = append(out, e)
		}
	}
	if set {
		out = append(out, ConfigEntry{Name: name, Value: value})
	}
	return out
}

// writeAutoConfFile is write_auto_conf_file plus the caller's crash-safe
// replace: write a temp file, fsync it, rename it over the old one, and fsync
// the directory (durable_rename).
func writeAutoConfFile(path string, entries []ConfigEntry) error {
	var b strings.Builder
	b.WriteString("# Do not edit this file manually!\n")
	b.WriteString("# It will be overwritten by the ALTER SYSTEM command.\n")
	for _, e := range entries {
		b.WriteString(e.Name)
		b.WriteString(" = '")
		b.WriteString(escapeSingleQuotesASCII(e.Value))
		b.WriteString("'\n")
	}
	tmp := path + ".tmp"
	f, err := os.OpenFile(tmp, os.O_CREATE|os.O_RDWR|os.O_TRUNC, 0o600)
	if err != nil {
		return &AlterSystemError{Code: "58030", Msg: fmt.Sprintf("could not open file %q: %v", AutoConfFileName+".tmp", err)}
	}
	if _, err := f.WriteString(b.String()); err != nil {
		f.Close()
		os.Remove(tmp)
		return &AlterSystemError{Code: "58030", Msg: fmt.Sprintf("could not write to file %q: %v", AutoConfFileName+".tmp", err)}
	}
	if err := f.Sync(); err != nil {
		f.Close()
		os.Remove(tmp)
		return &AlterSystemError{Code: "58030", Msg: fmt.Sprintf("could not fsync file %q: %v", AutoConfFileName+".tmp", err)}
	}
	if err := f.Close(); err != nil {
		os.Remove(tmp)
		return &AlterSystemError{Code: "58030", Msg: fmt.Sprintf("could not close file %q: %v", AutoConfFileName+".tmp", err)}
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return &AlterSystemError{Code: "58030", Msg: fmt.Sprintf("could not rename file %q to %q: %v", AutoConfFileName+".tmp", AutoConfFileName, err)}
	}
	if d, err := os.Open(filepath.Dir(path)); err == nil {
		_ = d.Sync()
		_ = d.Close()
	}
	return nil
}

// escapeSingleQuotesASCII is escape_single_quotes_ascii (src/port/quotes.c):
// double every single quote and backslash, so the config-file lexer reads the
// value back unchanged.
func escapeSingleQuotesASCII(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		if s[i] == '\'' || s[i] == '\\' {
			b.WriteByte(s[i])
		}
		b.WriteByte(s[i])
	}
	return b.String()
}

// AutoConfEntries parses the data directory's postgresql.auto.conf for the
// boot-time and reload passes, which apply it after postgresql.conf. A
// missing file is not an error (ParseConfigFile(PG_AUTOCONF_FILENAME, false,
// ...) is non-strict upstream).
func AutoConfEntries(dataDir string) ([]ConfigEntry, error) {
	if dataDir == "" {
		return nil, nil
	}
	path := filepath.Join(dataDir, AutoConfFileName)
	if _, err := os.Stat(path); err != nil {
		return nil, nil
	}
	return ParseConfigFile(path)
}

// AlterSystem runs ALTER SYSTEM against the session's global registry —
// the variable definitions it validates against are process-wide, and the
// file it rewrites is the cluster's. dataDir is the cluster data directory.
func (s *SessionRegistry) AlterSystem(dataDir, name, value string, set, resetAll bool) error {
	if s == nil || s.global == nil {
		return &AlterSystemError{Code: "0A000", Msg: "ALTER SYSTEM is not supported in this context"}
	}
	return s.global.AlterSystemSetConfigFile(dataDir, name, value, set, resetAll)
}
