package sqlparser

import "testing"

// Pins for the ALTER TABLE action wave: the corpus's largest unrouted class
// (712 fragments across 44 actions) drops to 6, and corpus parity 550 -> 646.

// TestAlterAddConstraint pins `ADD [CONSTRAINT name] <table constraint>`.
// One at_constraint nonterminal serves the named and unnamed spellings, and
// every alternative ends in at_constr_tail — the FLAT trailing-word list, so
// DEFERRABLE / NOT VALID / [NOT] ENFORCED / [NO] INHERIT compose in any order.
// A two-part tail cannot do this: NOT is followed by DEFERRABLE, VALID or
// ENFORCED and one token of lookahead cannot tell them apart.
func TestAlterAddConstraint(t *testing.T) {
	for _, q := range []string{
		"ALTER TABLE onek ADD CONSTRAINT c UNIQUE (unique1)",
		"ALTER TABLE t ADD CONSTRAINT c PRIMARY KEY (a)",
		"ALTER TABLE t ADD CONSTRAINT c CHECK (a > 0) NOT VALID",
		"ALTER TABLE t ADD CONSTRAINT c CHECK (a > 0) NO INHERIT",
		"ALTER TABLE t ADD CONSTRAINT c CHECK (a = 2) NOT VALID NO INHERIT",
		"ALTER TABLE t ADD CONSTRAINT c CHECK (a > 0) NOT ENFORCED",
		"ALTER TABLE t ADD CONSTRAINT c FOREIGN KEY (a) REFERENCES p (b) ON DELETE CASCADE",
		"ALTER TABLE t ADD CONSTRAINT c FOREIGN KEY (a) REFERENCES p MATCH FULL ON DELETE CASCADE NOT VALID",
		"ALTER TABLE t ADD CONSTRAINT c FOREIGN KEY (a) REFERENCES p DEFERRABLE",
		"ALTER TABLE t ADD CONSTRAINT c EXCLUDE USING btree (f3 WITH =)",
		"ALTER TABLE t ADD CONSTRAINT c PRIMARY KEY USING INDEX i",
		"ALTER TABLE t ADD CONSTRAINT c UNIQUE USING INDEX i",
		"ALTER TABLE t ADD CONSTRAINT c UNIQUE (a) DEFERRABLE INITIALLY DEFERRED",
		"ALTER TABLE t ADD CONSTRAINT c NOT NULL col NOT VALID NO INHERIT",
		"ALTER TABLE t ADD FOREIGN KEY (a) REFERENCES p",
		"ALTER TABLE t ADD UNIQUE (a, b)",
		"ALTER TABLE t ADD CHECK (a > 0) NOT VALID",
		"ALTER TABLE t ADD EXCLUDE USING btree (f3 WITH =) WHERE (f3 > 0)",
		"ALTER TABLE t ADD NOT NULL a NO INHERIT",
		"ALTER TABLE t ADD PRIMARY KEY (a)",
		"ALTER TABLE t ADD PRIMARY KEY USING INDEX i",
		// The column form is spelled four ways so no EMPTY nonterminal reduces
		// right after ADD — with one, `ADD EXCLUDE` had to choose between the
		// constraint keyword and a column named "exclude" a token too early.
		"ALTER TABLE t ADD COLUMN IF NOT EXISTS c2 integer",
		"ALTER TABLE t ADD COLUMN c2 integer",
		"ALTER TABLE t ADD c2 integer",
		"ALTER TABLE t ADD CONSTRAINT c UNIQUE (a), ADD CONSTRAINT d CHECK (b > 0)",
		"ALTER TABLE cwi_test DROP CONSTRAINT cwi_uniq_idx, ADD CONSTRAINT cwi_replaced_pkey PRIMARY KEY USING INDEX cwi_uniq2_idx",
	} {
		assertParity(t, q)
	}
}

// TestAlterColumnActions pins the ALTER [COLUMN] sub-actions. Several are
// NoOp in legacy and reproduced as such — including SET DATA TYPE, which
// differs from plain TYPE (that one does record AlterColumnType).
func TestAlterColumnActions(t *testing.T) {
	for _, q := range []string{
		"ALTER TABLE t ALTER COLUMN a TYPE int USING 0",
		"ALTER TABLE t ALTER COLUMN a TYPE int",
		"ALTER TABLE t ALTER COLUMN c SET DATA TYPE int USING 0",
		"ALTER TABLE t ALTER COLUMN a SET STATISTICS 100",
		"ALTER TABLE t ALTER COLUMN a SET STORAGE plain",
		"ALTER TABLE t ALTER COLUMN a SET COMPRESSION pglz",
		"ALTER TABLE t ALTER COLUMN c SET COMPRESSION default",
		"ALTER TABLE t ALTER COLUMN a SET (n_distinct = 1)",
		"ALTER TABLE t ALTER COLUMN c SET (n_distinct = -0.5)",
		"ALTER TABLE t ALTER COLUMN c SET (n_distinct = 0.5, n_distinct_inherited = -0.1)",
		"ALTER TABLE t ALTER COLUMN a RESET (n_distinct)",
		"ALTER TABLE t ALTER a SET STORAGE plain",
		"ALTER TABLE t ALTER COLUMN a DROP EXPRESSION",
		"ALTER TABLE t ALTER COLUMN b SET EXPRESSION AS (a * 2)",
		"ALTER TABLE t ALTER COLUMN a SET GENERATED ALWAYS",
		"ALTER TABLE t ALTER COLUMN a SET GENERATED BY DEFAULT SET INCREMENT BY 2",
		"ALTER TABLE t ALTER COLUMN b SET INCREMENT BY 2",
		"ALTER TABLE t ALTER COLUMN a RESTART WITH 5",
		"ALTER TABLE t ALTER COLUMN a DROP IDENTITY",
		"ALTER TABLE t ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY",
		"ALTER TABLE t ALTER COLUMN a SET DEFAULT 1",
		"ALTER TABLE t ALTER COLUMN a DROP NOT NULL",
	} {
		assertParity(t, q)
	}
}

// TestAlterConstraintAndTableActions pins ALTER CONSTRAINT — whose three
// categories each carry their own "was written" marker — and the table-level
// actions.
func TestAlterConstraintAndTableActions(t *testing.T) {
	for _, q := range []string{
		"ALTER TABLE t ALTER CONSTRAINT c NOT DEFERRABLE",
		"ALTER TABLE t ALTER CONSTRAINT c DEFERRABLE INITIALLY DEFERRED",
		"ALTER TABLE t ALTER CONSTRAINT c INHERIT",
		"ALTER TABLE t ALTER CONSTRAINT c NO INHERIT",
		"ALTER TABLE t ALTER CONSTRAINT fk ENFORCED",
		"ALTER TABLE t ALTER CONSTRAINT fk NOT ENFORCED",
		"ALTER TABLE t ALTER CONSTRAINT fk NOT DEFERRABLE ENFORCED",
		"ALTER TABLE t ALTER CONSTRAINT nn NOT DEFERRABLE NO INHERIT",
		"ALTER TABLE t RESET (fillfactor)",
		"ALTER TABLE t SET (fillfactor = 10)",
		"ALTER TABLE t SET ACCESS METHOD heap2",
		"ALTER TABLE t SET TABLESPACE ts",
		"ALTER TABLE t SET WITHOUT OIDS",
		"ALTER TABLE t SET WITHOUT CLUSTER",
		"ALTER TABLE t CLUSTER ON i",
		"ALTER TABLE t RENAME CONSTRAINT a TO b",
		"ALTER TABLE t DROP a",
		"ALTER TABLE t DROP COLUMN a",
		"ALTER TABLE t DROP COLUMN IF EXISTS a CASCADE",
		"ALTER TABLE t INHERIT p",
		"ALTER TABLE t NO INHERIT p",
		"ALTER TABLE t OF ty",
		"ALTER TABLE t NOT OF",
		"ALTER TABLE t DISABLE ROW LEVEL SECURITY",
		"ALTER TABLE t ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE t FORCE ROW LEVEL SECURITY",
		"ALTER TABLE t NO FORCE ROW LEVEL SECURITY",
		"ALTER TABLE t ENABLE ALWAYS RULE r",
		"ALTER TABLE t ENABLE REPLICA RULE r",
		"ALTER TABLE t ENABLE RULE r",
		"ALTER TABLE t DISABLE RULE r",
		"ALTER TABLE t DETACH PARTITION p CONCURRENTLY",
		"ALTER TABLE t DETACH PARTITION p FINALIZE",
		"ALTER TABLE t DETACH PARTITION p",
		// ENABLE / DISABLE TRIGGER is a STATEMENT-level flag in legacy, with
		// no action and no trigger name recorded.
		"ALTER TABLE t DISABLE TRIGGER tg",
		"ALTER TABLE t ENABLE ALWAYS TRIGGER tg",
		"ALTER TABLE t ENABLE TRIGGER ALL",
		"ALTER TABLE t DISABLE TRIGGER USER",
		// The inheritance star on the target name, as in a FROM clause.
		"ALTER TABLE e_star* RENAME COLUMN e TO ee",
		"ALTER TABLE ONLY t ADD CONSTRAINT c UNIQUE (a)",
		"ALTER TABLE IF EXISTS t DROP a",
	} {
		assertParity(t, q)
	}
}
