package sqlparser

import "testing"

// Pins for the batch ranked from the full regress corpus:
// legacy-accepts / yacc-rejects 299 -> 137, corpus parity 491 -> 521.

// TestCheckBodyIsOpaque — legacy's parseCheckExpr never parses a CHECK body:
// it records a PLAIN space join of the tokens between the parens (string
// literals re-quoted), so `CHECK ((y).a > 0)` is legal there even though the
// expression grammar rejects `(y).a`. The adapter folds `CHECK ( ... )` into
// one CHECKBODY terminal carrying both paren positions, and the rule joins.
func TestCheckBodyIsOpaque(t *testing.T) {
	for _, q := range []string{
		"CREATE TABLE tx (x int, y ty CHECK ((y).a > 0))",
		"CREATE TABLE tx (x int, CHECK ((y).a > 0))",
		"CREATE TABLE t (a text CHECK (a <> 'x'))",
		"CREATE TABLE t (a text CHECK (Upper(a) = 'X' AND (a) > 0))",
		"CREATE TABLE t (a int, CHECK (a IN (1, 2)))",
		"CREATE TABLE nv (check (d between '2009-01-01'::date and '2009-12-31'::date))",
		"CREATE TABLE t (a int CONSTRAINT c CHECK (a > 0) NO INHERIT)",
		"CREATE TABLE q1 PARTITION OF q ( CONSTRAINT check_1 CHECK (A IS NOT NULL AND Upper(a) = 'X') ) DEFAULT",
		// [NOT] ENFORCED is its own column-constraint item (see the grammar
		// note); at table level it is part of the flat trailer.
		"ALTER TABLE t ADD COLUMN x int CHECK (x > 0) NOT ENFORCED",
		"CREATE TABLE t (x int CHECK (x > 0) NOT ENFORCED)",
		"CREATE TABLE t (x int, CHECK (x > 0) NOT ENFORCED)",
		"CREATE TABLE t (x int, CONSTRAINT c CHECK (x > 0) ENFORCED)",
		"CREATE TABLE nv_parent (d date, check (false) no inherit not valid)",
		// ALTER TABLE ADD COLUMN had been dropping CHECK and REFERENCES.
		"ALTER TABLE t ADD COLUMN x int CHECK (x > 0) REFERENCES u (y) ON DELETE SET NULL (x)",
	} {
		assertParity(t, q)
	}
}

// TestGroupingSetsExpansion — GROUPING SETS / ROLLUP / CUBE expanded at PARSE
// time as parseGroupByElems does: GroupBy is the flat list with duplicates,
// GroupingSets the cartesian product of each element's alternatives, ROLLUP
// longest-prefix first, CUBE by ascending bit mask. ROLLUP and CUBE had
// parsed before but produced no GroupingSets at all.
func TestGroupingSetsExpansion(t *testing.T) {
	for _, q := range []string{
		"SELECT a, b FROM t GROUP BY GROUPING SETS ((), (a), (a, b))",
		"SELECT a FROM t GROUP BY GROUPING SETS (a, b)",
		"SELECT null FROM pg_database GROUP BY GROUPING SETS (()) FOR UPDATE",
		"SELECT a FROM t GROUP BY ROLLUP (a, b)",
		"SELECT a FROM t GROUP BY CUBE (a, b)",
		"SELECT a FROM t GROUP BY a, ROLLUP (b, c)",
		"SELECT a FROM t GROUP BY ROLLUP ((a, b), c)",
		"SELECT a FROM t GROUP BY GROUPING SETS (ROLLUP (a), CUBE (b))",
		"SELECT a FROM t GROUP BY a, b",
	} {
		assertParity(t, q)
	}
}

// TestForeignKeyOptions — MATCH FULL/SIMPLE (kept as a flag on the column
// form and on the table form), and `ON DELETE SET NULL|DEFAULT (cols)`, whose
// list legacy keeps for ON DELETE only. SET NULL / SET DEFAULT live outside
// fk_kw so the optional list does not shift/reduce against the bare keyword.
func TestForeignKeyOptions(t *testing.T) {
	for _, q := range []string{
		"CREATE TABLE fk (tid int, id int, foo int, FOREIGN KEY (tid, id) REFERENCES pk ON DELETE SET NULL (bar))",
		"CREATE TABLE fk (tid int, FOREIGN KEY (tid) REFERENCES pk ON DELETE SET DEFAULT (tid) ON UPDATE CASCADE)",
		"CREATE TABLE fk (f1 int CONSTRAINT fk1 REFERENCES pk MATCH FULL)",
		"CREATE TABLE fk (f1 int, FOREIGN KEY (f1) REFERENCES pk MATCH SIMPLE ON DELETE CASCADE)",
		"CREATE TABLE fk (f1 int, FOREIGN KEY (f1) REFERENCES pk MATCH FULL ON DELETE SET DEFAULT (f1))",
		"CREATE TABLE fk (f1 int REFERENCES pk ON DELETE SET NULL (f1))",
		"CREATE TABLE fk (f1 int, FOREIGN KEY (f1) REFERENCES pk ON UPDATE SET NULL (f1))",
	} {
		assertParity(t, q)
	}
}

// TestSmallFormsBatchF — the rest of the batch, one line each.
func TestSmallFormsBatchF(t *testing.T) {
	for _, q := range []string{
		// generated columns: legacy's join text, optional storage word (VIRTUAL default)
		"CREATE TABLE g (a int, b int GENERATED ALWAYS AS (a * 2))",
		"CREATE TABLE g (a int, b int GENERATED ALWAYS AS (a*2) STORED)",
		"CREATE TABLE g (a int, b int GENERATED ALWAYS AS (Upper(a) || 'x') VIRTUAL)",
		"CREATE TABLE g (a int PRIMARY KEY, b int GENERATED BY DEFAULT AS (a * 2) STORED)",
		// partition element lists: dropped options, DuplicateColumn
		"CREATE TABLE c PARTITION OF p (f3 WITH OPTIONS GENERATED ALWAYS AS IDENTITY) FOR VALUES IN (1)",
		"CREATE TABLE c PARTITION OF p (f3 GENERATED ALWAYS AS (a * 2) VIRTUAL) FOR VALUES IN (1)",
		"CREATE TABLE c PARTITION OF p (b NOT NULL, b DEFAULT 1, b CHECK (b > 0)) FOR VALUES IN (1)",
		"CREATE TABLE c PARTITION OF p (a PRIMARY KEY) FOR VALUES FROM (0) TO (1)",
		`CREATE TABLE c PARTITION OF p (b COLLATE "C") FOR VALUES IN (1)`,
		// view CHECK OPTION, with RawDef stopping at WITH
		"CREATE VIEW v AS SELECT * FROM t WITH CASCADED CHECK OPTION",
		"CREATE VIEW v AS SELECT * FROM t WITH LOCAL CHECK OPTION",
		"CREATE VIEW v AS SELECT * FROM t WITH CHECK OPTION",
		// column qualifiers
		"CREATE TABLE nulltest (col1 dnotnull, col2 dnotnull NULL)",
		"CREATE TABLE ts (a text, c text storage plain)",
		"ALTER TABLE t ADD COLUMN c text STORAGE external",
		"CREATE TABLE u (u unknown)",
		// calls and expressions
		"SELECT ten, sum(distinct four) filter (where four::text ~ '123') FROM onek",
		"SELECT sum(salary), row_number() OVER (ORDER BY depname), sum( sum(salary) FILTER (WHERE enroll_date > '2007-01-01') ) FILTER (WHERE depname <> 'sales') OVER (ORDER BY depname DESC) FROM empsalary GROUP BY depname",
		"SELECT count(a) FILTER (WHERE b) OVER w FROM t WINDOW w AS (ORDER BY a)",
		"SELECT * FROM tt5 NATURAL INNER JOIN tt6",
		"SELECT txid_snapshot '1:9223372036854775807:3'",
		"SELECT pg_snapshot '1:2:3'",
		"SELECT interval(0) '1 day 01:23:45.6789'",
		`SELECT SUBSTRING('abcdefg' SIMILAR 'a#"%#"g' ESCAPE '#')`,
		`SELECT SUBSTRING('abcdefg' SIMILAR 'a*#"%#"g*' ESCAPE '#')`,
		"SELECT SUBSTRING('abcdefg' SIMILAR '%' ESCAPE NULL)",
		"SELECT POSITION('\\x11'::bytea IN ''::bytea) = 0",
		"SELECT x FROM anyctest(variadic array[11, 12]) x",
		"SELECT 'foo' NOT LIKE ALL (array['%a'])",
		"SELECT 'foo' ILIKE ALL (array['%a'])",
		"SELECT a FROM t WHERE a BETWEEN 2^16 AND 2^17",
		// table trailers / actions
		"CREATE TABLE temptest(col int) ON COMMIT DELETE ROWS",
		"CREATE TEMP TABLE temptest(col int) ON COMMIT DROP",
		"ALTER TABLE t DROP COLUMN b CASCADE",
	} {
		assertParity(t, q)
	}
}

// TestMultiColumnSet pins `UPDATE ... SET (c1, c2) = (...)`, the last real
// cluster in the full regress corpus (34 fragments). The RHS is whatever the
// expression grammar makes of it — RowExpr, SubqueryExpr, ROW(...) call —
// except that a parenthesised single value is a one-element RowExpr, as legacy
// records it (decided from the token stream, since `(1)` collapses to `1`).
func TestMultiColumnSet(t *testing.T) {
	for _, q := range []string{
		"UPDATE t SET (a, b) = (1, 2)",
		"UPDATE t SET (a, b) = (SELECT 1, 2)",
		"UPDATE inhpar i SET (f1, f2) = (SELECT i.f1, i.f2 || '-' FROM int4_tbl LIMIT 1)",
		"UPDATE t SET (a) = (1)",
		"UPDATE t SET (a, b) = ROW(1, 2)",
		"UPDATE t SET a = 1, (b, c) = (2, 3)",
		"INSERT INTO t VALUES (1) ON CONFLICT (k) DO UPDATE SET (a, b) = (2, 3)",
		"UPDATE t SET a = 1",
		"UPDATE t SET a = DEFAULT",
	} {
		assertParity(t, q)
	}
}
