package sqlparser

import "testing"

// TestGeneratedColumnParity — `GENERATED ALWAYS AS (expr) STORED|VIRTUAL` and
// `GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY`.
//
// The generated EXPRESSION is a raw source span in legacy, like CHECK.
//
// The two storage keywords are one alternative with one mid-rule action, not
// two alternatives each carrying `{ markSpanStart() }`: identical prefixes with
// SEPARATE mid-rule actions give goyacc two distinct empty nonterminals
// reducible at the same point, which measured 420 reduce/reduce. gen_storage
// also pins the span end, because by the time the outer action runs the ')' is
// no longer the last consumed token.
//
// IDENTITY option lists (`(START WITH n INCREMENT BY n ...)`) are not ported;
// see TODO.md.
func TestGeneratedColumnParity(t *testing.T) {
	for _, q := range []string{
		"CREATE TABLE t (a int, b int GENERATED ALWAYS AS (a + 1) STORED)",
		"CREATE TABLE t (a int, b int GENERATED ALWAYS AS (a + 1) VIRTUAL)",
		"CREATE TABLE t (a int, b text GENERATED ALWAYS AS (a || 'x') STORED)",
		"CREATE TABLE t (a int GENERATED ALWAYS AS IDENTITY)",
		"CREATE TABLE t (a int GENERATED BY DEFAULT AS IDENTITY)",
		"CREATE TABLE t (a int GENERATED ALWAYS AS IDENTITY NOT NULL)",
		// guards
		"CREATE TABLE t (a int, b int)",
		"CREATE TABLE t (a int DEFAULT 0)",
		"CREATE TABLE t (a int CHECK (a > 0))",
	} {
		assertParity(t, q)
	}
}
