// Code generated by goyacc -o yacc_parser.go -v y.output ../../tmp/goopg_grammar.y. DO NOT EDIT.

//line ../../tmp/goopg_grammar.y:6

package sqlparser

import __yyfmt__ "fmt"

//line ../../tmp/goopg_grammar.y:7

import (
	"github.com/goopg/goopg/internal/parser"
)

//line ../../tmp/goopg_grammar.y:15
type yySymType struct {
	yys   int
	str   string        // IDENT / SCONST / keyword text / Op value ...
	ival  int           // ICONST / PARAM numbers
	pos   int           // byte offset of the production's first token
	stmt  parser.Stmt   // single-statement productions (P1+)
	stmts []parser.Stmt // statement lists (root)
	expr  parser.Expr   // expression productions (P2+)
	list  []any         // heterogeneous lists, mirroring PG's untyped List
}

const ABORT_P = 57346
const ABSENT = 57347
const ABSOLUTE_P = 57348
const ACCESS = 57349
const ACTION = 57350
const ADD_P = 57351
const ADMIN = 57352
const AFTER = 57353
const AGGREGATE = 57354
const ALL = 57355
const ALSO = 57356
const ALTER = 57357
const ALWAYS = 57358
const ANALYSE = 57359
const ANALYZE = 57360
const AND = 57361
const ANY = 57362
const ARRAY = 57363
const AS = 57364
const ASC = 57365
const ASENSITIVE = 57366
const ASSERTION = 57367
const ASSIGNMENT = 57368
const ASYMMETRIC = 57369
const AT = 57370
const ATOMIC = 57371
const ATTACH = 57372
const ATTRIBUTE = 57373
const AUTHORIZATION = 57374
const BACKWARD = 57375
const BEFORE = 57376
const BEGIN_P = 57377
const BETWEEN = 57378
const BIGINT = 57379
const BINARY = 57380
const BIT = 57381
const BOOLEAN_P = 57382
const BOTH = 57383
const BREADTH = 57384
const BY = 57385
const CACHE = 57386
const CALL = 57387
const CALLED = 57388
const CASCADE = 57389
const CASCADED = 57390
const CASE = 57391
const CAST = 57392
const CATALOG_P = 57393
const CHAIN = 57394
const CHAR_P = 57395
const CHARACTER = 57396
const CHARACTERISTICS = 57397
const CHECK = 57398
const CHECKPOINT = 57399
const CLASS = 57400
const CLOSE = 57401
const CLUSTER = 57402
const COALESCE = 57403
const COLLATE = 57404
const COLLATION = 57405
const COLUMN = 57406
const COLUMNS = 57407
const COMMENT = 57408
const COMMENTS = 57409
const COMMIT = 57410
const COMMITTED = 57411
const COMPRESSION = 57412
const CONCURRENTLY = 57413
const CONDITIONAL = 57414
const CONFIGURATION = 57415
const CONFLICT = 57416
const CONNECTION = 57417
const CONSTRAINT = 57418
const CONSTRAINTS = 57419
const CONTENT_P = 57420
const CONTINUE_P = 57421
const CONVERSION_P = 57422
const COPY = 57423
const COST = 57424
const CREATE = 57425
const CROSS = 57426
const CSV = 57427
const CUBE = 57428
const CURRENT_P = 57429
const CURRENT_CATALOG = 57430
const CURRENT_DATE = 57431
const CURRENT_ROLE = 57432
const CURRENT_SCHEMA = 57433
const CURRENT_TIME = 57434
const CURRENT_TIMESTAMP = 57435
const CURRENT_USER = 57436
const CURSOR = 57437
const CYCLE = 57438
const DATA_P = 57439
const DATABASE = 57440
const DAY_P = 57441
const DEALLOCATE = 57442
const DEC = 57443
const DECIMAL_P = 57444
const DECLARE = 57445
const DEFAULT = 57446
const DEFAULTS = 57447
const DEFERRABLE = 57448
const DEFERRED = 57449
const DEFINER = 57450
const DELETE_P = 57451
const DELIMITER = 57452
const DELIMITERS = 57453
const DEPENDS = 57454
const DEPTH = 57455
const DESC = 57456
const DETACH = 57457
const DICTIONARY = 57458
const DISABLE_P = 57459
const DISCARD = 57460
const DISTINCT = 57461
const DO = 57462
const DOCUMENT_P = 57463
const DOMAIN_P = 57464
const DOUBLE_P = 57465
const DROP = 57466
const EACH = 57467
const ELSE = 57468
const EMPTY_P = 57469
const ENABLE_P = 57470
const ENCODING = 57471
const ENCRYPTED = 57472
const END_P = 57473
const ENFORCED = 57474
const ENUM_P = 57475
const ERROR_P = 57476
const ESCAPE = 57477
const EVENT = 57478
const EXCEPT = 57479
const EXCLUDE = 57480
const EXCLUDING = 57481
const EXCLUSIVE = 57482
const EXECUTE = 57483
const EXISTS = 57484
const EXPLAIN = 57485
const EXPRESSION = 57486
const EXTENSION = 57487
const EXTERNAL = 57488
const EXTRACT = 57489
const FALSE_P = 57490
const FAMILY = 57491
const FETCH = 57492
const FILTER = 57493
const FINALIZE = 57494
const FIRST_P = 57495
const FLOAT_P = 57496
const FOLLOWING = 57497
const FOR = 57498
const FORCE = 57499
const FOREIGN = 57500
const FORMAT = 57501
const FORWARD = 57502
const FREEZE = 57503
const FROM = 57504
const FULL = 57505
const FUNCTION = 57506
const FUNCTIONS = 57507
const GENERATED = 57508
const GLOBAL = 57509
const GRANT = 57510
const GRANTED = 57511
const GREATEST = 57512
const GROUP_P = 57513
const GROUPING = 57514
const GROUPS = 57515
const HANDLER = 57516
const HAVING = 57517
const HEADER_P = 57518
const HOLD = 57519
const HOUR_P = 57520
const IDENTITY_P = 57521
const IF_P = 57522
const ILIKE = 57523
const IMMEDIATE = 57524
const IMMUTABLE = 57525
const IMPLICIT_P = 57526
const IMPORT_P = 57527
const IN_P = 57528
const INCLUDE = 57529
const INCLUDING = 57530
const INCREMENT = 57531
const INDENT = 57532
const INDEX = 57533
const INDEXES = 57534
const INHERIT = 57535
const INHERITS = 57536
const INITIALLY = 57537
const INLINE_P = 57538
const INNER_P = 57539
const INOUT = 57540
const INPUT_P = 57541
const INSENSITIVE = 57542
const INSERT = 57543
const INSTEAD = 57544
const INT_P = 57545
const INTEGER = 57546
const INTERSECT = 57547
const INTERVAL = 57548
const INTO = 57549
const INVOKER = 57550
const IS = 57551
const ISNULL = 57552
const ISOLATION = 57553
const JOIN = 57554
const JSON = 57555
const JSON_ARRAY = 57556
const JSON_ARRAYAGG = 57557
const JSON_EXISTS = 57558
const JSON_OBJECT = 57559
const JSON_OBJECTAGG = 57560
const JSON_QUERY = 57561
const JSON_SCALAR = 57562
const JSON_SERIALIZE = 57563
const JSON_TABLE = 57564
const JSON_VALUE = 57565
const KEEP = 57566
const KEY = 57567
const KEYS = 57568
const LABEL = 57569
const LANGUAGE = 57570
const LARGE_P = 57571
const LAST_P = 57572
const LATERAL_P = 57573
const LEADING = 57574
const LEAKPROOF = 57575
const LEAST = 57576
const LEFT = 57577
const LEVEL = 57578
const LIKE = 57579
const LIMIT = 57580
const LISTEN = 57581
const LOAD = 57582
const LOCAL = 57583
const LOCALTIME = 57584
const LOCALTIMESTAMP = 57585
const LOCATION = 57586
const LOCK_P = 57587
const LOCKED = 57588
const LOGGED = 57589
const MAPPING = 57590
const MATCH = 57591
const MATCHED = 57592
const MATERIALIZED = 57593
const MAXVALUE = 57594
const MERGE = 57595
const MERGE_ACTION = 57596
const METHOD = 57597
const MINUTE_P = 57598
const MINVALUE = 57599
const MODE = 57600
const MONTH_P = 57601
const MOVE = 57602
const NAME_P = 57603
const NAMES = 57604
const NATIONAL = 57605
const NATURAL = 57606
const NCHAR = 57607
const NESTED = 57608
const NEW = 57609
const NEXT = 57610
const NFC = 57611
const NFD = 57612
const NFKC = 57613
const NFKD = 57614
const NO = 57615
const NONE = 57616
const NORMALIZE = 57617
const NORMALIZED = 57618
const NOT = 57619
const NOTHING = 57620
const NOTIFY = 57621
const NOTNULL = 57622
const NOWAIT = 57623
const NULL_P = 57624
const NULLIF = 57625
const NULLS_P = 57626
const NUMERIC = 57627
const OBJECT_P = 57628
const OBJECTS_P = 57629
const OF = 57630
const OFF = 57631
const OFFSET = 57632
const OIDS = 57633
const OLD = 57634
const OMIT = 57635
const ON = 57636
const ONLY = 57637
const OPERATOR = 57638
const OPTION = 57639
const OPTIONS = 57640
const OR = 57641
const ORDER = 57642
const ORDINALITY = 57643
const OTHERS = 57644
const OUT_P = 57645
const OUTER_P = 57646
const OVER = 57647
const OVERLAPS = 57648
const OVERLAY = 57649
const OVERRIDING = 57650
const OWNED = 57651
const OWNER = 57652
const PARALLEL = 57653
const PARAMETER = 57654
const PARSER = 57655
const PARTIAL = 57656
const PARTITION = 57657
const PASSING = 57658
const PASSWORD = 57659
const PATH = 57660
const PERIOD = 57661
const PLACING = 57662
const PLAN = 57663
const PLANS = 57664
const POLICY = 57665
const POSITION = 57666
const PRECEDING = 57667
const PRECISION = 57668
const PREPARE = 57669
const PREPARED = 57670
const PRESERVE = 57671
const PRIMARY = 57672
const PRIOR = 57673
const PRIVILEGES = 57674
const PROCEDURAL = 57675
const PROCEDURE = 57676
const PROCEDURES = 57677
const PROGRAM = 57678
const PUBLICATION = 57679
const QUOTE = 57680
const QUOTES = 57681
const RANGE = 57682
const READ = 57683
const REAL = 57684
const REASSIGN = 57685
const RECURSIVE = 57686
const REF_P = 57687
const REFERENCES = 57688
const REFERENCING = 57689
const REFRESH = 57690
const REINDEX = 57691
const RELATIVE_P = 57692
const RELEASE = 57693
const RENAME = 57694
const REPEATABLE = 57695
const REPLACE = 57696
const REPLICA = 57697
const RESET = 57698
const RESTART = 57699
const RESTRICT = 57700
const RETURN = 57701
const RETURNING = 57702
const RETURNS = 57703
const REVOKE = 57704
const RIGHT = 57705
const ROLE = 57706
const ROLLBACK = 57707
const ROLLUP = 57708
const ROUTINE = 57709
const ROUTINES = 57710
const ROW = 57711
const ROWS = 57712
const RULE = 57713
const SAVEPOINT = 57714
const SCALAR = 57715
const SCHEMA = 57716
const SCHEMAS = 57717
const SCROLL = 57718
const SEARCH = 57719
const SECOND_P = 57720
const SECURITY = 57721
const SELECT = 57722
const SEQUENCE = 57723
const SEQUENCES = 57724
const SERIALIZABLE = 57725
const SERVER = 57726
const SESSION = 57727
const SESSION_USER = 57728
const SET = 57729
const SETOF = 57730
const SETS = 57731
const SHARE = 57732
const SHOW = 57733
const SIMILAR = 57734
const SIMPLE = 57735
const SKIP = 57736
const SMALLINT = 57737
const SNAPSHOT = 57738
const SOME = 57739
const SOURCE = 57740
const SQL_P = 57741
const STABLE = 57742
const STANDALONE_P = 57743
const START = 57744
const STATEMENT = 57745
const STATISTICS = 57746
const STDIN = 57747
const STDOUT = 57748
const STORAGE = 57749
const STORED = 57750
const STRICT_P = 57751
const STRING_P = 57752
const STRIP_P = 57753
const SUBSCRIPTION = 57754
const SUBSTRING = 57755
const SUPPORT = 57756
const SYMMETRIC = 57757
const SYSID = 57758
const SYSTEM_P = 57759
const SYSTEM_USER = 57760
const TABLE = 57761
const TABLES = 57762
const TABLESAMPLE = 57763
const TABLESPACE = 57764
const TARGET = 57765
const TEMP = 57766
const TEMPLATE = 57767
const TEMPORARY = 57768
const TEXT_P = 57769
const THEN = 57770
const TIES = 57771
const TIME = 57772
const TIMESTAMP = 57773
const TO = 57774
const TRAILING = 57775
const TRANSACTION = 57776
const TRANSFORM = 57777
const TREAT = 57778
const TRIGGER = 57779
const TRIM = 57780
const TRUE_P = 57781
const TRUNCATE = 57782
const TRUSTED = 57783
const TYPE_P = 57784
const TYPES_P = 57785
const UESCAPE = 57786
const UNBOUNDED = 57787
const UNCOMMITTED = 57788
const UNCONDITIONAL = 57789
const UNENCRYPTED = 57790
const UNION = 57791
const UNIQUE = 57792
const UNKNOWN = 57793
const UNLISTEN = 57794
const UNLOGGED = 57795
const UNTIL = 57796
const UPDATE = 57797
const USER = 57798
const USING = 57799
const VACUUM = 57800
const VALID = 57801
const VALIDATE = 57802
const VALIDATOR = 57803
const VALUE_P = 57804
const VALUES = 57805
const VARCHAR = 57806
const VARIADIC = 57807
const VARYING = 57808
const VERBOSE = 57809
const VERSION_P = 57810
const VIEW = 57811
const VIEWS = 57812
const VIRTUAL = 57813
const VOLATILE = 57814
const WHEN = 57815
const WHERE = 57816
const WHITESPACE_P = 57817
const WINDOW = 57818
const WITH = 57819
const WITHIN = 57820
const WITHOUT = 57821
const WORK = 57822
const WRAPPER = 57823
const WRITE = 57824
const XML_P = 57825
const XMLATTRIBUTES = 57826
const XMLCONCAT = 57827
const XMLELEMENT = 57828
const XMLEXISTS = 57829
const XMLFOREST = 57830
const XMLNAMESPACES = 57831
const XMLPARSE = 57832
const XMLPI = 57833
const XMLROOT = 57834
const XMLSERIALIZE = 57835
const XMLTABLE = 57836
const YEAR_P = 57837
const YES_P = 57838
const ZONE = 57839
const IDENT = 57840
const UIDENT = 57841
const FCONST = 57842
const SCONST = 57843
const USCONST = 57844
const BCONST = 57845
const XCONST = 57846
const Op = 57847
const ICONST = 57848
const PARAM = 57849
const TYPECAST = 57850
const DOT_DOT = 57851
const COLON_EQUALS = 57852
const EQUALS_GREATER = 57853
const LESS_EQUALS = 57854
const GREATER_EQUALS = 57855
const NOT_EQUALS = 57856
const NOT_LA = 57857
const NULLS_LA = 57858
const WITH_LA = 57859
const WITHOUT_LA = 57860
const FORMAT_LA = 57861

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ABORT_P",
	"ABSENT",
	"ABSOLUTE_P",
	"ACCESS",
	"ACTION",
	"ADD_P",
	"ADMIN",
	"AFTER",
	"AGGREGATE",
	"ALL",
	"ALSO",
	"ALTER",
	"ALWAYS",
	"ANALYSE",
	"ANALYZE",
	"AND",
	"ANY",
	"ARRAY",
	"AS",
	"ASC",
	"ASENSITIVE",
	"ASSERTION",
	"ASSIGNMENT",
	"ASYMMETRIC",
	"AT",
	"ATOMIC",
	"ATTACH",
	"ATTRIBUTE",
	"AUTHORIZATION",
	"BACKWARD",
	"BEFORE",
	"BEGIN_P",
	"BETWEEN",
	"BIGINT",
	"BINARY",
	"BIT",
	"BOOLEAN_P",
	"BOTH",
	"BREADTH",
	"BY",
	"CACHE",
	"CALL",
	"CALLED",
	"CASCADE",
	"CASCADED",
	"CASE",
	"CAST",
	"CATALOG_P",
	"CHAIN",
	"CHAR_P",
	"CHARACTER",
	"CHARACTERISTICS",
	"CHECK",
	"CHECKPOINT",
	"CLASS",
	"CLOSE",
	"CLUSTER",
	"COALESCE",
	"COLLATE",
	"COLLATION",
	"COLUMN",
	"COLUMNS",
	"COMMENT",
	"COMMENTS",
	"COMMIT",
	"COMMITTED",
	"COMPRESSION",
	"CONCURRENTLY",
	"CONDITIONAL",
	"CONFIGURATION",
	"CONFLICT",
	"CONNECTION",
	"CONSTRAINT",
	"CONSTRAINTS",
	"CONTENT_P",
	"CONTINUE_P",
	"CONVERSION_P",
	"COPY",
	"COST",
	"CREATE",
	"CROSS",
	"CSV",
	"CUBE",
	"CURRENT_P",
	"CURRENT_CATALOG",
	"CURRENT_DATE",
	"CURRENT_ROLE",
	"CURRENT_SCHEMA",
	"CURRENT_TIME",
	"CURRENT_TIMESTAMP",
	"CURRENT_USER",
	"CURSOR",
	"CYCLE",
	"DATA_P",
	"DATABASE",
	"DAY_P",
	"DEALLOCATE",
	"DEC",
	"DECIMAL_P",
	"DECLARE",
	"DEFAULT",
	"DEFAULTS",
	"DEFERRABLE",
	"DEFERRED",
	"DEFINER",
	"DELETE_P",
	"DELIMITER",
	"DELIMITERS",
	"DEPENDS",
	"DEPTH",
	"DESC",
	"DETACH",
	"DICTIONARY",
	"DISABLE_P",
	"DISCARD",
	"DISTINCT",
	"DO",
	"DOCUMENT_P",
	"DOMAIN_P",
	"DOUBLE_P",
	"DROP",
	"EACH",
	"ELSE",
	"EMPTY_P",
	"ENABLE_P",
	"ENCODING",
	"ENCRYPTED",
	"END_P",
	"ENFORCED",
	"ENUM_P",
	"ERROR_P",
	"ESCAPE",
	"EVENT",
	"EXCEPT",
	"EXCLUDE",
	"EXCLUDING",
	"EXCLUSIVE",
	"EXECUTE",
	"EXISTS",
	"EXPLAIN",
	"EXPRESSION",
	"EXTENSION",
	"EXTERNAL",
	"EXTRACT",
	"FALSE_P",
	"FAMILY",
	"FETCH",
	"FILTER",
	"FINALIZE",
	"FIRST_P",
	"FLOAT_P",
	"FOLLOWING",
	"FOR",
	"FORCE",
	"FOREIGN",
	"FORMAT",
	"FORWARD",
	"FREEZE",
	"FROM",
	"FULL",
	"FUNCTION",
	"FUNCTIONS",
	"GENERATED",
	"GLOBAL",
	"GRANT",
	"GRANTED",
	"GREATEST",
	"GROUP_P",
	"GROUPING",
	"GROUPS",
	"HANDLER",
	"HAVING",
	"HEADER_P",
	"HOLD",
	"HOUR_P",
	"IDENTITY_P",
	"IF_P",
	"ILIKE",
	"IMMEDIATE",
	"IMMUTABLE",
	"IMPLICIT_P",
	"IMPORT_P",
	"IN_P",
	"INCLUDE",
	"INCLUDING",
	"INCREMENT",
	"INDENT",
	"INDEX",
	"INDEXES",
	"INHERIT",
	"INHERITS",
	"INITIALLY",
	"INLINE_P",
	"INNER_P",
	"INOUT",
	"INPUT_P",
	"INSENSITIVE",
	"INSERT",
	"INSTEAD",
	"INT_P",
	"INTEGER",
	"INTERSECT",
	"INTERVAL",
	"INTO",
	"INVOKER",
	"IS",
	"ISNULL",
	"ISOLATION",
	"JOIN",
	"JSON",
	"JSON_ARRAY",
	"JSON_ARRAYAGG",
	"JSON_EXISTS",
	"JSON_OBJECT",
	"JSON_OBJECTAGG",
	"JSON_QUERY",
	"JSON_SCALAR",
	"JSON_SERIALIZE",
	"JSON_TABLE",
	"JSON_VALUE",
	"KEEP",
	"KEY",
	"KEYS",
	"LABEL",
	"LANGUAGE",
	"LARGE_P",
	"LAST_P",
	"LATERAL_P",
	"LEADING",
	"LEAKPROOF",
	"LEAST",
	"LEFT",
	"LEVEL",
	"LIKE",
	"LIMIT",
	"LISTEN",
	"LOAD",
	"LOCAL",
	"LOCALTIME",
	"LOCALTIMESTAMP",
	"LOCATION",
	"LOCK_P",
	"LOCKED",
	"LOGGED",
	"MAPPING",
	"MATCH",
	"MATCHED",
	"MATERIALIZED",
	"MAXVALUE",
	"MERGE",
	"MERGE_ACTION",
	"METHOD",
	"MINUTE_P",
	"MINVALUE",
	"MODE",
	"MONTH_P",
	"MOVE",
	"NAME_P",
	"NAMES",
	"NATIONAL",
	"NATURAL",
	"NCHAR",
	"NESTED",
	"NEW",
	"NEXT",
	"NFC",
	"NFD",
	"NFKC",
	"NFKD",
	"NO",
	"NONE",
	"NORMALIZE",
	"NORMALIZED",
	"NOT",
	"NOTHING",
	"NOTIFY",
	"NOTNULL",
	"NOWAIT",
	"NULL_P",
	"NULLIF",
	"NULLS_P",
	"NUMERIC",
	"OBJECT_P",
	"OBJECTS_P",
	"OF",
	"OFF",
	"OFFSET",
	"OIDS",
	"OLD",
	"OMIT",
	"ON",
	"ONLY",
	"OPERATOR",
	"OPTION",
	"OPTIONS",
	"OR",
	"ORDER",
	"ORDINALITY",
	"OTHERS",
	"OUT_P",
	"OUTER_P",
	"OVER",
	"OVERLAPS",
	"OVERLAY",
	"OVERRIDING",
	"OWNED",
	"OWNER",
	"PARALLEL",
	"PARAMETER",
	"PARSER",
	"PARTIAL",
	"PARTITION",
	"PASSING",
	"PASSWORD",
	"PATH",
	"PERIOD",
	"PLACING",
	"PLAN",
	"PLANS",
	"POLICY",
	"POSITION",
	"PRECEDING",
	"PRECISION",
	"PREPARE",
	"PREPARED",
	"PRESERVE",
	"PRIMARY",
	"PRIOR",
	"PRIVILEGES",
	"PROCEDURAL",
	"PROCEDURE",
	"PROCEDURES",
	"PROGRAM",
	"PUBLICATION",
	"QUOTE",
	"QUOTES",
	"RANGE",
	"READ",
	"REAL",
	"REASSIGN",
	"RECURSIVE",
	"REF_P",
	"REFERENCES",
	"REFERENCING",
	"REFRESH",
	"REINDEX",
	"RELATIVE_P",
	"RELEASE",
	"RENAME",
	"REPEATABLE",
	"REPLACE",
	"REPLICA",
	"RESET",
	"RESTART",
	"RESTRICT",
	"RETURN",
	"RETURNING",
	"RETURNS",
	"REVOKE",
	"RIGHT",
	"ROLE",
	"ROLLBACK",
	"ROLLUP",
	"ROUTINE",
	"ROUTINES",
	"ROW",
	"ROWS",
	"RULE",
	"SAVEPOINT",
	"SCALAR",
	"SCHEMA",
	"SCHEMAS",
	"SCROLL",
	"SEARCH",
	"SECOND_P",
	"SECURITY",
	"SELECT",
	"SEQUENCE",
	"SEQUENCES",
	"SERIALIZABLE",
	"SERVER",
	"SESSION",
	"SESSION_USER",
	"SET",
	"SETOF",
	"SETS",
	"SHARE",
	"SHOW",
	"SIMILAR",
	"SIMPLE",
	"SKIP",
	"SMALLINT",
	"SNAPSHOT",
	"SOME",
	"SOURCE",
	"SQL_P",
	"STABLE",
	"STANDALONE_P",
	"START",
	"STATEMENT",
	"STATISTICS",
	"STDIN",
	"STDOUT",
	"STORAGE",
	"STORED",
	"STRICT_P",
	"STRING_P",
	"STRIP_P",
	"SUBSCRIPTION",
	"SUBSTRING",
	"SUPPORT",
	"SYMMETRIC",
	"SYSID",
	"SYSTEM_P",
	"SYSTEM_USER",
	"TABLE",
	"TABLES",
	"TABLESAMPLE",
	"TABLESPACE",
	"TARGET",
	"TEMP",
	"TEMPLATE",
	"TEMPORARY",
	"TEXT_P",
	"THEN",
	"TIES",
	"TIME",
	"TIMESTAMP",
	"TO",
	"TRAILING",
	"TRANSACTION",
	"TRANSFORM",
	"TREAT",
	"TRIGGER",
	"TRIM",
	"TRUE_P",
	"TRUNCATE",
	"TRUSTED",
	"TYPE_P",
	"TYPES_P",
	"UESCAPE",
	"UNBOUNDED",
	"UNCOMMITTED",
	"UNCONDITIONAL",
	"UNENCRYPTED",
	"UNION",
	"UNIQUE",
	"UNKNOWN",
	"UNLISTEN",
	"UNLOGGED",
	"UNTIL",
	"UPDATE",
	"USER",
	"USING",
	"VACUUM",
	"VALID",
	"VALIDATE",
	"VALIDATOR",
	"VALUE_P",
	"VALUES",
	"VARCHAR",
	"VARIADIC",
	"VARYING",
	"VERBOSE",
	"VERSION_P",
	"VIEW",
	"VIEWS",
	"VIRTUAL",
	"VOLATILE",
	"WHEN",
	"WHERE",
	"WHITESPACE_P",
	"WINDOW",
	"WITH",
	"WITHIN",
	"WITHOUT",
	"WORK",
	"WRAPPER",
	"WRITE",
	"XML_P",
	"XMLATTRIBUTES",
	"XMLCONCAT",
	"XMLELEMENT",
	"XMLEXISTS",
	"XMLFOREST",
	"XMLNAMESPACES",
	"XMLPARSE",
	"XMLPI",
	"XMLROOT",
	"XMLSERIALIZE",
	"XMLTABLE",
	"YEAR_P",
	"YES_P",
	"ZONE",
	"IDENT",
	"UIDENT",
	"FCONST",
	"SCONST",
	"USCONST",
	"BCONST",
	"XCONST",
	"Op",
	"ICONST",
	"PARAM",
	"TYPECAST",
	"DOT_DOT",
	"COLON_EQUALS",
	"EQUALS_GREATER",
	"LESS_EQUALS",
	"GREATER_EQUALS",
	"NOT_EQUALS",
	"NOT_LA",
	"NULLS_LA",
	"WITH_LA",
	"WITHOUT_LA",
	"FORMAT_LA",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line ../../tmp/goopg_grammar.y:156

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 1

var yyAct = [...]int8{
	1,
}

var yyPact = [...]int16{
	-32768, -32768,
}

var yyPgo = [...]int8{
	0, 0,
}

var yyR1 = [...]int8{
	0, 1,
}

var yyR2 = [...]int8{
	0, 0,
}

var yyChk = [...]int16{
	-32768, -1,
}

var yyDef = [...]int8{
	1, -2,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int16{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
	122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
	132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
	142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
	152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
	162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
	172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
	182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
	192, 193, 194, 195, 196, 197, 198, 199, 200, 201,
	202, 203, 204, 205, 206, 207, 208, 209, 210, 211,
	212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
	222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
	232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
	242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
	252, 253, 254, 255, 256, 257,
}

var yyTok3 = [...]uint16{
	57600, 258, 57601, 259, 57602, 260, 57603, 261, 57604, 262,
	57605, 263, 57606, 264, 57607, 265, 57608, 266, 57609, 267,
	57610, 268, 57611, 269, 57612, 270, 57613, 271, 57614, 272,
	57615, 273, 57616, 274, 57617, 275, 57618, 276, 57619, 277,
	57620, 278, 57621, 279, 57622, 280, 57623, 281, 57624, 282,
	57625, 283, 57626, 284, 57627, 285, 57628, 286, 57629, 287,
	57630, 288, 57631, 289, 57632, 290, 57633, 291, 57634, 292,
	57635, 293, 57636, 294, 57637, 295, 57638, 296, 57639, 297,
	57640, 298, 57641, 299, 57642, 300, 57643, 301, 57644, 302,
	57645, 303, 57646, 304, 57647, 305, 57648, 306, 57649, 307,
	57650, 308, 57651, 309, 57652, 310, 57653, 311, 57654, 312,
	57655, 313, 57656, 314, 57657, 315, 57658, 316, 57659, 317,
	57660, 318, 57661, 319, 57662, 320, 57663, 321, 57664, 322,
	57665, 323, 57666, 324, 57667, 325, 57668, 326, 57669, 327,
	57670, 328, 57671, 329, 57672, 330, 57673, 331, 57674, 332,
	57675, 333, 57676, 334, 57677, 335, 57678, 336, 57679, 337,
	57680, 338, 57681, 339, 57682, 340, 57683, 341, 57684, 342,
	57685, 343, 57686, 344, 57687, 345, 57688, 346, 57689, 347,
	57690, 348, 57691, 349, 57692, 350, 57693, 351, 57694, 352,
	57695, 353, 57696, 354, 57697, 355, 57698, 356, 57699, 357,
	57700, 358, 57701, 359, 57702, 360, 57703, 361, 57704, 362,
	57705, 363, 57706, 364, 57707, 365, 57708, 366, 57709, 367,
	57710, 368, 57711, 369, 57712, 370, 57713, 371, 57714, 372,
	57715, 373, 57716, 374, 57717, 375, 57718, 376, 57719, 377,
	57720, 378, 57721, 379, 57722, 380, 57723, 381, 57724, 382,
	57725, 383, 57726, 384, 57727, 385, 57728, 386, 57729, 387,
	57730, 388, 57731, 389, 57732, 390, 57733, 391, 57734, 392,
	57735, 393, 57736, 394, 57737, 395, 57738, 396, 57739, 397,
	57740, 398, 57741, 399, 57742, 400, 57743, 401, 57744, 402,
	57745, 403, 57746, 404, 57747, 405, 57748, 406, 57749, 407,
	57750, 408, 57751, 409, 57752, 410, 57753, 411, 57754, 412,
	57755, 413, 57756, 414, 57757, 415, 57758, 416, 57759, 417,
	57760, 418, 57761, 419, 57762, 420, 57763, 421, 57764, 422,
	57765, 423, 57766, 424, 57767, 425, 57768, 426, 57769, 427,
	57770, 428, 57771, 429, 57772, 430, 57773, 431, 57774, 432,
	57775, 433, 57776, 434, 57777, 435, 57778, 436, 57779, 437,
	57780, 438, 57781, 439, 57782, 440, 57783, 441, 57784, 442,
	57785, 443, 57786, 444, 57787, 445, 57788, 446, 57789, 447,
	57790, 448, 57791, 449, 57792, 450, 57793, 451, 57794, 452,
	57795, 453, 57796, 454, 57797, 455, 57798, 456, 57799, 457,
	57800, 458, 57801, 459, 57802, 460, 57803, 461, 57804, 462,
	57805, 463, 57806, 464, 57807, 465, 57808, 466, 57809, 467,
	57810, 468, 57811, 469, 57812, 470, 57813, 471, 57814, 472,
	57815, 473, 57816, 474, 57817, 475, 57818, 476, 57819, 477,
	57820, 478, 57821, 479, 57822, 480, 57823, 481, 57824, 482,
	57825, 483, 57826, 484, 57827, 485, 57828, 486, 57829, 487,
	57830, 488, 57831, 489, 57832, 490, 57833, 491, 57834, 492,
	57835, 493, 57836, 494, 57837, 495, 57838, 496, 57839, 497,
	57840, 498, 57841, 499, 57842, 500, 57843, 501, 57844, 502,
	57845, 503, 57846, 504, 57847, 505, 57848, 506, 57849, 507,
	57850, 508, 57851, 509, 57852, 510, 57853, 511, 57854, 512,
	57855, 513, 57856, 514, 57857, 515, 57858, 516, 57859, 517,
	57860, 518, 57861, 519, 0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ../../tmp/goopg_grammar.y:142
		{
			yylex.(*lexerState).out = nil
		}
	}
	goto yystack /* stack new state and value */
}
