// Command gen-tokennums-go extracts the numeric token values that goyacc
// assigned (const NAME = <n> lines in the generated parser) and emits a
// name→number table for the lexer adapter.
//
// Why this exists: goyacc assigns NAMED terminals values in the Unicode
// private-use range (yyPrivate=57344 + n). The compact yyToknames array is
// error-printing only — its index+1 does NOT equal the parser value. The
// adapter therefore needs the real constants, and referencing 494+
// identifiers by hand is unmaintainable, so we scrape them from the
// generated source (the authoritative assignment).
//
// Regenerate via `make gen-parser` (runs right after goyacc).
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var constRe = regexp.MustCompile(`(?m)^const\s+([A-Za-z_][A-Za-z_0-9]*)\s*=\s*(\d+)\s*$`)

func main() {
	in := flagStr("in", "internal/parser/yacc_parser.go", "generated parser path")
	out := flagStr("out", "internal/parser/tokennums_gen.go", "output table path")
	src, err := os.ReadFile(*in)
	if err != nil {
		fail("read %s: %v", *in, err)
	}
	matches := constRe.FindAllStringSubmatch(string(src), -1)
	if len(matches) == 0 {
		fail("no `const NAME = n` lines found in %s", *in)
	}
	nums := make(map[string]int, len(matches))
	for _, m := range matches {
		nums[m[1]] = atoi(m[2])
	}
	names := make([]string, 0, len(nums))
	for n := range nums {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cmd/gen-tokennums-go FROM %s. DO NOT EDIT.\n", filepath.Base(*in))
	b.WriteString("// Maps goyacc terminal names to their parser-space values\n")
	b.WriteString("// (Unicode private-use range; see tables.go notes).\n\n")
	b.WriteString("package parser\n\n")
	b.WriteString(fmt.Sprintf("// %d terminals scraped from the generated parser.\n", len(nums)))
	b.WriteString("var genTokenNums = map[string]int{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t%q: %d,\n", n, nums[n])
	}
	b.WriteString("}\n")

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fail("mkdir: %v", err)
	}
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fail("write %s: %v", *out, err)
	}
	fmt.Fprintf(os.Stderr, "gen-tokennums-go: wrote %d terminals to %s\n", len(nums), *out)
}

func flagStr(name, def, usage string) *string {
	return flag.String(name, def, usage)
}

func atoi(s string) int {
	n := 0
	for i := 0; i < len(s); i++ {
		n = n*10 + int(s[i]-'0')
	}
	return n
}

func fail(f string, a ...any) {
	fmt.Fprintf(os.Stderr, "gen-tokennums-go: "+f+"\n", a...)
	os.Exit(1)
}
