create table t(a int, b int);
insert into t select g % 50, g from generate_series(1, 5000) g;
analyze t;
explain (costs off) select * from (select sum(b) s from t group by a) x;
explain (costs off) select * from (select b from t order by a) x;
explain (costs off) select * from (select a, rank() over (order by b) r from t) w;
explain (costs off) select * from (select a, b, rank() over (order by b) r from t) w;
explain (costs off) select * from (select b, a, rank() over (order by b) r from t) w;
explain (costs off) select * from (select a, b, rank() over (partition by b order by a) r from t) w;
explain (costs off) select a, c, rank() over (order by c) from (select a, sum(b) c from t group by a) v;
explain (costs off) select c, a, rank() over (order by c) from (select a, sum(b) c from t group by a) v;
explain (costs off) select a, c, rank() over (partition by a order by c) from (select a, sum(b) c from t group by a) v;
explain (costs off) select a+1, c, rank() over (order by c) from (select a, sum(b) c from t group by a) v;
explain (costs off) select c, rank() over (order by a) from (select a, sum(b) c from t group by a) v;
explain (costs off) select rank() over (order by c), a, c from (select a, sum(b) c from t group by a) v;
explain (costs off) select count(*) from (select sum(b) s from t group by a) x;
explain (costs off) select * from t, (select sum(b) s from t group by a) x where t.b = x.s;
explain (costs off) select * from (select sum(b) s from t group by a order by sum(b)) x;
explain (costs off) select * from (select b from t order by 1) x;
explain (costs off) select * from (select b as z from t order by z) x;
explain (costs off) select * from (select a, sum(b) s from t group by 1) x;
explain (costs off) select * from (select distinct on (a) a, b from t order by a, b) x;
explain (costs off) select * from (select a, b from t order by a+1) x;
