package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/goopg/goopg/internal/testport/framework"
)

func main() {
	var (
		repoRoot = flag.String("repo-root", ".", "path to repository root")
		outPath  = flag.String("out", "docs/test-port/upstream-regress-coverage.md", "output markdown path")
	)
	flag.Parse()

	root, err := filepath.Abs(*repoRoot)
	if err != nil {
		fail("resolve repo root", err)
	}
	cases, err := framework.DiscoverRegressCases(root)
	if err != nil {
		fail("discover regress cases", err)
	}

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fail("mkdir output dir", err)
	}
	f, err := os.Create(*outPath)
	if err != nil {
		fail("create output", err)
	}
	defer f.Close()

	fmt.Fprintln(f, "# Upstream pg_regress Coverage Classification")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "Generated by `go run ./cmd/gen-regress-coverage --repo-root . --out docs/test-port/upstream-regress-coverage.md`.")
	fmt.Fprintf(f, "Generated at: %s\n\n", time.Now().Format(time.RFC3339))
	fmt.Fprintf(f, "Total discovered SQL cases: **%d**\n\n", len(cases))
	fmt.Fprintln(f, "Status policy for this phase:")
	fmt.Fprintln(f, "- `defer`: migration target discovered but not pass-required yet.")
	fmt.Fprintln(f, "- `port`: used only after a case is wired to a concrete Go port test.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "| name | sql_path | expected_path | status | rationale |")
	fmt.Fprintln(f, "| ---- | -------- | ------------- | ------ | --------- |")
	for _, c := range cases {
		rationale := "Harness-ready discovery complete; execution parity deferred to staged porting."
		status := "defer"
		if strings.TrimSpace(c.ExpectedPath) == "" {
			rationale = "No matching expected file found; needs expectation mapping."
		}
		fmt.Fprintf(f, "| %s | `%s` | `%s` | %s | %s |\n", c.Name, c.SQLPath, c.ExpectedPath, status, rationale)
	}
}

func fail(where string, err error) {
	fmt.Fprintf(os.Stderr, "gen-regress-coverage: %s: %v\n", where, err)
	os.Exit(1)
}
