select * from (select s_store_sk, s_store_name from store where s_store_sk < 4) y, (select r_reason_sk k from reason where r_reason_sk < 3) x order by 1,3;
select y.*, x.k from (select s_store_sk, s_store_name from store where s_store_sk < 4) y, (select r_reason_sk k from reason where r_reason_sk < 3) x order by 1,3;
select y, x.k from (select s_store_sk, s_store_name from store where s_store_sk < 3) y, (select r_reason_sk k from reason where r_reason_sk < 3) x order by 2,1;
select n, count(*) from (select s_store_name n, s_store_sk from store) y, reason where r_reason_sk = s_store_sk group by n order by n;
select s_store_sk from (select s_store_sk from store) y, (select s_store_sk from store) z order by 1 limit 3;
select y.s_store_sk from (select s_store_sk from store where s_store_sk<3) y, (select s_store_sk from store where s_store_sk<3) z where y.s_store_sk = z.s_store_sk order by 1;
select s_store_name from (select s_store_sk k from store) y, reason where k = r_reason_sk order by 1 limit 2;
select store.s_store_sk from (select s_store_sk from store) y, reason limit 1;
select k, (select count(*) from reason r2 where r2.r_reason_sk = y.k) from (select r_reason_sk k from reason) y, (select s_store_sk from store where s_store_sk = 1) z order by 1 limit 4;
select a.k from (select r_reason_sk k from reason, store where r_reason_sk = s_store_sk) a, (select d_date_sk from date_dim where d_date_sk = 2415022) b order by 1;
select k, s from (select r_reason_sk k, r_reason_desc s from reason where r_reason_sk in (1,2)) y, store where s_store_sk = k order by 1;
select y.k2 from (select r_reason_sk as k2, r_reason_id from reason) y, (select 1 as one) z where y.k2 <= 2 order by 1;
select * from (select s_store_sk, s_store_name from store where s_store_sk < 4) y, reason x where x.r_reason_sk < 4 order by 3 desc, 1;
select * from (select s_store_sk, s_store_name from store where s_store_sk < 4) y, (select r_reason_sk k from reason where r_reason_sk < 4) x order by 3 desc, 1;
select distinct * from (select s_store_name n from store) y, (select r_reason_sk k from reason where r_reason_sk < 3) x order by 2 desc, 1;
select n, count(*) from (select s_store_name n, s_store_sk from store) y, (select r_reason_sk k from reason) x where k = s_store_sk group by 1 order by 1;
select * from (select r_reason_sk, r_reason_desc from reason where r_reason_sk < 3) y join reason z using (r_reason_sk), store where s_store_sk = 1 order by 1;
select count(*) from (select ss_item_sk i, ss_ticket_number t from store_sales, date_dim where ss_sold_date_sk = d_date_sk and d_year = 2000) y, item where i = i_item_sk and i_category = 'Music';
select v, w from (select s_store_sk * 2 as v, s_store_sk w from store where s_store_sk < 4) y, reason where r_reason_sk = w order by 1;
select * from (select s_store_sk + 1, s_store_name from store where s_store_sk < 3) y order by 1;
select y from (select s_store_sk * 10 as v, s_store_name n from store where s_store_sk < 3) y order by 1;
select v, count(*) from (select s_store_sk % 2 as v from store) y group by v order by v;
select count(*) from (select extract(year from d_date) as yr, d_date_sk from date_dim where d_year = 2000) y, store_sales where ss_sold_date_sk = d_date_sk and yr = 2000;
select v, (select count(*) from reason r where r.r_reason_sk = y.v) from (select s_store_sk + 0 as v from store where s_store_sk < 4) y order by 1;
select k from (select s_store_sk as k from store, reason where s_store_sk = r_reason_sk) y where k < 3 order by k;
select case when v > 2 then 'big' else 'small' end, count(*) from (select s_store_sk as v from store) y group by 1 order by 1;
select * from (select s_store_sk from store where s_store_sk = 1) y;
select k, n from (select s_store_sk k, r_reason_desc n from store join reason on s_store_sk = r_reason_sk where s_store_sk < 4) y order by k;
select y.*, x.k2 from (select s_store_sk k, r_reason_sk r from store join reason on s_store_sk = r_reason_sk) y, (select r_reason_sk k2 from reason where r_reason_sk < 3) x where y.k = x.k2 order by 1;
select count(*) from (select ss_item_sk i from store_sales join date_dim on ss_sold_date_sk = d_date_sk cross join store where d_year = 2000 and s_store_sk = ss_store_sk) y, item where i = i_item_sk and i_category = 'Music';
select k from (select s_store_sk k from store inner join reason on s_store_sk = r_reason_sk and r_reason_sk > 2) y order by 1;
select count(*), sum(act) from (select ss_ticket_number t, case when sr_return_quantity is not null then (ss_quantity - sr_return_quantity) * ss_sales_price else ss_quantity * ss_sales_price end act from store_sales left outer join store_returns on (sr_item_sk = ss_item_sk and sr_ticket_number = ss_ticket_number)) y;
select count(*) from (select ss_ticket_number t from store_sales left join store_returns on sr_item_sk = ss_item_sk and sr_ticket_number = ss_ticket_number where sr_ticket_number is null) y;
select count(*) from (select ss_ticket_number t, sr_reason_sk r from store_sales left join store_returns on sr_item_sk = ss_item_sk and sr_ticket_number = ss_ticket_number, reason where sr_reason_sk = r_reason_sk and r_reason_desc = 'reason 28') y;
select count(*), count(a), count(b) from (select s_store_sk a, r_reason_sk b from store full join reason on s_store_sk = r_reason_sk) y;
select a, b from (select s_store_sk a, r_reason_sk b from store right join reason on s_store_sk = r_reason_sk where r_reason_sk < 5) y order by 2;
