package parser

import "testing"

// TestImplicitRowConstructor pins `(a, b) op (x, y)`, the LAST structural
// blocker, and the fix that made it free: the parenthesised expression now
// lives in c_expr as gram.y :15540 has it, instead of as two separate copies
// in a_expr and b_expr. That split was the "a_expr/b_expr c_expr split" behind
// every reduce/reduce measurement on this grammar — the parser had to decide,
// right after '(', whether the inside was an a_expr or a b_expr, and any third
// rule sharing the prefix collided with both. With one rule, implicit_row
// beside it merely shares a prefix state and ',' versus ')' decides. Cost:
// zero conflicts.
//
// Legacy builds RowExpr for the implicit form and a plain row(...) FuncCall
// for the explicit ROW(...) spelling; it rejects indirection on either.
func TestImplicitRowConstructor(t *testing.T) {
	for _, q := range []string{
		"SELECT (1, 2)",
		"SELECT ((1, 2))",
		"SELECT ROW(1, 2)",
		"SELECT (1, 2) = ROW(1, 2)",
		"SELECT * FROM t WHERE (a, b) > ('x', 0)",
		"SELECT * FROM t WHERE (a, b) = (1, 2)",
		"SELECT * FROM t WHERE (a, b) IN ((1, 2), (3, 4))",
		"SELECT * FROM t WHERE (a, b) IN (SELECT 1, 2)",
		"SELECT (a, b) IS NULL FROM t",
		"SELECT proname, proargtypes, pronamespace FROM pg_proc WHERE (proname, pronamespace) > ('abs', 0) ORDER BY proname, proargtypes, pronamespace",
		// Grouping parens, from every context that used to have its own copy.
		"SELECT (1)",
		"SELECT ((1))",
		"SELECT (a + b) * c FROM t",
		"SELECT -(a) FROM t",
		"SELECT (a)::int FROM t",
		"SELECT a FROM t WHERE a BETWEEN (1) AND (2 + 3)",
		"SELECT a FROM t WHERE a BETWEEN (b) AND c",
		"SELECT a FROM t ORDER BY a FETCH FIRST (NULL+1) ROWS WITH TIES",
		"SELECT * FROM t WHERE a IN (1, 2)",
	} {
		assertParity(t, q)
	}
	for _, q := range []string{
		"SELECT (a, b).f1 FROM t",
		"SELECT (a).b FROM t",
		"SELECT (a, b) OVERLAPS (c, d)",
	} {
		assertBothReject(t, q)
	}
}

// TestWholeRowStarExpression pins `tbl.*` as an EXPRESSION — VALUES(n.*),
// f(n.*), count(t.*) — which had been recorded as costing 20 reduce/reduce.
// The real collision was never the a_expr/b_expr split: target_el carried its
// OWN `qualified_name '.' '*'` copy, and the two reduced in the same state,
// one conflict per token that can follow a target entry. Only c_expr spells
// it now; target_el reaches it through a_expr and builds the same StarExpr.
func TestWholeRowStarExpression(t *testing.T) {
	for _, q := range []string{
		"SELECT t.* FROM t",
		"SELECT t.*, a FROM t",
		"SELECT a, t.* FROM t",
		"SELECT s.t.* FROM s.t",
		"SELECT t.* FROM t WHERE a = 1 ORDER BY b",
		"VALUES(n.*)",
		"SELECT * FROM nocols n, LATERAL (VALUES(n.*)) v",
		"SELECT f(n.*) FROM t n",
		"SELECT count(t.*) FROM t",
		"SELECT n.* AS x FROM t n",
		"SELECT * FROM t",
	} {
		assertParity(t, q)
	}
	assertBothReject(t, "SELECT (n).* FROM t n")
}

// TestIdentitySequenceOptions pins `GENERATED ... AS IDENTITY (START WITH n
// ...)` — the option list legacy's identity parser takes (ddl.go:4715-4755)
// — on BOTH the CREATE TABLE column and the ALTER TABLE ADD COLUMN sibling.
// The ALTER action had been copying only NotNull and DEFAULT from the
// constraint carrier, silently dropping identity altogether while CREATE
// TABLE kept it, and `add column` is routed.
func TestIdentitySequenceOptions(t *testing.T) {
	for _, q := range []string{
		"CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY)",
		"CREATE TABLE t (id int GENERATED BY DEFAULT AS IDENTITY)",
		"CREATE TABLE truncate_b (id int GENERATED ALWAYS AS IDENTITY (START WITH 44))",
		"CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY (START WITH 44 INCREMENT BY 2 MINVALUE 1 MAXVALUE 100 CACHE 5 CYCLE))",
		"CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY (INCREMENT 2 START 10 NO CYCLE))",
		"CREATE TABLE t (id int GENERATED BY DEFAULT AS IDENTITY (START WITH -5 NO MINVALUE NO MAXVALUE) PRIMARY KEY)",
		"ALTER TABLE t ADD COLUMN id int GENERATED ALWAYS AS IDENTITY",
		"ALTER TABLE t ADD COLUMN id int GENERATED BY DEFAULT AS IDENTITY (START WITH 5)",
		"ALTER TABLE t ADD COLUMN id int NOT NULL DEFAULT 1",
	} {
		assertParity(t, q)
	}
}
