package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/goopg/goopg/internal/testport/framework"
)

func main() {
	var (
		repoRoot = flag.String("repo-root", ".", "path to repository root")
		outPath  = flag.String("out", "docs/test-port/upstream-isolation-coverage.md", "output markdown path")
	)
	flag.Parse()

	root, err := filepath.Abs(*repoRoot)
	if err != nil {
		fail("resolve repo root", err)
	}
	paths, err := framework.DiscoverIsolationSpecs(root)
	if err != nil {
		fail("discover isolation specs", err)
	}

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fail("mkdir output dir", err)
	}
	f, err := os.Create(*outPath)
	if err != nil {
		fail("create output", err)
	}
	defer f.Close()

	fmt.Fprintln(f, "# Upstream isolation Spec Coverage Classification")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "Generated by `go run ./cmd/gen-isolation-coverage --repo-root . --out docs/test-port/upstream-isolation-coverage.md`.")
	fmt.Fprintf(f, "Generated at: %s\n\n", time.Now().Format(time.RFC3339))
	fmt.Fprintf(f, "Total discovered specs: **%d**\n\n", len(paths))
	fmt.Fprintln(f, "Status policy for this phase:")
	fmt.Fprintln(f, "- `defer`: scheduler/parity not pass-required yet.")
	fmt.Fprintln(f, "- `port`: used after a spec is wired and validated end-to-end.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "| spec | status | rationale |")
	fmt.Fprintln(f, "| ---- | ------ | --------- |")
	for _, p := range paths {
		name := strings.TrimSuffix(filepath.Base(p), filepath.Ext(p))
		rationale := "Deterministic scheduler foundation available; execution parity deferred to staged migration."
		fmt.Fprintf(f, "| `%s` | defer | %s (case `%s`) |\n", p, rationale, name)
	}
}

func fail(where string, err error) {
	fmt.Fprintf(os.Stderr, "gen-isolation-coverage: %s: %v\n", where, err)
	os.Exit(1)
}
