package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type row struct {
	Path      string
	Status    string
	Rationale string
}

type specMeta struct {
	status    string
	rationale string
}

// loadCSV parses the inventory CSV and returns a map of item_path → specMeta
// for rows where kind == "tap".
func loadCSV(csvPath string) (map[string]specMeta, error) {
	f, err := os.Open(csvPath)
	if err != nil {
		return nil, fmt.Errorf("open csv %q: %w", csvPath, err)
	}
	defer f.Close()

	r := csv.NewReader(f)
	header, err := r.Read()
	if err != nil {
		return nil, fmt.Errorf("read csv header: %w", err)
	}

	colIndex := func(name string) int {
		for i, h := range header {
			if h == name {
				return i
			}
		}
		return -1
	}

	kindIdx := colIndex("kind")
	itemPathIdx := colIndex("item_path")
	statusIdx := colIndex("status")
	rationaleIdx := colIndex("rationale")

	if itemPathIdx < 0 || statusIdx < 0 {
		return nil, fmt.Errorf("csv missing required columns (item_path, status)")
	}

	out := make(map[string]specMeta)
	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("read csv row: %w", err)
		}
		if kindIdx >= 0 && kindIdx < len(rec) && rec[kindIdx] != "tap" {
			continue
		}
		if itemPathIdx >= len(rec) {
			continue
		}
		meta := specMeta{status: rec[statusIdx]}
		if rationaleIdx >= 0 && rationaleIdx < len(rec) {
			meta.rationale = rec[rationaleIdx]
		}
		out[rec[itemPathIdx]] = meta
	}
	return out, nil
}

func main() {
	var (
		repoRoot = flag.String("repo-root", ".", "path to goopg repository root")
		outPath  = flag.String("out", "docs/test-port/upstream-tap-coverage.md", "output markdown path")
		csvPath  = flag.String("csv", "docs/test-port/postgres-oracle-target-inventory.csv", "path to inventory CSV")
	)
	flag.Parse()

	root, err := filepath.Abs(*repoRoot)
	if err != nil {
		fail("resolve repo root", err)
	}

	inventory, err := loadCSV(*csvPath)
	if err != nil {
		fail("load inventory csv", err)
	}

	paths, err := collect(root)
	if err != nil {
		fail("collect tap tests", err)
	}
	rows := make([]row, 0, len(paths))
	for _, p := range paths {
		status, why := classify(p)
		if meta, ok := inventory[p]; ok && meta.status != "" {
			status = meta.status
			if meta.rationale != "" {
				why = meta.rationale
			}
		}
		rows = append(rows, row{Path: p, Status: status, Rationale: why})
	}

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fail("mkdir output dir", err)
	}
	f, err := os.Create(*outPath)
	if err != nil {
		fail("create output file", err)
	}
	defer f.Close()

	counts := map[string]int{"port": 0, "excluded": 0, "defer": 0}
	for _, r := range rows {
		counts[r.Status]++
	}

	fmt.Fprintln(f, "# Upstream TAP Coverage Classification")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "Generated by `go run ./cmd/gen-tap-coverage --repo-root . --out docs/test-port/upstream-tap-coverage.md`.")
	fmt.Fprintf(f, "Generated at: %s\n\n", time.Now().Format(time.RFC3339))
	fmt.Fprintln(f, "Scope in this file:")
	fmt.Fprintln(f, "- `postgres/src/test/recovery/t/*.pl`")
	fmt.Fprintln(f, "- `postgres/src/test/subscription/t/*.pl`")
	fmt.Fprintln(f, "- `postgres/src/bin/*/t/*.pl`")
	fmt.Fprintln(f)
	fmt.Fprintf(f, "Total tests: **%d** (port=%d, defer=%d, excluded=%d)\n\n", len(rows), counts["port"], counts["defer"], counts["excluded"])
	fmt.Fprintln(f, "| Path | Status | Rationale |")
	fmt.Fprintln(f, "| ---- | ------ | --------- |")
	for _, r := range rows {
		fmt.Fprintf(f, "| `%s` | %s | %s |\n", r.Path, r.Status, r.Rationale)
	}
}

func collect(root string) ([]string, error) {
	seen := map[string]struct{}{}
	var out []string
	add := func(abs string) {
		rel, err := filepath.Rel(root, abs)
		if err != nil {
			return
		}
		rel = filepath.ToSlash(rel)
		if _, ok := seen[rel]; ok {
			return
		}
		seen[rel] = struct{}{}
		out = append(out, rel)
	}
	walk := func(base string, pred func(string) bool) error {
		return filepath.WalkDir(base, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				return nil
			}
			if filepath.Ext(path) != ".pl" {
				return nil
			}
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return nil
			}
			rel = filepath.ToSlash(rel)
			if pred(rel) {
				add(path)
			}
			return nil
		})
	}

	recoveryDir := filepath.Join(root, "postgres", "src", "test", "recovery", "t")
	if err := walk(recoveryDir, func(rel string) bool {
		return strings.HasPrefix(rel, "postgres/src/test/recovery/t/")
	}); err != nil {
		return nil, err
	}
	subscriptionDir := filepath.Join(root, "postgres", "src", "test", "subscription", "t")
	if err := walk(subscriptionDir, func(rel string) bool {
		return strings.HasPrefix(rel, "postgres/src/test/subscription/t/")
	}); err != nil {
		return nil, err
	}
	binDir := filepath.Join(root, "postgres", "src", "bin")
	if err := walk(binDir, func(rel string) bool {
		return strings.HasPrefix(rel, "postgres/src/bin/") && strings.Contains(rel, "/t/")
	}); err != nil {
		return nil, err
	}
	sort.Strings(out)
	return out, nil
}

func classify(rel string) (status, rationale string) {
	if strings.HasPrefix(rel, "postgres/src/test/recovery/t/") {
		return "defer", "Requires replication/failover/recovery semantics not yet implemented in goopg v0."
	}
	if strings.HasPrefix(rel, "postgres/src/test/subscription/t/") {
		return "defer", "Requires logical replication/subscription semantics not yet implemented in goopg v0."
	}
	tool := binTool(rel)
	switch tool {
	case "pgbench", "psql", "pg_isready", "pg_ctl", "initdb":
		return "port", "Maps to goopg server lifecycle and SQL protocol behavior; candidate for direct Go test porting."
	case "scripts":
		return "defer", "Depends on broader SQL/catalog parity for PostgreSQL utility scripts."
	default:
		return "excluded", fmt.Sprintf("Upstream binary %q is outside goopg's current server-focused scope.", tool)
	}
}

func binTool(rel string) string {
	const prefix = "postgres/src/bin/"
	if !strings.HasPrefix(rel, prefix) {
		return "unknown"
	}
	rest := strings.TrimPrefix(rel, prefix)
	parts := strings.Split(rest, "/")
	if len(parts) == 0 || parts[0] == "" {
		return "unknown"
	}
	return parts[0]
}

func fail(where string, err error) {
	fmt.Fprintf(os.Stderr, "gen-tap-coverage: %s: %v\n", where, err)
	os.Exit(1)
}
