// Code generated by cmd/gen-information-schema-views/main.go; DO NOT EDIT.
package initdb

// informationSchemaViewSeedRels returns the 29 on-disk information_schema
// views' bootstrap pg_class row and pg_attribute descriptors, rendered from
// internal/initdb/information_schema_view_manifest.tsv (M0133-S4).
//
// Oracle: PostgreSQL 18.3, catalog version 202506291.
//
// The rows carry goopg's RelType (2249, RECORDOID) rather than upstream's
// per-view composite type, the same deliberate divergence as the pg_catalog
// corpus (M0131-S6.5); the upstream value is in each view's comment.
func informationSchemaViewSeedRels() []nailedRel {
	return []nailedRel{
		// information_schema_catalog_name — _RETURN rule OID 13296, upstream reltype 13295.
		{
			OID:      13293,
			RelName:  "information_schema_catalog_name",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 1,
			Attrs: []nailedAttr{
				{Name: "catalog_name", TypeOID: 13292, Num: 1, Len: 64},
			},
		},
		// applicable_roles — _RETURN rule OID 13305, upstream reltype 13304.
		{
			OID:      13302,
			RelName:  "applicable_roles",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 3,
			Attrs: []nailedAttr{
				{Name: "grantee", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "role_name", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "is_grantable", TypeOID: 13300, Num: 3, Len: -1},
			},
		},
		// check_constraint_routine_usage — _RETURN rule OID 13324, upstream reltype 13323.
		{
			OID:      13321,
			RelName:  "check_constraint_routine_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 6,
			Attrs: []nailedAttr{
				{Name: "constraint_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "constraint_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "constraint_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "specific_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "specific_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "specific_name", TypeOID: 13292, Num: 6, Len: 64},
			},
		},
		// column_column_usage — _RETURN rule OID 13344, upstream reltype 13343.
		{
			OID:      13341,
			RelName:  "column_column_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 5,
			Attrs: []nailedAttr{
				{Name: "table_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "column_name", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "dependent_column", TypeOID: 13292, Num: 5, Len: 64},
			},
		},
		// column_domain_usage — _RETURN rule OID 13349, upstream reltype 13348.
		{
			OID:      13346,
			RelName:  "column_domain_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 7,
			Attrs: []nailedAttr{
				{Name: "domain_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "domain_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "domain_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "table_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "column_name", TypeOID: 13292, Num: 7, Len: 64},
			},
		},
		// column_udt_usage — _RETURN rule OID 13359, upstream reltype 13358.
		{
			OID:      13356,
			RelName:  "column_udt_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 7,
			Attrs: []nailedAttr{
				{Name: "udt_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "udt_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "udt_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "table_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "column_name", TypeOID: 13292, Num: 7, Len: 64},
			},
		},
		// constraint_table_usage — _RETURN rule OID 13374, upstream reltype 13373.
		{
			OID:      13371,
			RelName:  "constraint_table_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 6,
			Attrs: []nailedAttr{
				{Name: "table_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "constraint_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "constraint_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "constraint_name", TypeOID: 13292, Num: 6, Len: 64},
			},
		},
		// domain_constraints — _RETURN rule OID 13379, upstream reltype 13378.
		{
			OID:      13376,
			RelName:  "domain_constraints",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 8,
			Attrs: []nailedAttr{
				{Name: "constraint_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "constraint_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "constraint_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "domain_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "domain_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "domain_name", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "is_deferrable", TypeOID: 13300, Num: 7, Len: -1},
				{Name: "initially_deferred", TypeOID: 13300, Num: 8, Len: -1},
			},
		},
		// domain_udt_usage — _RETURN rule OID 13384, upstream reltype 13383.
		{
			OID:      13381,
			RelName:  "domain_udt_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 6,
			Attrs: []nailedAttr{
				{Name: "udt_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "udt_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "udt_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "domain_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "domain_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "domain_name", TypeOID: 13292, Num: 6, Len: 64},
			},
		},
		// enabled_roles — _RETURN rule OID 13393, upstream reltype 13392.
		{
			OID:      13390,
			RelName:  "enabled_roles",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 1,
			Attrs: []nailedAttr{
				{Name: "role_name", TypeOID: 13292, Num: 1, Len: 64},
			},
		},
		// routine_column_usage — _RETURN rule OID 13416, upstream reltype 13415.
		{
			OID:      13413,
			RelName:  "routine_column_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 10,
			Attrs: []nailedAttr{
				{Name: "specific_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "specific_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "specific_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "routine_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "routine_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "routine_name", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "table_catalog", TypeOID: 13292, Num: 7, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 8, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 9, Len: 64},
				{Name: "column_name", TypeOID: 13292, Num: 10, Len: 64},
			},
		},
		// routine_privileges — _RETURN rule OID 13421, upstream reltype 13420.
		{
			OID:      13418,
			RelName:  "routine_privileges",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 10,
			Attrs: []nailedAttr{
				{Name: "grantor", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "grantee", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "specific_catalog", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "specific_schema", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "specific_name", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "routine_catalog", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "routine_schema", TypeOID: 13292, Num: 7, Len: 64},
				{Name: "routine_name", TypeOID: 13292, Num: 8, Len: 64},
				{Name: "privilege_type", TypeOID: 13290, Num: 9, Len: -1},
				{Name: "is_grantable", TypeOID: 13300, Num: 10, Len: -1},
			},
		},
		// routine_routine_usage — _RETURN rule OID 13430, upstream reltype 13429.
		{
			OID:      13427,
			RelName:  "routine_routine_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 6,
			Attrs: []nailedAttr{
				{Name: "specific_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "specific_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "specific_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "routine_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "routine_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "routine_name", TypeOID: 13292, Num: 6, Len: 64},
			},
		},
		// routine_sequence_usage — _RETURN rule OID 13435, upstream reltype 13434.
		{
			OID:      13432,
			RelName:  "routine_sequence_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 9,
			Attrs: []nailedAttr{
				{Name: "specific_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "specific_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "specific_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "routine_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "routine_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "routine_name", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "sequence_catalog", TypeOID: 13292, Num: 7, Len: 64},
				{Name: "sequence_schema", TypeOID: 13292, Num: 8, Len: 64},
				{Name: "sequence_name", TypeOID: 13292, Num: 9, Len: 64},
			},
		},
		// routine_table_usage — _RETURN rule OID 13440, upstream reltype 13439.
		{
			OID:      13437,
			RelName:  "routine_table_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 9,
			Attrs: []nailedAttr{
				{Name: "specific_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "specific_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "specific_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "routine_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "routine_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "routine_name", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "table_catalog", TypeOID: 13292, Num: 7, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 8, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 9, Len: 64},
			},
		},
		// schemata — _RETURN rule OID 13450, upstream reltype 13449.
		{
			OID:      13447,
			RelName:  "schemata",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 7,
			Attrs: []nailedAttr{
				{Name: "catalog_name", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "schema_name", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "schema_owner", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "default_character_set_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "default_character_set_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "default_character_set_name", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "sql_path", TypeOID: 13290, Num: 7, Len: -1},
			},
		},
		// table_constraints — _RETURN rule OID 13479, upstream reltype 13478.
		{
			OID:      13476,
			RelName:  "table_constraints",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 11,
			Attrs: []nailedAttr{
				{Name: "constraint_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "constraint_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "constraint_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "table_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "constraint_type", TypeOID: 13290, Num: 7, Len: -1},
				{Name: "is_deferrable", TypeOID: 13300, Num: 8, Len: -1},
				{Name: "initially_deferred", TypeOID: 13300, Num: 9, Len: -1},
				{Name: "enforced", TypeOID: 13300, Num: 10, Len: -1},
				{Name: "nulls_distinct", TypeOID: 13300, Num: 11, Len: -1},
			},
		},
		// table_privileges — _RETURN rule OID 13484, upstream reltype 13483.
		{
			OID:      13481,
			RelName:  "table_privileges",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 8,
			Attrs: []nailedAttr{
				{Name: "grantor", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "grantee", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "table_catalog", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "privilege_type", TypeOID: 13290, Num: 6, Len: -1},
				{Name: "is_grantable", TypeOID: 13300, Num: 7, Len: -1},
				{Name: "with_hierarchy", TypeOID: 13300, Num: 8, Len: -1},
			},
		},
		// tables — _RETURN rule OID 13493, upstream reltype 13492.
		{
			OID:      13490,
			RelName:  "tables",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 12,
			Attrs: []nailedAttr{
				{Name: "table_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "table_type", TypeOID: 13290, Num: 4, Len: -1},
				{Name: "self_referencing_column_name", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "reference_generation", TypeOID: 13290, Num: 6, Len: -1},
				{Name: "user_defined_type_catalog", TypeOID: 13292, Num: 7, Len: 64},
				{Name: "user_defined_type_schema", TypeOID: 13292, Num: 8, Len: 64},
				{Name: "user_defined_type_name", TypeOID: 13292, Num: 9, Len: 64},
				{Name: "is_insertable_into", TypeOID: 13300, Num: 10, Len: -1},
				{Name: "is_typed", TypeOID: 13300, Num: 11, Len: -1},
				{Name: "commit_action", TypeOID: 13290, Num: 12, Len: -1},
			},
		},
		// udt_privileges — _RETURN rule OID 13513, upstream reltype 13512.
		{
			OID:      13510,
			RelName:  "udt_privileges",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 7,
			Attrs: []nailedAttr{
				{Name: "grantor", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "grantee", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "udt_catalog", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "udt_schema", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "udt_name", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "privilege_type", TypeOID: 13290, Num: 6, Len: -1},
				{Name: "is_grantable", TypeOID: 13300, Num: 7, Len: -1},
			},
		},
		// user_defined_types — _RETURN rule OID 13531, upstream reltype 13530.
		{
			OID:      13528,
			RelName:  "user_defined_types",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 29,
			Attrs: []nailedAttr{
				{Name: "user_defined_type_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "user_defined_type_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "user_defined_type_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "user_defined_type_category", TypeOID: 13290, Num: 4, Len: -1},
				{Name: "is_instantiable", TypeOID: 13300, Num: 5, Len: -1},
				{Name: "is_final", TypeOID: 13300, Num: 6, Len: -1},
				{Name: "ordering_form", TypeOID: 13290, Num: 7, Len: -1},
				{Name: "ordering_category", TypeOID: 13290, Num: 8, Len: -1},
				{Name: "ordering_routine_catalog", TypeOID: 13292, Num: 9, Len: 64},
				{Name: "ordering_routine_schema", TypeOID: 13292, Num: 10, Len: 64},
				{Name: "ordering_routine_name", TypeOID: 13292, Num: 11, Len: 64},
				{Name: "reference_type", TypeOID: 13290, Num: 12, Len: -1},
				{Name: "data_type", TypeOID: 13290, Num: 13, Len: -1},
				{Name: "character_maximum_length", TypeOID: 13287, Num: 14, Len: 4},
				{Name: "character_octet_length", TypeOID: 13287, Num: 15, Len: 4},
				{Name: "character_set_catalog", TypeOID: 13292, Num: 16, Len: 64},
				{Name: "character_set_schema", TypeOID: 13292, Num: 17, Len: 64},
				{Name: "character_set_name", TypeOID: 13292, Num: 18, Len: 64},
				{Name: "collation_catalog", TypeOID: 13292, Num: 19, Len: 64},
				{Name: "collation_schema", TypeOID: 13292, Num: 20, Len: 64},
				{Name: "collation_name", TypeOID: 13292, Num: 21, Len: 64},
				{Name: "numeric_precision", TypeOID: 13287, Num: 22, Len: 4},
				{Name: "numeric_precision_radix", TypeOID: 13287, Num: 23, Len: 4},
				{Name: "numeric_scale", TypeOID: 13287, Num: 24, Len: 4},
				{Name: "datetime_precision", TypeOID: 13287, Num: 25, Len: 4},
				{Name: "interval_type", TypeOID: 13290, Num: 26, Len: -1},
				{Name: "interval_precision", TypeOID: 13287, Num: 27, Len: 4},
				{Name: "source_dtd_identifier", TypeOID: 13292, Num: 28, Len: 64},
				{Name: "ref_dtd_identifier", TypeOID: 13292, Num: 29, Len: 64},
			},
		},
		// view_column_usage — _RETURN rule OID 13536, upstream reltype 13535.
		{
			OID:      13533,
			RelName:  "view_column_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 7,
			Attrs: []nailedAttr{
				{Name: "view_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "view_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "view_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "table_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "column_name", TypeOID: 13292, Num: 7, Len: 64},
			},
		},
		// view_routine_usage — _RETURN rule OID 13541, upstream reltype 13540.
		{
			OID:      13538,
			RelName:  "view_routine_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 6,
			Attrs: []nailedAttr{
				{Name: "table_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "specific_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "specific_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "specific_name", TypeOID: 13292, Num: 6, Len: 64},
			},
		},
		// view_table_usage — _RETURN rule OID 13546, upstream reltype 13545.
		{
			OID:      13543,
			RelName:  "view_table_usage",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 6,
			Attrs: []nailedAttr{
				{Name: "view_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "view_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "view_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "table_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 6, Len: 64},
			},
		},
		// views — _RETURN rule OID 13551, upstream reltype 13550.
		{
			OID:      13548,
			RelName:  "views",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 10,
			Attrs: []nailedAttr{
				{Name: "table_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "table_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "table_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "view_definition", TypeOID: 13290, Num: 4, Len: -1},
				{Name: "check_option", TypeOID: 13290, Num: 5, Len: -1},
				{Name: "is_updatable", TypeOID: 13300, Num: 6, Len: -1},
				{Name: "is_insertable_into", TypeOID: 13300, Num: 7, Len: -1},
				{Name: "is_trigger_updatable", TypeOID: 13300, Num: 8, Len: -1},
				{Name: "is_trigger_deletable", TypeOID: 13300, Num: 9, Len: -1},
				{Name: "is_trigger_insertable_into", TypeOID: 13300, Num: 10, Len: -1},
			},
		},
		// _pg_foreign_table_columns — _RETURN rule OID 13566, upstream reltype 13565.
		{
			OID:      13563,
			RelName:  "_pg_foreign_table_columns",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 4,
			Attrs: []nailedAttr{
				{Name: "nspname", TypeOID: 19, Num: 1, Len: 64},
				{Name: "relname", TypeOID: 19, Num: 2, Len: 64},
				{Name: "attname", TypeOID: 19, Num: 3, Len: 64},
				{Name: "attfdwoptions", TypeOID: 1009, Num: 4, Len: -1},
			},
		},
		// _pg_foreign_data_wrappers — _RETURN rule OID 13575, upstream reltype 13574.
		{
			OID:      13572,
			RelName:  "_pg_foreign_data_wrappers",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 7,
			Attrs: []nailedAttr{
				{Name: "oid", TypeOID: 26, Num: 1, Len: 4},
				{Name: "fdwowner", TypeOID: 26, Num: 2, Len: 4},
				{Name: "fdwoptions", TypeOID: 1009, Num: 3, Len: -1},
				{Name: "foreign_data_wrapper_catalog", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "foreign_data_wrapper_name", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "authorization_identifier", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "foreign_data_wrapper_language", TypeOID: 13290, Num: 7, Len: -1},
			},
		},
		// _pg_foreign_servers — _RETURN rule OID 13587, upstream reltype 13586.
		{
			OID:      13584,
			RelName:  "_pg_foreign_servers",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 9,
			Attrs: []nailedAttr{
				{Name: "oid", TypeOID: 26, Num: 1, Len: 4},
				{Name: "srvoptions", TypeOID: 1009, Num: 2, Len: -1},
				{Name: "foreign_server_catalog", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "foreign_server_name", TypeOID: 13292, Num: 4, Len: 64},
				{Name: "foreign_data_wrapper_catalog", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "foreign_data_wrapper_name", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "foreign_server_type", TypeOID: 13290, Num: 7, Len: -1},
				{Name: "foreign_server_version", TypeOID: 13290, Num: 8, Len: -1},
				{Name: "authorization_identifier", TypeOID: 13292, Num: 9, Len: 64},
			},
		},
		// _pg_foreign_tables — _RETURN rule OID 13599, upstream reltype 13598.
		{
			OID:      13596,
			RelName:  "_pg_foreign_tables",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 7,
			Attrs: []nailedAttr{
				{Name: "foreign_table_catalog", TypeOID: 13292, Num: 1, Len: 64},
				{Name: "foreign_table_schema", TypeOID: 13292, Num: 2, Len: 64},
				{Name: "foreign_table_name", TypeOID: 13292, Num: 3, Len: 64},
				{Name: "ftoptions", TypeOID: 1009, Num: 4, Len: -1},
				{Name: "foreign_server_catalog", TypeOID: 13292, Num: 5, Len: 64},
				{Name: "foreign_server_name", TypeOID: 13292, Num: 6, Len: 64},
				{Name: "authorization_identifier", TypeOID: 13292, Num: 7, Len: 64},
			},
		},
	}
}

// informationSchemaViewRewriteEntries returns the 29 ON-SELECT (_RETURN)
// rules that back the on-disk information_schema views, rendered from the same
// manifest as informationSchemaViewSeedRels. Identical rule form to the
// pg_catalog corpus: _RETURN / CMD_SELECT / ALWAYS / INSTEAD, empty ev_qual.
func informationSchemaViewRewriteEntries() []pgRewriteEntry {
	return []pgRewriteEntry{
		{
			OID:       13296,
			RuleName:  "_RETURN",
			EvClass:   13293, // information_schema_catalog_name
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("information_schema_catalog_name"),
		},
		{
			OID:       13305,
			RuleName:  "_RETURN",
			EvClass:   13302, // applicable_roles
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("applicable_roles"),
		},
		{
			OID:       13324,
			RuleName:  "_RETURN",
			EvClass:   13321, // check_constraint_routine_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("check_constraint_routine_usage"),
		},
		{
			OID:       13344,
			RuleName:  "_RETURN",
			EvClass:   13341, // column_column_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("column_column_usage"),
		},
		{
			OID:       13349,
			RuleName:  "_RETURN",
			EvClass:   13346, // column_domain_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("column_domain_usage"),
		},
		{
			OID:       13359,
			RuleName:  "_RETURN",
			EvClass:   13356, // column_udt_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("column_udt_usage"),
		},
		{
			OID:       13374,
			RuleName:  "_RETURN",
			EvClass:   13371, // constraint_table_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("constraint_table_usage"),
		},
		{
			OID:       13379,
			RuleName:  "_RETURN",
			EvClass:   13376, // domain_constraints
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("domain_constraints"),
		},
		{
			OID:       13384,
			RuleName:  "_RETURN",
			EvClass:   13381, // domain_udt_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("domain_udt_usage"),
		},
		{
			OID:       13393,
			RuleName:  "_RETURN",
			EvClass:   13390, // enabled_roles
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("enabled_roles"),
		},
		{
			OID:       13416,
			RuleName:  "_RETURN",
			EvClass:   13413, // routine_column_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("routine_column_usage"),
		},
		{
			OID:       13421,
			RuleName:  "_RETURN",
			EvClass:   13418, // routine_privileges
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("routine_privileges"),
		},
		{
			OID:       13430,
			RuleName:  "_RETURN",
			EvClass:   13427, // routine_routine_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("routine_routine_usage"),
		},
		{
			OID:       13435,
			RuleName:  "_RETURN",
			EvClass:   13432, // routine_sequence_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("routine_sequence_usage"),
		},
		{
			OID:       13440,
			RuleName:  "_RETURN",
			EvClass:   13437, // routine_table_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("routine_table_usage"),
		},
		{
			OID:       13450,
			RuleName:  "_RETURN",
			EvClass:   13447, // schemata
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("schemata"),
		},
		{
			OID:       13479,
			RuleName:  "_RETURN",
			EvClass:   13476, // table_constraints
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("table_constraints"),
		},
		{
			OID:       13484,
			RuleName:  "_RETURN",
			EvClass:   13481, // table_privileges
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("table_privileges"),
		},
		{
			OID:       13493,
			RuleName:  "_RETURN",
			EvClass:   13490, // tables
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("tables"),
		},
		{
			OID:       13513,
			RuleName:  "_RETURN",
			EvClass:   13510, // udt_privileges
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("udt_privileges"),
		},
		{
			OID:       13531,
			RuleName:  "_RETURN",
			EvClass:   13528, // user_defined_types
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("user_defined_types"),
		},
		{
			OID:       13536,
			RuleName:  "_RETURN",
			EvClass:   13533, // view_column_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("view_column_usage"),
		},
		{
			OID:       13541,
			RuleName:  "_RETURN",
			EvClass:   13538, // view_routine_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("view_routine_usage"),
		},
		{
			OID:       13546,
			RuleName:  "_RETURN",
			EvClass:   13543, // view_table_usage
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("view_table_usage"),
		},
		{
			OID:       13551,
			RuleName:  "_RETURN",
			EvClass:   13548, // views
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("views"),
		},
		{
			OID:       13566,
			RuleName:  "_RETURN",
			EvClass:   13563, // _pg_foreign_table_columns
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("_pg_foreign_table_columns"),
		},
		{
			OID:       13575,
			RuleName:  "_RETURN",
			EvClass:   13572, // _pg_foreign_data_wrappers
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("_pg_foreign_data_wrappers"),
		},
		{
			OID:       13587,
			RuleName:  "_RETURN",
			EvClass:   13584, // _pg_foreign_servers
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("_pg_foreign_servers"),
		},
		{
			OID:       13599,
			RuleName:  "_RETURN",
			EvClass:   13596, // _pg_foreign_tables
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("_pg_foreign_tables"),
		},
	}
}
