// Code generated by cmd/gen-nailed-view-tables/main.go; DO NOT EDIT.
package initdb

// nailedViewSeedRels returns the 6 on-disk system views' bootstrap pg_class
// row and pg_attribute descriptors, rendered from
// internal/initdb/nailed_view_manifest.tsv (M0131-S7.4).
//
// Oracle: PostgreSQL 18.3, catalog version 202506291.
//
// The rows carry goopg's RelType (2249, RECORDOID) rather than upstream's
// per-view composite type, which goopg does not mint yet (M0131-S6.5); the
// upstream value is in each view's comment. IsShared is false for every
// system view — they are per-database relations.
func nailedViewSeedRels() []nailedRel {
	return []nailedRel{
		// pg_stat_replication — _RETURN rule OID 12234, upstream reltype 12233.
		{
			OID:      12231,
			RelName:  "pg_stat_replication",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 20,
			Attrs: []nailedAttr{
				{Name: "pid", TypeOID: 23, Num: 1, Len: 4},
				{Name: "usesysid", TypeOID: 26, Num: 2, Len: 4},
				{Name: "usename", TypeOID: 19, Num: 3, Len: 64},
				{Name: "application_name", TypeOID: 25, Num: 4, Len: -1},
				{Name: "client_addr", TypeOID: 869, Num: 5, Len: -1},
				{Name: "client_hostname", TypeOID: 25, Num: 6, Len: -1},
				{Name: "client_port", TypeOID: 23, Num: 7, Len: 4},
				{Name: "backend_start", TypeOID: 1184, Num: 8, Len: 8},
				{Name: "backend_xmin", TypeOID: 28, Num: 9, Len: 4},
				{Name: "state", TypeOID: 25, Num: 10, Len: -1},
				{Name: "sent_lsn", TypeOID: 3220, Num: 11, Len: 8},
				{Name: "write_lsn", TypeOID: 3220, Num: 12, Len: 8},
				{Name: "flush_lsn", TypeOID: 3220, Num: 13, Len: 8},
				{Name: "replay_lsn", TypeOID: 3220, Num: 14, Len: 8},
				{Name: "write_lag", TypeOID: 1186, Num: 15, Len: 16},
				{Name: "flush_lag", TypeOID: 1186, Num: 16, Len: 16},
				{Name: "replay_lag", TypeOID: 1186, Num: 17, Len: 16},
				{Name: "sync_priority", TypeOID: 23, Num: 18, Len: 4},
				{Name: "sync_state", TypeOID: 25, Num: 19, Len: -1},
				{Name: "reply_time", TypeOID: 1184, Num: 20, Len: 8},
			},
		},
		// pg_stat_wal_receiver — _RETURN rule OID 12243, upstream reltype 12242.
		{
			OID:      12240,
			RelName:  "pg_stat_wal_receiver",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 15,
			Attrs: []nailedAttr{
				{Name: "pid", TypeOID: 23, Num: 1, Len: 4},
				{Name: "status", TypeOID: 25, Num: 2, Len: -1},
				{Name: "receive_start_lsn", TypeOID: 3220, Num: 3, Len: 8},
				{Name: "receive_start_tli", TypeOID: 23, Num: 4, Len: 4},
				{Name: "written_lsn", TypeOID: 3220, Num: 5, Len: 8},
				{Name: "flushed_lsn", TypeOID: 3220, Num: 6, Len: 8},
				{Name: "received_tli", TypeOID: 23, Num: 7, Len: 4},
				{Name: "last_msg_send_time", TypeOID: 1184, Num: 8, Len: 8},
				{Name: "last_msg_receipt_time", TypeOID: 1184, Num: 9, Len: 8},
				{Name: "latest_end_lsn", TypeOID: 3220, Num: 10, Len: 8},
				{Name: "latest_end_time", TypeOID: 1184, Num: 11, Len: 8},
				{Name: "slot_name", TypeOID: 25, Num: 12, Len: -1},
				{Name: "sender_host", TypeOID: 25, Num: 13, Len: -1},
				{Name: "sender_port", TypeOID: 23, Num: 14, Len: 4},
				{Name: "conninfo", TypeOID: 25, Num: 15, Len: -1},
			},
		},
		// pg_stat_recovery_prefetch — _RETURN rule OID 12247, upstream reltype 12246.
		{
			OID:      12244,
			RelName:  "pg_stat_recovery_prefetch",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 10,
			Attrs: []nailedAttr{
				{Name: "stats_reset", TypeOID: 1184, Num: 1, Len: 8},
				{Name: "prefetch", TypeOID: 20, Num: 2, Len: 8},
				{Name: "hit", TypeOID: 20, Num: 3, Len: 8},
				{Name: "skip_init", TypeOID: 20, Num: 4, Len: 8},
				{Name: "skip_new", TypeOID: 20, Num: 5, Len: 8},
				{Name: "skip_fpw", TypeOID: 20, Num: 6, Len: 8},
				{Name: "skip_rep", TypeOID: 20, Num: 7, Len: 8},
				{Name: "wal_distance", TypeOID: 23, Num: 8, Len: 4},
				{Name: "block_distance", TypeOID: 23, Num: 9, Len: 4},
				{Name: "io_depth", TypeOID: 23, Num: 10, Len: 4},
			},
		},
		// pg_stat_subscription — _RETURN rule OID 12251, upstream reltype 12250.
		{
			OID:      12248,
			RelName:  "pg_stat_subscription",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 11,
			Attrs: []nailedAttr{
				{Name: "subid", TypeOID: 26, Num: 1, Len: 4},
				{Name: "subname", TypeOID: 19, Num: 2, Len: 64},
				{Name: "worker_type", TypeOID: 25, Num: 3, Len: -1},
				{Name: "pid", TypeOID: 23, Num: 4, Len: 4},
				{Name: "leader_pid", TypeOID: 23, Num: 5, Len: 4},
				{Name: "relid", TypeOID: 26, Num: 6, Len: 4},
				{Name: "received_lsn", TypeOID: 3220, Num: 7, Len: 8},
				{Name: "last_msg_send_time", TypeOID: 1184, Num: 8, Len: 8},
				{Name: "last_msg_receipt_time", TypeOID: 1184, Num: 9, Len: 8},
				{Name: "latest_end_lsn", TypeOID: 3220, Num: 10, Len: 8},
				{Name: "latest_end_time", TypeOID: 1184, Num: 11, Len: 8},
			},
		},
		// pg_replication_slots — _RETURN rule OID 12264, upstream reltype 12263.
		{
			OID:      12261,
			RelName:  "pg_replication_slots",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 21,
			Attrs: []nailedAttr{
				{Name: "slot_name", TypeOID: 19, Num: 1, Len: 64},
				{Name: "plugin", TypeOID: 19, Num: 2, Len: 64},
				{Name: "slot_type", TypeOID: 25, Num: 3, Len: -1},
				{Name: "datoid", TypeOID: 26, Num: 4, Len: 4},
				{Name: "database", TypeOID: 19, Num: 5, Len: 64},
				{Name: "temporary", TypeOID: 16, Num: 6, Len: 1},
				{Name: "active", TypeOID: 16, Num: 7, Len: 1},
				{Name: "active_pid", TypeOID: 23, Num: 8, Len: 4},
				{Name: "xmin", TypeOID: 28, Num: 9, Len: 4},
				{Name: "catalog_xmin", TypeOID: 28, Num: 10, Len: 4},
				{Name: "restart_lsn", TypeOID: 3220, Num: 11, Len: 8},
				{Name: "confirmed_flush_lsn", TypeOID: 3220, Num: 12, Len: 8},
				{Name: "wal_status", TypeOID: 25, Num: 13, Len: -1},
				{Name: "safe_wal_size", TypeOID: 20, Num: 14, Len: 8},
				{Name: "two_phase", TypeOID: 16, Num: 15, Len: 1},
				{Name: "two_phase_at", TypeOID: 3220, Num: 16, Len: 8},
				{Name: "inactive_since", TypeOID: 1184, Num: 17, Len: 8},
				{Name: "conflicting", TypeOID: 16, Num: 18, Len: 1},
				{Name: "invalidation_reason", TypeOID: 25, Num: 19, Len: -1},
				{Name: "failover", TypeOID: 16, Num: 20, Len: 1},
				{Name: "synced", TypeOID: 16, Num: 21, Len: 1},
			},
		},
		// pg_stat_replication_slots — _RETURN rule OID 12269, upstream reltype 12268.
		{
			OID:      12266,
			RelName:  "pg_stat_replication_slots",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 10,
			Attrs: []nailedAttr{
				{Name: "slot_name", TypeOID: 25, Num: 1, Len: -1},
				{Name: "spill_txns", TypeOID: 20, Num: 2, Len: 8},
				{Name: "spill_count", TypeOID: 20, Num: 3, Len: 8},
				{Name: "spill_bytes", TypeOID: 20, Num: 4, Len: 8},
				{Name: "stream_txns", TypeOID: 20, Num: 5, Len: 8},
				{Name: "stream_count", TypeOID: 20, Num: 6, Len: 8},
				{Name: "stream_bytes", TypeOID: 20, Num: 7, Len: 8},
				{Name: "total_txns", TypeOID: 20, Num: 8, Len: 8},
				{Name: "total_bytes", TypeOID: 20, Num: 9, Len: 8},
				{Name: "stats_reset", TypeOID: 1184, Num: 10, Len: 8},
			},
		},
	}
}
