// Code generated by cmd/gen-nailed-view-tables/main.go; DO NOT EDIT.
package initdb

// nailedViewSeedRels returns the 33 on-disk system views' bootstrap pg_class
// row and pg_attribute descriptors, rendered from
// internal/initdb/nailed_view_manifest.tsv (M0131-S7.4).
//
// Oracle: PostgreSQL 18.3, catalog version 202506291.
//
// The rows carry goopg's RelType (2249, RECORDOID) rather than upstream's
// per-view composite type, which goopg does not mint yet (M0131-S6.5); the
// upstream value is in each view's comment. IsShared is false for every
// system view — they are per-database relations.
func nailedViewSeedRels() []nailedRel {
	return []nailedRel{
		// pg_views — _RETURN rule OID 12031, upstream reltype 12030.
		{
			OID:      12028,
			RelName:  "pg_views",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 4,
			Attrs: []nailedAttr{
				{Name: "schemaname", TypeOID: 19, Num: 1, Len: 64},
				{Name: "viewname", TypeOID: 19, Num: 2, Len: 64},
				{Name: "viewowner", TypeOID: 19, Num: 3, Len: 64},
				{Name: "definition", TypeOID: 25, Num: 4, Len: -1},
			},
		},
		// pg_tables — _RETURN rule OID 12036, upstream reltype 12035.
		{
			OID:      12033,
			RelName:  "pg_tables",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 8,
			Attrs: []nailedAttr{
				{Name: "schemaname", TypeOID: 19, Num: 1, Len: 64},
				{Name: "tablename", TypeOID: 19, Num: 2, Len: 64},
				{Name: "tableowner", TypeOID: 19, Num: 3, Len: 64},
				{Name: "tablespace", TypeOID: 19, Num: 4, Len: 64},
				{Name: "hasindexes", TypeOID: 16, Num: 5, Len: 1},
				{Name: "hasrules", TypeOID: 16, Num: 6, Len: 1},
				{Name: "hastriggers", TypeOID: 16, Num: 7, Len: 1},
				{Name: "rowsecurity", TypeOID: 16, Num: 8, Len: 1},
			},
		},
		// pg_matviews — _RETURN rule OID 12041, upstream reltype 12040.
		{
			OID:      12038,
			RelName:  "pg_matviews",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 7,
			Attrs: []nailedAttr{
				{Name: "schemaname", TypeOID: 19, Num: 1, Len: 64},
				{Name: "matviewname", TypeOID: 19, Num: 2, Len: 64},
				{Name: "matviewowner", TypeOID: 19, Num: 3, Len: 64},
				{Name: "tablespace", TypeOID: 19, Num: 4, Len: 64},
				{Name: "hasindexes", TypeOID: 16, Num: 5, Len: 1},
				{Name: "ispopulated", TypeOID: 16, Num: 6, Len: 1},
				{Name: "definition", TypeOID: 25, Num: 7, Len: -1},
			},
		},
		// pg_locks — _RETURN rule OID 12076, upstream reltype 12075.
		{
			OID:      12073,
			RelName:  "pg_locks",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 16,
			Attrs: []nailedAttr{
				{Name: "locktype", TypeOID: 25, Num: 1, Len: -1},
				{Name: "database", TypeOID: 26, Num: 2, Len: 4},
				{Name: "relation", TypeOID: 26, Num: 3, Len: 4},
				{Name: "page", TypeOID: 23, Num: 4, Len: 4},
				{Name: "tuple", TypeOID: 21, Num: 5, Len: 2},
				{Name: "virtualxid", TypeOID: 25, Num: 6, Len: -1},
				{Name: "transactionid", TypeOID: 28, Num: 7, Len: 4},
				{Name: "classid", TypeOID: 26, Num: 8, Len: 4},
				{Name: "objid", TypeOID: 26, Num: 9, Len: 4},
				{Name: "objsubid", TypeOID: 21, Num: 10, Len: 2},
				{Name: "virtualtransaction", TypeOID: 25, Num: 11, Len: -1},
				{Name: "pid", TypeOID: 23, Num: 12, Len: 4},
				{Name: "mode", TypeOID: 25, Num: 13, Len: -1},
				{Name: "granted", TypeOID: 16, Num: 14, Len: 1},
				{Name: "fastpath", TypeOID: 16, Num: 15, Len: 1},
				{Name: "waitstart", TypeOID: 1184, Num: 16, Len: 8},
			},
		},
		// pg_cursors — _RETURN rule OID 12080, upstream reltype 12079.
		{
			OID:      12077,
			RelName:  "pg_cursors",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 6,
			Attrs: []nailedAttr{
				{Name: "name", TypeOID: 25, Num: 1, Len: -1},
				{Name: "statement", TypeOID: 25, Num: 2, Len: -1},
				{Name: "is_holdable", TypeOID: 16, Num: 3, Len: 1},
				{Name: "is_binary", TypeOID: 16, Num: 4, Len: 1},
				{Name: "is_scrollable", TypeOID: 16, Num: 5, Len: 1},
				{Name: "creation_time", TypeOID: 1184, Num: 6, Len: 8},
			},
		},
		// pg_prepared_statements — _RETURN rule OID 12098, upstream reltype 12097.
		{
			OID:      12095,
			RelName:  "pg_prepared_statements",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 8,
			Attrs: []nailedAttr{
				{Name: "name", TypeOID: 25, Num: 1, Len: -1},
				{Name: "statement", TypeOID: 25, Num: 2, Len: -1},
				{Name: "prepare_time", TypeOID: 1184, Num: 3, Len: 8},
				{Name: "parameter_types", TypeOID: 2211, Num: 4, Len: -1},
				{Name: "result_types", TypeOID: 2211, Num: 5, Len: -1},
				{Name: "from_sql", TypeOID: 16, Num: 6, Len: 1},
				{Name: "generic_plans", TypeOID: 20, Num: 7, Len: 8},
				{Name: "custom_plans", TypeOID: 20, Num: 8, Len: 8},
			},
		},
		// pg_settings — _RETURN rule OID 12107, upstream reltype 12106.
		{
			OID:      12104,
			RelName:  "pg_settings",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 17,
			Attrs: []nailedAttr{
				{Name: "name", TypeOID: 25, Num: 1, Len: -1},
				{Name: "setting", TypeOID: 25, Num: 2, Len: -1},
				{Name: "unit", TypeOID: 25, Num: 3, Len: -1},
				{Name: "category", TypeOID: 25, Num: 4, Len: -1},
				{Name: "short_desc", TypeOID: 25, Num: 5, Len: -1},
				{Name: "extra_desc", TypeOID: 25, Num: 6, Len: -1},
				{Name: "context", TypeOID: 25, Num: 7, Len: -1},
				{Name: "vartype", TypeOID: 25, Num: 8, Len: -1},
				{Name: "source", TypeOID: 25, Num: 9, Len: -1},
				{Name: "min_val", TypeOID: 25, Num: 10, Len: -1},
				{Name: "max_val", TypeOID: 25, Num: 11, Len: -1},
				{Name: "enumvals", TypeOID: 1009, Num: 12, Len: -1},
				{Name: "boot_val", TypeOID: 25, Num: 13, Len: -1},
				{Name: "reset_val", TypeOID: 25, Num: 14, Len: -1},
				{Name: "sourcefile", TypeOID: 25, Num: 15, Len: -1},
				{Name: "sourceline", TypeOID: 23, Num: 16, Len: 4},
				{Name: "pending_restart", TypeOID: 16, Num: 17, Len: 1},
			},
		},
		// pg_file_settings — _RETURN rule OID 12113, upstream reltype 12112.
		{
			OID:      12110,
			RelName:  "pg_file_settings",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 7,
			Attrs: []nailedAttr{
				{Name: "sourcefile", TypeOID: 25, Num: 1, Len: -1},
				{Name: "sourceline", TypeOID: 23, Num: 2, Len: 4},
				{Name: "seqno", TypeOID: 23, Num: 3, Len: 4},
				{Name: "name", TypeOID: 25, Num: 4, Len: -1},
				{Name: "setting", TypeOID: 25, Num: 5, Len: -1},
				{Name: "applied", TypeOID: 16, Num: 6, Len: 1},
				{Name: "error", TypeOID: 25, Num: 7, Len: -1},
			},
		},
		// pg_hba_file_rules — _RETURN rule OID 12117, upstream reltype 12116.
		{
			OID:      12114,
			RelName:  "pg_hba_file_rules",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 11,
			Attrs: []nailedAttr{
				{Name: "rule_number", TypeOID: 23, Num: 1, Len: 4},
				{Name: "file_name", TypeOID: 25, Num: 2, Len: -1},
				{Name: "line_number", TypeOID: 23, Num: 3, Len: 4},
				{Name: "type", TypeOID: 25, Num: 4, Len: -1},
				{Name: "database", TypeOID: 1009, Num: 5, Len: -1},
				{Name: "user_name", TypeOID: 1009, Num: 6, Len: -1},
				{Name: "address", TypeOID: 25, Num: 7, Len: -1},
				{Name: "netmask", TypeOID: 25, Num: 8, Len: -1},
				{Name: "auth_method", TypeOID: 25, Num: 9, Len: -1},
				{Name: "options", TypeOID: 1009, Num: 10, Len: -1},
				{Name: "error", TypeOID: 25, Num: 11, Len: -1},
			},
		},
		// pg_ident_file_mappings — _RETURN rule OID 12121, upstream reltype 12120.
		{
			OID:      12118,
			RelName:  "pg_ident_file_mappings",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 7,
			Attrs: []nailedAttr{
				{Name: "map_number", TypeOID: 23, Num: 1, Len: 4},
				{Name: "file_name", TypeOID: 25, Num: 2, Len: -1},
				{Name: "line_number", TypeOID: 23, Num: 3, Len: 4},
				{Name: "map_name", TypeOID: 25, Num: 4, Len: -1},
				{Name: "sys_name", TypeOID: 25, Num: 5, Len: -1},
				{Name: "pg_username", TypeOID: 25, Num: 6, Len: -1},
				{Name: "error", TypeOID: 25, Num: 7, Len: -1},
			},
		},
		// pg_timezone_names — _RETURN rule OID 12129, upstream reltype 12128.
		{
			OID:      12126,
			RelName:  "pg_timezone_names",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 4,
			Attrs: []nailedAttr{
				{Name: "name", TypeOID: 25, Num: 1, Len: -1},
				{Name: "abbrev", TypeOID: 25, Num: 2, Len: -1},
				{Name: "utc_offset", TypeOID: 1186, Num: 3, Len: 16},
				{Name: "is_dst", TypeOID: 16, Num: 4, Len: 1},
			},
		},
		// pg_config — _RETURN rule OID 12133, upstream reltype 12132.
		{
			OID:      12130,
			RelName:  "pg_config",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 2,
			Attrs: []nailedAttr{
				{Name: "name", TypeOID: 25, Num: 1, Len: -1},
				{Name: "setting", TypeOID: 25, Num: 2, Len: -1},
			},
		},
		// pg_shmem_allocations — _RETURN rule OID 12137, upstream reltype 12136.
		{
			OID:      12134,
			RelName:  "pg_shmem_allocations",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 4,
			Attrs: []nailedAttr{
				{Name: "name", TypeOID: 25, Num: 1, Len: -1},
				{Name: "off", TypeOID: 20, Num: 2, Len: 8},
				{Name: "size", TypeOID: 20, Num: 3, Len: 8},
				{Name: "allocated_size", TypeOID: 20, Num: 4, Len: 8},
			},
		},
		// pg_shmem_allocations_numa — _RETURN rule OID 12141, upstream reltype 12140.
		{
			OID:      12138,
			RelName:  "pg_shmem_allocations_numa",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 3,
			Attrs: []nailedAttr{
				{Name: "name", TypeOID: 25, Num: 1, Len: -1},
				{Name: "numa_node", TypeOID: 23, Num: 2, Len: 4},
				{Name: "size", TypeOID: 20, Num: 3, Len: 8},
			},
		},
		// pg_backend_memory_contexts — _RETURN rule OID 12145, upstream reltype 12144.
		{
			OID:      12142,
			RelName:  "pg_backend_memory_contexts",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 10,
			Attrs: []nailedAttr{
				{Name: "name", TypeOID: 25, Num: 1, Len: -1},
				{Name: "ident", TypeOID: 25, Num: 2, Len: -1},
				{Name: "type", TypeOID: 25, Num: 3, Len: -1},
				{Name: "level", TypeOID: 23, Num: 4, Len: 4},
				{Name: "path", TypeOID: 1007, Num: 5, Len: -1},
				{Name: "total_bytes", TypeOID: 20, Num: 6, Len: 8},
				{Name: "total_nblocks", TypeOID: 20, Num: 7, Len: 8},
				{Name: "free_bytes", TypeOID: 20, Num: 8, Len: 8},
				{Name: "free_chunks", TypeOID: 20, Num: 9, Len: 8},
				{Name: "used_bytes", TypeOID: 20, Num: 10, Len: 8},
			},
		},
		// pg_stat_replication — _RETURN rule OID 12234, upstream reltype 12233.
		{
			OID:      12231,
			RelName:  "pg_stat_replication",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 20,
			Attrs: []nailedAttr{
				{Name: "pid", TypeOID: 23, Num: 1, Len: 4},
				{Name: "usesysid", TypeOID: 26, Num: 2, Len: 4},
				{Name: "usename", TypeOID: 19, Num: 3, Len: 64},
				{Name: "application_name", TypeOID: 25, Num: 4, Len: -1},
				{Name: "client_addr", TypeOID: 869, Num: 5, Len: -1},
				{Name: "client_hostname", TypeOID: 25, Num: 6, Len: -1},
				{Name: "client_port", TypeOID: 23, Num: 7, Len: 4},
				{Name: "backend_start", TypeOID: 1184, Num: 8, Len: 8},
				{Name: "backend_xmin", TypeOID: 28, Num: 9, Len: 4},
				{Name: "state", TypeOID: 25, Num: 10, Len: -1},
				{Name: "sent_lsn", TypeOID: 3220, Num: 11, Len: 8},
				{Name: "write_lsn", TypeOID: 3220, Num: 12, Len: 8},
				{Name: "flush_lsn", TypeOID: 3220, Num: 13, Len: 8},
				{Name: "replay_lsn", TypeOID: 3220, Num: 14, Len: 8},
				{Name: "write_lag", TypeOID: 1186, Num: 15, Len: 16},
				{Name: "flush_lag", TypeOID: 1186, Num: 16, Len: 16},
				{Name: "replay_lag", TypeOID: 1186, Num: 17, Len: 16},
				{Name: "sync_priority", TypeOID: 23, Num: 18, Len: 4},
				{Name: "sync_state", TypeOID: 25, Num: 19, Len: -1},
				{Name: "reply_time", TypeOID: 1184, Num: 20, Len: 8},
			},
		},
		// pg_stat_slru — _RETURN rule OID 12239, upstream reltype 12238.
		{
			OID:      12236,
			RelName:  "pg_stat_slru",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 9,
			Attrs: []nailedAttr{
				{Name: "name", TypeOID: 25, Num: 1, Len: -1},
				{Name: "blks_zeroed", TypeOID: 20, Num: 2, Len: 8},
				{Name: "blks_hit", TypeOID: 20, Num: 3, Len: 8},
				{Name: "blks_read", TypeOID: 20, Num: 4, Len: 8},
				{Name: "blks_written", TypeOID: 20, Num: 5, Len: 8},
				{Name: "blks_exists", TypeOID: 20, Num: 6, Len: 8},
				{Name: "flushes", TypeOID: 20, Num: 7, Len: 8},
				{Name: "truncates", TypeOID: 20, Num: 8, Len: 8},
				{Name: "stats_reset", TypeOID: 1184, Num: 9, Len: 8},
			},
		},
		// pg_stat_wal_receiver — _RETURN rule OID 12243, upstream reltype 12242.
		{
			OID:      12240,
			RelName:  "pg_stat_wal_receiver",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 15,
			Attrs: []nailedAttr{
				{Name: "pid", TypeOID: 23, Num: 1, Len: 4},
				{Name: "status", TypeOID: 25, Num: 2, Len: -1},
				{Name: "receive_start_lsn", TypeOID: 3220, Num: 3, Len: 8},
				{Name: "receive_start_tli", TypeOID: 23, Num: 4, Len: 4},
				{Name: "written_lsn", TypeOID: 3220, Num: 5, Len: 8},
				{Name: "flushed_lsn", TypeOID: 3220, Num: 6, Len: 8},
				{Name: "received_tli", TypeOID: 23, Num: 7, Len: 4},
				{Name: "last_msg_send_time", TypeOID: 1184, Num: 8, Len: 8},
				{Name: "last_msg_receipt_time", TypeOID: 1184, Num: 9, Len: 8},
				{Name: "latest_end_lsn", TypeOID: 3220, Num: 10, Len: 8},
				{Name: "latest_end_time", TypeOID: 1184, Num: 11, Len: 8},
				{Name: "slot_name", TypeOID: 25, Num: 12, Len: -1},
				{Name: "sender_host", TypeOID: 25, Num: 13, Len: -1},
				{Name: "sender_port", TypeOID: 23, Num: 14, Len: 4},
				{Name: "conninfo", TypeOID: 25, Num: 15, Len: -1},
			},
		},
		// pg_stat_recovery_prefetch — _RETURN rule OID 12247, upstream reltype 12246.
		{
			OID:      12244,
			RelName:  "pg_stat_recovery_prefetch",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 10,
			Attrs: []nailedAttr{
				{Name: "stats_reset", TypeOID: 1184, Num: 1, Len: 8},
				{Name: "prefetch", TypeOID: 20, Num: 2, Len: 8},
				{Name: "hit", TypeOID: 20, Num: 3, Len: 8},
				{Name: "skip_init", TypeOID: 20, Num: 4, Len: 8},
				{Name: "skip_new", TypeOID: 20, Num: 5, Len: 8},
				{Name: "skip_fpw", TypeOID: 20, Num: 6, Len: 8},
				{Name: "skip_rep", TypeOID: 20, Num: 7, Len: 8},
				{Name: "wal_distance", TypeOID: 23, Num: 8, Len: 4},
				{Name: "block_distance", TypeOID: 23, Num: 9, Len: 4},
				{Name: "io_depth", TypeOID: 23, Num: 10, Len: 4},
			},
		},
		// pg_stat_subscription — _RETURN rule OID 12251, upstream reltype 12250.
		{
			OID:      12248,
			RelName:  "pg_stat_subscription",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 11,
			Attrs: []nailedAttr{
				{Name: "subid", TypeOID: 26, Num: 1, Len: 4},
				{Name: "subname", TypeOID: 19, Num: 2, Len: 64},
				{Name: "worker_type", TypeOID: 25, Num: 3, Len: -1},
				{Name: "pid", TypeOID: 23, Num: 4, Len: 4},
				{Name: "leader_pid", TypeOID: 23, Num: 5, Len: 4},
				{Name: "relid", TypeOID: 26, Num: 6, Len: 4},
				{Name: "received_lsn", TypeOID: 3220, Num: 7, Len: 8},
				{Name: "last_msg_send_time", TypeOID: 1184, Num: 8, Len: 8},
				{Name: "last_msg_receipt_time", TypeOID: 1184, Num: 9, Len: 8},
				{Name: "latest_end_lsn", TypeOID: 3220, Num: 10, Len: 8},
				{Name: "latest_end_time", TypeOID: 1184, Num: 11, Len: 8},
			},
		},
		// pg_stat_ssl — _RETURN rule OID 12256, upstream reltype 12255.
		{
			OID:      12253,
			RelName:  "pg_stat_ssl",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 8,
			Attrs: []nailedAttr{
				{Name: "pid", TypeOID: 23, Num: 1, Len: 4},
				{Name: "ssl", TypeOID: 16, Num: 2, Len: 1},
				{Name: "version", TypeOID: 25, Num: 3, Len: -1},
				{Name: "cipher", TypeOID: 25, Num: 4, Len: -1},
				{Name: "bits", TypeOID: 23, Num: 5, Len: 4},
				{Name: "client_dn", TypeOID: 25, Num: 6, Len: -1},
				{Name: "client_serial", TypeOID: 1700, Num: 7, Len: -1},
				{Name: "issuer_dn", TypeOID: 25, Num: 8, Len: -1},
			},
		},
		// pg_stat_gssapi — _RETURN rule OID 12260, upstream reltype 12259.
		{
			OID:      12257,
			RelName:  "pg_stat_gssapi",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 5,
			Attrs: []nailedAttr{
				{Name: "pid", TypeOID: 23, Num: 1, Len: 4},
				{Name: "gss_authenticated", TypeOID: 16, Num: 2, Len: 1},
				{Name: "principal", TypeOID: 25, Num: 3, Len: -1},
				{Name: "encrypted", TypeOID: 16, Num: 4, Len: 1},
				{Name: "credentials_delegated", TypeOID: 16, Num: 5, Len: 1},
			},
		},
		// pg_replication_slots — _RETURN rule OID 12264, upstream reltype 12263.
		{
			OID:      12261,
			RelName:  "pg_replication_slots",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 21,
			Attrs: []nailedAttr{
				{Name: "slot_name", TypeOID: 19, Num: 1, Len: 64},
				{Name: "plugin", TypeOID: 19, Num: 2, Len: 64},
				{Name: "slot_type", TypeOID: 25, Num: 3, Len: -1},
				{Name: "datoid", TypeOID: 26, Num: 4, Len: 4},
				{Name: "database", TypeOID: 19, Num: 5, Len: 64},
				{Name: "temporary", TypeOID: 16, Num: 6, Len: 1},
				{Name: "active", TypeOID: 16, Num: 7, Len: 1},
				{Name: "active_pid", TypeOID: 23, Num: 8, Len: 4},
				{Name: "xmin", TypeOID: 28, Num: 9, Len: 4},
				{Name: "catalog_xmin", TypeOID: 28, Num: 10, Len: 4},
				{Name: "restart_lsn", TypeOID: 3220, Num: 11, Len: 8},
				{Name: "confirmed_flush_lsn", TypeOID: 3220, Num: 12, Len: 8},
				{Name: "wal_status", TypeOID: 25, Num: 13, Len: -1},
				{Name: "safe_wal_size", TypeOID: 20, Num: 14, Len: 8},
				{Name: "two_phase", TypeOID: 16, Num: 15, Len: 1},
				{Name: "two_phase_at", TypeOID: 3220, Num: 16, Len: 8},
				{Name: "inactive_since", TypeOID: 1184, Num: 17, Len: 8},
				{Name: "conflicting", TypeOID: 16, Num: 18, Len: 1},
				{Name: "invalidation_reason", TypeOID: 25, Num: 19, Len: -1},
				{Name: "failover", TypeOID: 16, Num: 20, Len: 1},
				{Name: "synced", TypeOID: 16, Num: 21, Len: 1},
			},
		},
		// pg_stat_replication_slots — _RETURN rule OID 12269, upstream reltype 12268.
		{
			OID:      12266,
			RelName:  "pg_stat_replication_slots",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 10,
			Attrs: []nailedAttr{
				{Name: "slot_name", TypeOID: 25, Num: 1, Len: -1},
				{Name: "spill_txns", TypeOID: 20, Num: 2, Len: 8},
				{Name: "spill_count", TypeOID: 20, Num: 3, Len: 8},
				{Name: "spill_bytes", TypeOID: 20, Num: 4, Len: 8},
				{Name: "stream_txns", TypeOID: 20, Num: 5, Len: 8},
				{Name: "stream_count", TypeOID: 20, Num: 6, Len: 8},
				{Name: "stream_bytes", TypeOID: 20, Num: 7, Len: 8},
				{Name: "total_txns", TypeOID: 20, Num: 8, Len: 8},
				{Name: "total_bytes", TypeOID: 20, Num: 9, Len: 8},
				{Name: "stats_reset", TypeOID: 1184, Num: 10, Len: 8},
			},
		},
		// pg_stat_archiver — _RETURN rule OID 12292, upstream reltype 12291.
		{
			OID:      12289,
			RelName:  "pg_stat_archiver",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 7,
			Attrs: []nailedAttr{
				{Name: "archived_count", TypeOID: 20, Num: 1, Len: 8},
				{Name: "last_archived_wal", TypeOID: 25, Num: 2, Len: -1},
				{Name: "last_archived_time", TypeOID: 1184, Num: 3, Len: 8},
				{Name: "failed_count", TypeOID: 20, Num: 4, Len: 8},
				{Name: "last_failed_wal", TypeOID: 25, Num: 5, Len: -1},
				{Name: "last_failed_time", TypeOID: 1184, Num: 6, Len: 8},
				{Name: "stats_reset", TypeOID: 1184, Num: 7, Len: 8},
			},
		},
		// pg_stat_bgwriter — _RETURN rule OID 12296, upstream reltype 12295.
		{
			OID:      12293,
			RelName:  "pg_stat_bgwriter",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 4,
			Attrs: []nailedAttr{
				{Name: "buffers_clean", TypeOID: 20, Num: 1, Len: 8},
				{Name: "maxwritten_clean", TypeOID: 20, Num: 2, Len: 8},
				{Name: "buffers_alloc", TypeOID: 20, Num: 3, Len: 8},
				{Name: "stats_reset", TypeOID: 1184, Num: 4, Len: 8},
			},
		},
		// pg_stat_checkpointer — _RETURN rule OID 12300, upstream reltype 12299.
		{
			OID:      12297,
			RelName:  "pg_stat_checkpointer",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 11,
			Attrs: []nailedAttr{
				{Name: "num_timed", TypeOID: 20, Num: 1, Len: 8},
				{Name: "num_requested", TypeOID: 20, Num: 2, Len: 8},
				{Name: "num_done", TypeOID: 20, Num: 3, Len: 8},
				{Name: "restartpoints_timed", TypeOID: 20, Num: 4, Len: 8},
				{Name: "restartpoints_req", TypeOID: 20, Num: 5, Len: 8},
				{Name: "restartpoints_done", TypeOID: 20, Num: 6, Len: 8},
				{Name: "write_time", TypeOID: 701, Num: 7, Len: 8},
				{Name: "sync_time", TypeOID: 701, Num: 8, Len: 8},
				{Name: "buffers_written", TypeOID: 20, Num: 9, Len: 8},
				{Name: "slru_written", TypeOID: 20, Num: 10, Len: 8},
				{Name: "stats_reset", TypeOID: 1184, Num: 11, Len: 8},
			},
		},
		// pg_stat_io — _RETURN rule OID 12304, upstream reltype 12303.
		{
			OID:      12301,
			RelName:  "pg_stat_io",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 20,
			Attrs: []nailedAttr{
				{Name: "backend_type", TypeOID: 25, Num: 1, Len: -1},
				{Name: "object", TypeOID: 25, Num: 2, Len: -1},
				{Name: "context", TypeOID: 25, Num: 3, Len: -1},
				{Name: "reads", TypeOID: 20, Num: 4, Len: 8},
				{Name: "read_bytes", TypeOID: 1700, Num: 5, Len: -1},
				{Name: "read_time", TypeOID: 701, Num: 6, Len: 8},
				{Name: "writes", TypeOID: 20, Num: 7, Len: 8},
				{Name: "write_bytes", TypeOID: 1700, Num: 8, Len: -1},
				{Name: "write_time", TypeOID: 701, Num: 9, Len: 8},
				{Name: "writebacks", TypeOID: 20, Num: 10, Len: 8},
				{Name: "writeback_time", TypeOID: 701, Num: 11, Len: 8},
				{Name: "extends", TypeOID: 20, Num: 12, Len: 8},
				{Name: "extend_bytes", TypeOID: 1700, Num: 13, Len: -1},
				{Name: "extend_time", TypeOID: 701, Num: 14, Len: 8},
				{Name: "hits", TypeOID: 20, Num: 15, Len: 8},
				{Name: "evictions", TypeOID: 20, Num: 16, Len: 8},
				{Name: "reuses", TypeOID: 20, Num: 17, Len: 8},
				{Name: "fsyncs", TypeOID: 20, Num: 18, Len: 8},
				{Name: "fsync_time", TypeOID: 701, Num: 19, Len: 8},
				{Name: "stats_reset", TypeOID: 1184, Num: 20, Len: 8},
			},
		},
		// pg_stat_wal — _RETURN rule OID 12308, upstream reltype 12307.
		{
			OID:      12305,
			RelName:  "pg_stat_wal",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 5,
			Attrs: []nailedAttr{
				{Name: "wal_records", TypeOID: 20, Num: 1, Len: 8},
				{Name: "wal_fpi", TypeOID: 20, Num: 2, Len: 8},
				{Name: "wal_bytes", TypeOID: 1700, Num: 3, Len: -1},
				{Name: "wal_buffers_full", TypeOID: 20, Num: 4, Len: 8},
				{Name: "stats_reset", TypeOID: 1184, Num: 5, Len: 8},
			},
		},
		// pg_stat_progress_basebackup — _RETURN rule OID 12332, upstream reltype 12331.
		{
			OID:      12329,
			RelName:  "pg_stat_progress_basebackup",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 6,
			Attrs: []nailedAttr{
				{Name: "pid", TypeOID: 23, Num: 1, Len: 4},
				{Name: "phase", TypeOID: 25, Num: 2, Len: -1},
				{Name: "backup_total", TypeOID: 20, Num: 3, Len: 8},
				{Name: "backup_streamed", TypeOID: 20, Num: 4, Len: 8},
				{Name: "tablespaces_total", TypeOID: 20, Num: 5, Len: 8},
				{Name: "tablespaces_streamed", TypeOID: 20, Num: 6, Len: 8},
			},
		},
		// pg_replication_origin_status — _RETURN rule OID 12346, upstream reltype 12345.
		{
			OID:      12343,
			RelName:  "pg_replication_origin_status",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 4,
			Attrs: []nailedAttr{
				{Name: "local_id", TypeOID: 26, Num: 1, Len: 4},
				{Name: "external_id", TypeOID: 25, Num: 2, Len: -1},
				{Name: "remote_lsn", TypeOID: 3220, Num: 3, Len: 8},
				{Name: "local_lsn", TypeOID: 3220, Num: 4, Len: 8},
			},
		},
		// pg_wait_events — _RETURN rule OID 12354, upstream reltype 12353.
		{
			OID:      12351,
			RelName:  "pg_wait_events",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 3,
			Attrs: []nailedAttr{
				{Name: "type", TypeOID: 25, Num: 1, Len: -1},
				{Name: "name", TypeOID: 25, Num: 2, Len: -1},
				{Name: "description", TypeOID: 25, Num: 3, Len: -1},
			},
		},
		// pg_aios — _RETURN rule OID 12358, upstream reltype 12357.
		{
			OID:      12355,
			RelName:  "pg_aios",
			RelType:  2249,
			RelKind:  'v',
			RelNatts: 15,
			Attrs: []nailedAttr{
				{Name: "pid", TypeOID: 23, Num: 1, Len: 4},
				{Name: "io_id", TypeOID: 23, Num: 2, Len: 4},
				{Name: "io_generation", TypeOID: 20, Num: 3, Len: 8},
				{Name: "state", TypeOID: 25, Num: 4, Len: -1},
				{Name: "operation", TypeOID: 25, Num: 5, Len: -1},
				{Name: "off", TypeOID: 20, Num: 6, Len: 8},
				{Name: "length", TypeOID: 20, Num: 7, Len: 8},
				{Name: "target", TypeOID: 25, Num: 8, Len: -1},
				{Name: "handle_data_len", TypeOID: 21, Num: 9, Len: 2},
				{Name: "raw_result", TypeOID: 23, Num: 10, Len: 4},
				{Name: "result", TypeOID: 25, Num: 11, Len: -1},
				{Name: "target_desc", TypeOID: 25, Num: 12, Len: -1},
				{Name: "f_sync", TypeOID: 16, Num: 13, Len: 1},
				{Name: "f_localmem", TypeOID: 16, Num: 14, Len: 1},
				{Name: "f_buffered", TypeOID: 16, Num: 15, Len: 1},
			},
		},
	}
}

// nailedViewRewriteEntries returns the 33 ON-SELECT (_RETURN) rules that back
// the on-disk system views, rendered from the same manifest as
// nailedViewSeedRels. A hosted PG opening a view with relhasrules=true
// resolves the rule through SearchSysCache2(RULERELNAME, view_oid, "_RETURN")
// and FATALs with "cache lookup failed for rule …" if the row is absent, so
// every rel row above owes exactly one entry here.
//
// Only the OIDs and the ev_class link vary: an ON-SELECT view rule is always
// _RETURN / CMD_SELECT ('1') / ALWAYS ('O') / INSTEAD, with an empty ev_qual
// ("<>"). The ev_action body is read from the embedded capture by view name
// (nailed_view_ev_action.go), which is why adding a view needs no //go:embed
// line.
func nailedViewRewriteEntries() []pgRewriteEntry {
	return []pgRewriteEntry{
		{
			OID:       12031,
			RuleName:  "_RETURN",
			EvClass:   12028, // pg_views
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_views"),
		},
		{
			OID:       12036,
			RuleName:  "_RETURN",
			EvClass:   12033, // pg_tables
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_tables"),
		},
		{
			OID:       12041,
			RuleName:  "_RETURN",
			EvClass:   12038, // pg_matviews
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_matviews"),
		},
		{
			OID:       12076,
			RuleName:  "_RETURN",
			EvClass:   12073, // pg_locks
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_locks"),
		},
		{
			OID:       12080,
			RuleName:  "_RETURN",
			EvClass:   12077, // pg_cursors
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_cursors"),
		},
		{
			OID:       12098,
			RuleName:  "_RETURN",
			EvClass:   12095, // pg_prepared_statements
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_prepared_statements"),
		},
		{
			OID:       12107,
			RuleName:  "_RETURN",
			EvClass:   12104, // pg_settings
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_settings"),
		},
		{
			OID:       12113,
			RuleName:  "_RETURN",
			EvClass:   12110, // pg_file_settings
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_file_settings"),
		},
		{
			OID:       12117,
			RuleName:  "_RETURN",
			EvClass:   12114, // pg_hba_file_rules
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_hba_file_rules"),
		},
		{
			OID:       12121,
			RuleName:  "_RETURN",
			EvClass:   12118, // pg_ident_file_mappings
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_ident_file_mappings"),
		},
		{
			OID:       12129,
			RuleName:  "_RETURN",
			EvClass:   12126, // pg_timezone_names
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_timezone_names"),
		},
		{
			OID:       12133,
			RuleName:  "_RETURN",
			EvClass:   12130, // pg_config
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_config"),
		},
		{
			OID:       12137,
			RuleName:  "_RETURN",
			EvClass:   12134, // pg_shmem_allocations
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_shmem_allocations"),
		},
		{
			OID:       12141,
			RuleName:  "_RETURN",
			EvClass:   12138, // pg_shmem_allocations_numa
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_shmem_allocations_numa"),
		},
		{
			OID:       12145,
			RuleName:  "_RETURN",
			EvClass:   12142, // pg_backend_memory_contexts
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_backend_memory_contexts"),
		},
		{
			OID:       12234,
			RuleName:  "_RETURN",
			EvClass:   12231, // pg_stat_replication
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_replication"),
		},
		{
			OID:       12239,
			RuleName:  "_RETURN",
			EvClass:   12236, // pg_stat_slru
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_slru"),
		},
		{
			OID:       12243,
			RuleName:  "_RETURN",
			EvClass:   12240, // pg_stat_wal_receiver
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_wal_receiver"),
		},
		{
			OID:       12247,
			RuleName:  "_RETURN",
			EvClass:   12244, // pg_stat_recovery_prefetch
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_recovery_prefetch"),
		},
		{
			OID:       12251,
			RuleName:  "_RETURN",
			EvClass:   12248, // pg_stat_subscription
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_subscription"),
		},
		{
			OID:       12256,
			RuleName:  "_RETURN",
			EvClass:   12253, // pg_stat_ssl
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_ssl"),
		},
		{
			OID:       12260,
			RuleName:  "_RETURN",
			EvClass:   12257, // pg_stat_gssapi
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_gssapi"),
		},
		{
			OID:       12264,
			RuleName:  "_RETURN",
			EvClass:   12261, // pg_replication_slots
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_replication_slots"),
		},
		{
			OID:       12269,
			RuleName:  "_RETURN",
			EvClass:   12266, // pg_stat_replication_slots
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_replication_slots"),
		},
		{
			OID:       12292,
			RuleName:  "_RETURN",
			EvClass:   12289, // pg_stat_archiver
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_archiver"),
		},
		{
			OID:       12296,
			RuleName:  "_RETURN",
			EvClass:   12293, // pg_stat_bgwriter
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_bgwriter"),
		},
		{
			OID:       12300,
			RuleName:  "_RETURN",
			EvClass:   12297, // pg_stat_checkpointer
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_checkpointer"),
		},
		{
			OID:       12304,
			RuleName:  "_RETURN",
			EvClass:   12301, // pg_stat_io
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_io"),
		},
		{
			OID:       12308,
			RuleName:  "_RETURN",
			EvClass:   12305, // pg_stat_wal
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_wal"),
		},
		{
			OID:       12332,
			RuleName:  "_RETURN",
			EvClass:   12329, // pg_stat_progress_basebackup
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_stat_progress_basebackup"),
		},
		{
			OID:       12346,
			RuleName:  "_RETURN",
			EvClass:   12343, // pg_replication_origin_status
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_replication_origin_status"),
		},
		{
			OID:       12354,
			RuleName:  "_RETURN",
			EvClass:   12351, // pg_wait_events
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_wait_events"),
		},
		{
			OID:       12358,
			RuleName:  "_RETURN",
			EvClass:   12355, // pg_aios
			EvType:    '1',
			EvEnabled: 'O',
			IsInstead: true,
			EvQual:    "<>",
			EvAction:  nailedViewEvAction("pg_aios"),
		},
	}
}
