// Code generated by .ralph/tmp_gen_pg_aggregate.py. DO NOT EDIT.

package initdb

import (
	"fmt"

	"github.com/goopg/goopg/internal/catalog"
	"github.com/goopg/goopg/internal/executor"
)

// pgAggregateEntry mirrors one row of PG18's pg_aggregate (OID 2600).
// The first 20 columns are fixed-size; agginitval and aggminitval are
// variable-length text (nullable).
type pgAggregateEntry struct {
	AggFnOID        uint32 // aggfnoid (regproc) — also the row OID
	AggKind         byte   // aggkind: 'n'=normal, 'o'=ordered-set, 'h'=hypothetical
	AggNumDirectArgs int16  // aggnumdirectargs (direct args for ordered-set)
	AggTransFn      uint32 // aggtransfn
	AggFinalFn      uint32 // aggfinalfn (0 if none)
	AggCombineFn    uint32 // aggcombinefn (0 if none)
	AggSerialFn     uint32 // aggserialfn (0 if none)
	AggDeserialFn   uint32 // aggdeserialfn (0 if none)
	AggMTransFn     uint32 // aggmtransfn (0 if none)
	AggMInvTransFn  uint32 // aggminvtransfn (0 if none)
	AggMFinalFn     uint32 // aggmfinalfn (0 if none)
	AggFinalExtra   bool   // aggfinalextra
	AggMFinalExtra  bool   // aggmfinalextra
	AggFinalModify  byte   // aggfinalmodify: 'r','s','w'
	AggMFinalModify byte   // aggmfinalmodify: 'r','s','w'
	AggSortOp       uint32 // aggsortop (0 if none)
	AggTransType    uint32 // aggtranstype
	AggTransSpace   int32  // aggtransspace
	AggMTransType   uint32 // aggmtranstype (0 if none)
	AggMTransSpace  int32  // aggmtransspace
	AggInitVal      string // agginitval (empty = NULL)
	AggMInitVal     string // aggminitval (empty = NULL)
}

// pgAggregateColDefs returns the 22-column PG18 pg_aggregate schema.
// Columns 1-20 are fixed-size; 21-22 (agginitval, aggminitval) are nullable text.
// Column order matches FormData_pg_aggregate so PG's GETSTRUCT cast works.
func pgAggregateColDefs() []catalog.Column {
	return []catalog.Column{
		{Name: "aggfnoid",        Type: catalog.Type{Name: "regproc"}}, // 1  regproc (=oid 24)
		{Name: "aggkind",          Type: catalog.Type{Name: "char"}},   // 2
		{Name: "aggnumdirectargs", Type: catalog.Type{Name: "int2"}},   // 3
		{Name: "aggtransfn",       Type: catalog.Type{Name: "regproc"}}, // 4
		{Name: "aggfinalfn",       Type: catalog.Type{Name: "regproc"}}, // 5
		{Name: "aggcombinefn",     Type: catalog.Type{Name: "regproc"}}, // 6
		{Name: "aggserialfn",      Type: catalog.Type{Name: "regproc"}}, // 7
		{Name: "aggdeserialfn",    Type: catalog.Type{Name: "regproc"}}, // 8
		{Name: "aggmtransfn",      Type: catalog.Type{Name: "regproc"}}, // 9
		{Name: "aggminvtransfn",   Type: catalog.Type{Name: "regproc"}}, // 10
		{Name: "aggmfinalfn",      Type: catalog.Type{Name: "regproc"}}, // 11
		{Name: "aggfinalextra",    Type: catalog.Type{Name: "bool"}},   // 12
		{Name: "aggmfinalextra",   Type: catalog.Type{Name: "bool"}},   // 13
		{Name: "aggfinalmodify",   Type: catalog.Type{Name: "char"}},   // 14
		{Name: "aggmfinalmodify",  Type: catalog.Type{Name: "char"}},   // 15
		{Name: "aggsortop",        Type: catalog.Type{Name: "oid"}},    // 16
		{Name: "aggtranstype",     Type: catalog.Type{Name: "oid"}},    // 17
		{Name: "aggtransspace",    Type: catalog.Type{Name: "int4"}},   // 18
		{Name: "aggmtranstype",    Type: catalog.Type{Name: "oid"}},    // 19
		{Name: "aggmtransspace",   Type: catalog.Type{Name: "int4"}},   // 20
		{Name: "agginitval",       Type: catalog.Type{Name: "text"}},   // 21 nullable
		{Name: "aggminitval",      Type: catalog.Type{Name: "text"}},   // 22 nullable
	}
}

// aggNullableText returns NullDatum for an empty string (BKI _null_),
// or a text Datum for a non-empty agginitval / aggminitval value.
func aggNullableText(s string) executor.Datum {
	if s == "" {
		return executor.NullDatum
	}
	return executor.NewStringDatum(s)
}

// pgAggregateRow encodes one pg_aggregate row as a 22-column executor.Row.
// pg_aggregate has no separate oid column — aggfnoid (column 1) is the
// primary key. The row order matches FormData_pg_aggregate exactly.
func pgAggregateRow(e pgAggregateEntry) executor.Row {
	return executor.Row{
		executor.NewIntDatum(int64(e.AggFnOID)),                          // 1  aggfnoid
		executor.NewStringDatum(string([]byte{e.AggKind})),               // 2  aggkind
		executor.NewIntDatum(int64(e.AggNumDirectArgs)),                  // 3  aggnumdirectargs
		executor.NewIntDatum(int64(e.AggTransFn)),                        // 4  aggtransfn
		executor.NewIntDatum(int64(e.AggFinalFn)),                        // 5  aggfinalfn
		executor.NewIntDatum(int64(e.AggCombineFn)),                      // 6  aggcombinefn
		executor.NewIntDatum(int64(e.AggSerialFn)),                       // 7  aggserialfn
		executor.NewIntDatum(int64(e.AggDeserialFn)),                     // 8  aggdeserialfn
		executor.NewIntDatum(int64(e.AggMTransFn)),                       // 9  aggmtransfn
		executor.NewIntDatum(int64(e.AggMInvTransFn)),                    // 10 aggminvtransfn
		executor.NewIntDatum(int64(e.AggMFinalFn)),                       // 11 aggmfinalfn
		executor.NewBoolDatum(e.AggFinalExtra),                           // 12 aggfinalextra
		executor.NewBoolDatum(e.AggMFinalExtra),                          // 13 aggmfinalextra
		executor.NewStringDatum(string([]byte{e.AggFinalModify})),         // 14 aggfinalmodify
		executor.NewStringDatum(string([]byte{e.AggMFinalModify})),        // 15 aggmfinalmodify
		executor.NewIntDatum(int64(e.AggSortOp)),                         // 16 aggsortop
		executor.NewIntDatum(int64(e.AggTransType)),                      // 17 aggtranstype
		executor.NewIntDatum(int64(e.AggTransSpace)),                     // 18 aggtransspace
		executor.NewIntDatum(int64(e.AggMTransType)),                     // 19 aggmtranstype
		executor.NewIntDatum(int64(e.AggMTransSpace)),                    // 20 aggmtransspace
		aggNullableText(e.AggInitVal),                                    // 21 agginitval (nullable)
		aggNullableText(e.AggMInitVal),                                   // 22 aggminitval (nullable)
	}
}

// pgAggregateInitialEntries returns all 161 BKI rows for pg_aggregate
// (OID 2600), sourced from PG18's pg_aggregate.dat.
// aggfnoid is the proc OID of the aggregate function (= the row key).
// All proc/type/operator OIDs are resolved from the respective .dat files.
func pgAggregateInitialEntries() []pgAggregateEntry {
	return []pgAggregateEntry{
		// avg(int8)
		{
			AggFnOID: 2100, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2746, AggFinalFn: 3389, AggCombineFn: 2785,
			AggSerialFn: 2786, AggDeserialFn: 2787,
			AggMTransFn: 2746, AggMInvTransFn: 3387, AggMFinalFn: 3389,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// avg(int4)
		{
			AggFnOID: 2101, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1963, AggFinalFn: 1964, AggCombineFn: 3324,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 1963, AggMInvTransFn: 3571, AggMFinalFn: 1964,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1016,
			AggTransSpace: 0, AggMTransType: 1016, AggMTransSpace: 0,
			AggInitVal: "{0,0}",
			AggMInitVal: "{0,0}",
		},
		// avg(int2)
		{
			AggFnOID: 2102, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1962, AggFinalFn: 1964, AggCombineFn: 3324,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 1962, AggMInvTransFn: 3570, AggMFinalFn: 1964,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1016,
			AggTransSpace: 0, AggMTransType: 1016, AggMTransSpace: 0,
			AggInitVal: "{0,0}",
			AggMInitVal: "{0,0}",
		},
		// avg(numeric)
		{
			AggFnOID: 2103, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2858, AggFinalFn: 1837, AggCombineFn: 3337,
			AggSerialFn: 2740, AggDeserialFn: 2741,
			AggMTransFn: 2858, AggMInvTransFn: 3548, AggMFinalFn: 1837,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// avg(float4)
		{
			AggFnOID: 2104, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 208, AggFinalFn: 1830, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// avg(float8)
		{
			AggFnOID: 2105, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 222, AggFinalFn: 1830, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// avg(interval)
		{
			AggFnOID: 2106, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1843, AggFinalFn: 1844, AggCombineFn: 3325,
			AggSerialFn: 6324, AggDeserialFn: 6325,
			AggMTransFn: 1843, AggMInvTransFn: 3549, AggMFinalFn: 1844,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 40, AggMTransType: 2281, AggMTransSpace: 40,
		},
		// sum(int8)
		{
			AggFnOID: 2107, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2746, AggFinalFn: 3388, AggCombineFn: 2785,
			AggSerialFn: 2786, AggDeserialFn: 2787,
			AggMTransFn: 2746, AggMInvTransFn: 3387, AggMFinalFn: 3388,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// sum(int4)
		{
			AggFnOID: 2108, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1841, AggFinalFn: 0, AggCombineFn: 463,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 1963, AggMInvTransFn: 3571, AggMFinalFn: 3572,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 20,
			AggTransSpace: 0, AggMTransType: 1016, AggMTransSpace: 0,
			AggMInitVal: "{0,0}",
		},
		// sum(int2)
		{
			AggFnOID: 2109, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1840, AggFinalFn: 0, AggCombineFn: 463,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 1962, AggMInvTransFn: 3570, AggMFinalFn: 3572,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 20,
			AggTransSpace: 0, AggMTransType: 1016, AggMTransSpace: 0,
			AggMInitVal: "{0,0}",
		},
		// sum(float4)
		{
			AggFnOID: 2110, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 204, AggFinalFn: 0, AggCombineFn: 204,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 700,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// sum(float8)
		{
			AggFnOID: 2111, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 218, AggFinalFn: 0, AggCombineFn: 218,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 701,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// sum(money)
		{
			AggFnOID: 2112, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 894, AggFinalFn: 0, AggCombineFn: 894,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 894, AggMInvTransFn: 895, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 790,
			AggTransSpace: 0, AggMTransType: 790, AggMTransSpace: 0,
		},
		// sum(interval)
		{
			AggFnOID: 2113, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1843, AggFinalFn: 6326, AggCombineFn: 3325,
			AggSerialFn: 6324, AggDeserialFn: 6325,
			AggMTransFn: 1843, AggMInvTransFn: 3549, AggMFinalFn: 6326,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 40, AggMTransType: 2281, AggMTransSpace: 40,
		},
		// sum(numeric)
		{
			AggFnOID: 2114, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2858, AggFinalFn: 3178, AggCombineFn: 3337,
			AggSerialFn: 2740, AggDeserialFn: 2741,
			AggMTransFn: 2858, AggMInvTransFn: 3548, AggMFinalFn: 3178,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// max(int8)
		{
			AggFnOID: 2115, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1236, AggFinalFn: 0, AggCombineFn: 1236,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 413, AggTransType: 20,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(int4)
		{
			AggFnOID: 2116, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 768, AggFinalFn: 0, AggCombineFn: 768,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 521, AggTransType: 23,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(int2)
		{
			AggFnOID: 2117, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 770, AggFinalFn: 0, AggCombineFn: 770,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 520, AggTransType: 21,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(oid)
		{
			AggFnOID: 2118, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1965, AggFinalFn: 0, AggCombineFn: 1965,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 610, AggTransType: 26,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(float4)
		{
			AggFnOID: 2119, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 209, AggFinalFn: 0, AggCombineFn: 209,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 623, AggTransType: 700,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(float8)
		{
			AggFnOID: 2120, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 223, AggFinalFn: 0, AggCombineFn: 223,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 674, AggTransType: 701,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(date)
		{
			AggFnOID: 2122, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1138, AggFinalFn: 0, AggCombineFn: 1138,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1097, AggTransType: 1082,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(time)
		{
			AggFnOID: 2123, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1377, AggFinalFn: 0, AggCombineFn: 1377,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1112, AggTransType: 1083,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(timetz)
		{
			AggFnOID: 2124, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1379, AggFinalFn: 0, AggCombineFn: 1379,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1554, AggTransType: 1266,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(money)
		{
			AggFnOID: 2125, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 898, AggFinalFn: 0, AggCombineFn: 898,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 903, AggTransType: 790,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(timestamp)
		{
			AggFnOID: 2126, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2036, AggFinalFn: 0, AggCombineFn: 2036,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 2064, AggTransType: 1114,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(timestamptz)
		{
			AggFnOID: 2127, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1196, AggFinalFn: 0, AggCombineFn: 1196,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1324, AggTransType: 1184,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(interval)
		{
			AggFnOID: 2128, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1198, AggFinalFn: 0, AggCombineFn: 1198,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1334, AggTransType: 1186,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(text)
		{
			AggFnOID: 2129, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 458, AggFinalFn: 0, AggCombineFn: 458,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 666, AggTransType: 25,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(numeric)
		{
			AggFnOID: 2130, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1767, AggFinalFn: 0, AggCombineFn: 1767,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1756, AggTransType: 1700,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(anyarray)
		{
			AggFnOID: 2050, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 515, AggFinalFn: 0, AggCombineFn: 515,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1073, AggTransType: 2277,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(record)
		{
			AggFnOID: 6373, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6375, AggFinalFn: 0, AggCombineFn: 6375,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 2991, AggTransType: 2249,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(bpchar)
		{
			AggFnOID: 2244, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1063, AggFinalFn: 0, AggCombineFn: 1063,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1060, AggTransType: 1042,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(tid)
		{
			AggFnOID: 2797, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2795, AggFinalFn: 0, AggCombineFn: 2795,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 2800, AggTransType: 27,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(anyenum)
		{
			AggFnOID: 3526, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 3525, AggFinalFn: 0, AggCombineFn: 3525,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 3519, AggTransType: 3500,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(inet)
		{
			AggFnOID: 3564, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 3562, AggFinalFn: 0, AggCombineFn: 3562,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1205, AggTransType: 869,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(pg_lsn)
		{
			AggFnOID: 4189, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 4187, AggFinalFn: 0, AggCombineFn: 4187,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 3225, AggTransType: 3220,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(xid8)
		{
			AggFnOID: 5099, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 5097, AggFinalFn: 0, AggCombineFn: 5097,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 5074, AggTransType: 5069,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// max(bytea)
		{
			AggFnOID: 6395, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6393, AggFinalFn: 0, AggCombineFn: 6393,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1959, AggTransType: 17,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(int8)
		{
			AggFnOID: 2131, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1237, AggFinalFn: 0, AggCombineFn: 1237,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 412, AggTransType: 20,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(int4)
		{
			AggFnOID: 2132, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 769, AggFinalFn: 0, AggCombineFn: 769,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 97, AggTransType: 23,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(int2)
		{
			AggFnOID: 2133, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 771, AggFinalFn: 0, AggCombineFn: 771,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 95, AggTransType: 21,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(oid)
		{
			AggFnOID: 2134, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1966, AggFinalFn: 0, AggCombineFn: 1966,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 609, AggTransType: 26,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(float4)
		{
			AggFnOID: 2135, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 211, AggFinalFn: 0, AggCombineFn: 211,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 622, AggTransType: 700,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(float8)
		{
			AggFnOID: 2136, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 224, AggFinalFn: 0, AggCombineFn: 224,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 672, AggTransType: 701,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(date)
		{
			AggFnOID: 2138, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1139, AggFinalFn: 0, AggCombineFn: 1139,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1095, AggTransType: 1082,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(time)
		{
			AggFnOID: 2139, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1378, AggFinalFn: 0, AggCombineFn: 1378,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1110, AggTransType: 1083,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(timetz)
		{
			AggFnOID: 2140, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1380, AggFinalFn: 0, AggCombineFn: 1380,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1552, AggTransType: 1266,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(money)
		{
			AggFnOID: 2141, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 899, AggFinalFn: 0, AggCombineFn: 899,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 902, AggTransType: 790,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(timestamp)
		{
			AggFnOID: 2142, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2035, AggFinalFn: 0, AggCombineFn: 2035,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 2062, AggTransType: 1114,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(timestamptz)
		{
			AggFnOID: 2143, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1195, AggFinalFn: 0, AggCombineFn: 1195,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1322, AggTransType: 1184,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(interval)
		{
			AggFnOID: 2144, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1197, AggFinalFn: 0, AggCombineFn: 1197,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1332, AggTransType: 1186,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(text)
		{
			AggFnOID: 2145, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 459, AggFinalFn: 0, AggCombineFn: 459,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 664, AggTransType: 25,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(numeric)
		{
			AggFnOID: 2146, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1766, AggFinalFn: 0, AggCombineFn: 1766,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1754, AggTransType: 1700,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(anyarray)
		{
			AggFnOID: 2051, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 516, AggFinalFn: 0, AggCombineFn: 516,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1072, AggTransType: 2277,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(record)
		{
			AggFnOID: 6374, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6376, AggFinalFn: 0, AggCombineFn: 6376,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 2990, AggTransType: 2249,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(bpchar)
		{
			AggFnOID: 2245, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1064, AggFinalFn: 0, AggCombineFn: 1064,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1058, AggTransType: 1042,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(tid)
		{
			AggFnOID: 2798, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2796, AggFinalFn: 0, AggCombineFn: 2796,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 2799, AggTransType: 27,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(anyenum)
		{
			AggFnOID: 3527, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 3524, AggFinalFn: 0, AggCombineFn: 3524,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 3518, AggTransType: 3500,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(inet)
		{
			AggFnOID: 3565, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 3563, AggFinalFn: 0, AggCombineFn: 3563,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1203, AggTransType: 869,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(pg_lsn)
		{
			AggFnOID: 4190, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 4188, AggFinalFn: 0, AggCombineFn: 4188,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 3224, AggTransType: 3220,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(xid8)
		{
			AggFnOID: 5100, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 5098, AggFinalFn: 0, AggCombineFn: 5098,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 5073, AggTransType: 5069,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// min(bytea)
		{
			AggFnOID: 6396, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6394, AggFinalFn: 0, AggCombineFn: 6394,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 1957, AggTransType: 17,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// count(any)
		{
			AggFnOID: 2147, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2804, AggFinalFn: 0, AggCombineFn: 463,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 2804, AggMInvTransFn: 3547, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 20,
			AggTransSpace: 0, AggMTransType: 20, AggMTransSpace: 0,
			AggInitVal: "0",
			AggMInitVal: "0",
		},
		// count()
		{
			AggFnOID: 2803, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1219, AggFinalFn: 0, AggCombineFn: 463,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 1219, AggMInvTransFn: 3546, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 20,
			AggTransSpace: 0, AggMTransType: 20, AggMTransSpace: 0,
			AggInitVal: "0",
			AggMInitVal: "0",
		},
		// var_pop(int8)
		{
			AggFnOID: 2718, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1836, AggFinalFn: 2514, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1836, AggMInvTransFn: 3569, AggMFinalFn: 2514,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// var_pop(int4)
		{
			AggFnOID: 2719, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1835, AggFinalFn: 3390, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1835, AggMInvTransFn: 3568, AggMFinalFn: 3390,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// var_pop(int2)
		{
			AggFnOID: 2720, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1834, AggFinalFn: 3390, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1834, AggMInvTransFn: 3567, AggMFinalFn: 3390,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// var_pop(float4)
		{
			AggFnOID: 2721, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 208, AggFinalFn: 2512, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// var_pop(float8)
		{
			AggFnOID: 2722, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 222, AggFinalFn: 2512, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// var_pop(numeric)
		{
			AggFnOID: 2723, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1833, AggFinalFn: 2514, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1833, AggMInvTransFn: 3548, AggMFinalFn: 2514,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// var_samp(int8)
		{
			AggFnOID: 2641, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1836, AggFinalFn: 1838, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1836, AggMInvTransFn: 3569, AggMFinalFn: 1838,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// var_samp(int4)
		{
			AggFnOID: 2642, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1835, AggFinalFn: 3391, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1835, AggMInvTransFn: 3568, AggMFinalFn: 3391,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// var_samp(int2)
		{
			AggFnOID: 2643, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1834, AggFinalFn: 3391, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1834, AggMInvTransFn: 3567, AggMFinalFn: 3391,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// var_samp(float4)
		{
			AggFnOID: 2644, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 208, AggFinalFn: 1831, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// var_samp(float8)
		{
			AggFnOID: 2645, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 222, AggFinalFn: 1831, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// var_samp(numeric)
		{
			AggFnOID: 2646, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1833, AggFinalFn: 1838, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1833, AggMInvTransFn: 3548, AggMFinalFn: 1838,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// variance(int8)
		{
			AggFnOID: 2148, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1836, AggFinalFn: 1838, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1836, AggMInvTransFn: 3569, AggMFinalFn: 1838,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// variance(int4)
		{
			AggFnOID: 2149, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1835, AggFinalFn: 3391, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1835, AggMInvTransFn: 3568, AggMFinalFn: 3391,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// variance(int2)
		{
			AggFnOID: 2150, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1834, AggFinalFn: 3391, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1834, AggMInvTransFn: 3567, AggMFinalFn: 3391,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// variance(float4)
		{
			AggFnOID: 2151, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 208, AggFinalFn: 1831, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// variance(float8)
		{
			AggFnOID: 2152, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 222, AggFinalFn: 1831, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// variance(numeric)
		{
			AggFnOID: 2153, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1833, AggFinalFn: 1838, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1833, AggMInvTransFn: 3548, AggMFinalFn: 1838,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// stddev_pop(int8)
		{
			AggFnOID: 2724, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1836, AggFinalFn: 2596, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1836, AggMInvTransFn: 3569, AggMFinalFn: 2596,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// stddev_pop(int4)
		{
			AggFnOID: 2725, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1835, AggFinalFn: 3392, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1835, AggMInvTransFn: 3568, AggMFinalFn: 3392,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// stddev_pop(int2)
		{
			AggFnOID: 2726, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1834, AggFinalFn: 3392, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1834, AggMInvTransFn: 3567, AggMFinalFn: 3392,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// stddev_pop(float4)
		{
			AggFnOID: 2727, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 208, AggFinalFn: 2513, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// stddev_pop(float8)
		{
			AggFnOID: 2728, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 222, AggFinalFn: 2513, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// stddev_pop(numeric)
		{
			AggFnOID: 2729, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1833, AggFinalFn: 2596, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1833, AggMInvTransFn: 3548, AggMFinalFn: 2596,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// stddev_samp(int8)
		{
			AggFnOID: 2712, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1836, AggFinalFn: 1839, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1836, AggMInvTransFn: 3569, AggMFinalFn: 1839,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// stddev_samp(int4)
		{
			AggFnOID: 2713, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1835, AggFinalFn: 3393, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1835, AggMInvTransFn: 3568, AggMFinalFn: 3393,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// stddev_samp(int2)
		{
			AggFnOID: 2714, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1834, AggFinalFn: 3393, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1834, AggMInvTransFn: 3567, AggMFinalFn: 3393,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// stddev_samp(float4)
		{
			AggFnOID: 2715, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 208, AggFinalFn: 1832, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// stddev_samp(float8)
		{
			AggFnOID: 2716, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 222, AggFinalFn: 1832, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// stddev_samp(numeric)
		{
			AggFnOID: 2717, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1833, AggFinalFn: 1839, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1833, AggMInvTransFn: 3548, AggMFinalFn: 1839,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// stddev(int8)
		{
			AggFnOID: 2154, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1836, AggFinalFn: 1839, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1836, AggMInvTransFn: 3569, AggMFinalFn: 1839,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// stddev(int4)
		{
			AggFnOID: 2155, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1835, AggFinalFn: 3393, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1835, AggMInvTransFn: 3568, AggMFinalFn: 3393,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// stddev(int2)
		{
			AggFnOID: 2156, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1834, AggFinalFn: 3393, AggCombineFn: 3338,
			AggSerialFn: 3339, AggDeserialFn: 3340,
			AggMTransFn: 1834, AggMInvTransFn: 3567, AggMFinalFn: 3393,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 48, AggMTransType: 2281, AggMTransSpace: 48,
		},
		// stddev(float4)
		{
			AggFnOID: 2157, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 208, AggFinalFn: 1832, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// stddev(float8)
		{
			AggFnOID: 2158, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 222, AggFinalFn: 1832, AggCombineFn: 276,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0}",
		},
		// stddev(numeric)
		{
			AggFnOID: 2159, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1833, AggFinalFn: 1839, AggCombineFn: 3341,
			AggSerialFn: 3335, AggDeserialFn: 3336,
			AggMTransFn: 1833, AggMInvTransFn: 3548, AggMFinalFn: 1839,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 128, AggMTransType: 2281, AggMTransSpace: 128,
		},
		// regr_count
		{
			AggFnOID: 2818, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2805, AggFinalFn: 0, AggCombineFn: 463,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 20,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "0",
		},
		// regr_sxx
		{
			AggFnOID: 2819, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2806, AggFinalFn: 2807, AggCombineFn: 3342,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0,0,0,0}",
		},
		// regr_syy
		{
			AggFnOID: 2820, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2806, AggFinalFn: 2808, AggCombineFn: 3342,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0,0,0,0}",
		},
		// regr_sxy
		{
			AggFnOID: 2821, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2806, AggFinalFn: 2809, AggCombineFn: 3342,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0,0,0,0}",
		},
		// regr_avgx
		{
			AggFnOID: 2822, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2806, AggFinalFn: 2810, AggCombineFn: 3342,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0,0,0,0}",
		},
		// regr_avgy
		{
			AggFnOID: 2823, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2806, AggFinalFn: 2811, AggCombineFn: 3342,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0,0,0,0}",
		},
		// regr_r2
		{
			AggFnOID: 2824, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2806, AggFinalFn: 2812, AggCombineFn: 3342,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0,0,0,0}",
		},
		// regr_slope
		{
			AggFnOID: 2825, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2806, AggFinalFn: 2813, AggCombineFn: 3342,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0,0,0,0}",
		},
		// regr_intercept
		{
			AggFnOID: 2826, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2806, AggFinalFn: 2814, AggCombineFn: 3342,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0,0,0,0}",
		},
		// covar_pop
		{
			AggFnOID: 2827, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2806, AggFinalFn: 2815, AggCombineFn: 3342,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0,0,0,0}",
		},
		// covar_samp
		{
			AggFnOID: 2828, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2806, AggFinalFn: 2816, AggCombineFn: 3342,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0,0,0,0}",
		},
		// corr
		{
			AggFnOID: 2829, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2806, AggFinalFn: 2817, AggCombineFn: 3342,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1022,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
			AggInitVal: "{0,0,0,0,0,0}",
		},
		// bool_and
		{
			AggFnOID: 2517, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2515, AggFinalFn: 0, AggCombineFn: 2515,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 3496, AggMInvTransFn: 3497, AggMFinalFn: 3498,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 58, AggTransType: 16,
			AggTransSpace: 0, AggMTransType: 2281, AggMTransSpace: 16,
		},
		// bool_or
		{
			AggFnOID: 2518, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2516, AggFinalFn: 0, AggCombineFn: 2516,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 3496, AggMInvTransFn: 3497, AggMFinalFn: 3499,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 59, AggTransType: 16,
			AggTransSpace: 0, AggMTransType: 2281, AggMTransSpace: 16,
		},
		// every
		{
			AggFnOID: 2519, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2515, AggFinalFn: 0, AggCombineFn: 2515,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 3496, AggMInvTransFn: 3497, AggMFinalFn: 3498,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 58, AggTransType: 16,
			AggTransSpace: 0, AggMTransType: 2281, AggMTransSpace: 16,
		},
		// bit_and(int2)
		{
			AggFnOID: 2236, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1892, AggFinalFn: 0, AggCombineFn: 1892,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 21,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// bit_or(int2)
		{
			AggFnOID: 2237, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1893, AggFinalFn: 0, AggCombineFn: 1893,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 21,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// bit_xor(int2)
		{
			AggFnOID: 6164, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1894, AggFinalFn: 0, AggCombineFn: 1894,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 21,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// bit_and(int4)
		{
			AggFnOID: 2238, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1898, AggFinalFn: 0, AggCombineFn: 1898,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 23,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// bit_or(int4)
		{
			AggFnOID: 2239, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1899, AggFinalFn: 0, AggCombineFn: 1899,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 23,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// bit_xor(int4)
		{
			AggFnOID: 6165, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1900, AggFinalFn: 0, AggCombineFn: 1900,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 23,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// bit_and(int8)
		{
			AggFnOID: 2240, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1904, AggFinalFn: 0, AggCombineFn: 1904,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 20,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// bit_or(int8)
		{
			AggFnOID: 2241, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1905, AggFinalFn: 0, AggCombineFn: 1905,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 20,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// bit_xor(int8)
		{
			AggFnOID: 6166, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1906, AggFinalFn: 0, AggCombineFn: 1906,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 20,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// bit_and(bit)
		{
			AggFnOID: 2242, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1673, AggFinalFn: 0, AggCombineFn: 1673,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1560,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// bit_or(bit)
		{
			AggFnOID: 2243, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1674, AggFinalFn: 0, AggCombineFn: 1674,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1560,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// bit_xor(bit)
		{
			AggFnOID: 6167, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 1675, AggFinalFn: 0, AggCombineFn: 1675,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 1560,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// xmlagg
		{
			AggFnOID: 2901, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2900, AggFinalFn: 0, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 142,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// array_agg(anynonarray)
		{
			AggFnOID: 2335, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 2333, AggFinalFn: 2334, AggCombineFn: 6293,
			AggSerialFn: 6294, AggDeserialFn: 6295,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: true, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// array_agg(anyarray)
		{
			AggFnOID: 4053, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 4051, AggFinalFn: 4052, AggCombineFn: 6296,
			AggSerialFn: 6297, AggDeserialFn: 6298,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: true, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// string_agg(text,text)
		{
			AggFnOID: 3538, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 3535, AggFinalFn: 3536, AggCombineFn: 6299,
			AggSerialFn: 6300, AggDeserialFn: 6301,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// string_agg(bytea,bytea)
		{
			AggFnOID: 3545, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 3543, AggFinalFn: 3544, AggCombineFn: 6299,
			AggSerialFn: 6300, AggDeserialFn: 6301,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// range_intersect_agg(anyrange)
		{
			AggFnOID: 4450, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 4401, AggFinalFn: 0, AggCombineFn: 4401,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 3831,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// range_intersect_agg(anymultirange)
		{
			AggFnOID: 4389, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 4388, AggFinalFn: 0, AggCombineFn: 4388,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 4537,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// range_agg(anyrange)
		{
			AggFnOID: 4301, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 4299, AggFinalFn: 4300, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: true, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// range_agg(anymultirange)
		{
			AggFnOID: 6227, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6225, AggFinalFn: 6226, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: true, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// json_agg
		{
			AggFnOID: 3175, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 3173, AggFinalFn: 3174, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// json_agg_strict
		{
			AggFnOID: 6276, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6275, AggFinalFn: 3174, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// json_object_agg
		{
			AggFnOID: 3197, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 3180, AggFinalFn: 3196, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// json_object_agg_unique
		{
			AggFnOID: 6281, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6278, AggFinalFn: 3196, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// json_object_agg_strict
		{
			AggFnOID: 6280, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6277, AggFinalFn: 3196, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// json_object_agg_unique_strict
		{
			AggFnOID: 6282, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6279, AggFinalFn: 3196, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// jsonb_agg
		{
			AggFnOID: 3267, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 3265, AggFinalFn: 3266, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// jsonb_agg_strict
		{
			AggFnOID: 6284, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6283, AggFinalFn: 3266, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// jsonb_object_agg
		{
			AggFnOID: 3270, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 3268, AggFinalFn: 3269, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// jsonb_object_agg_unique
		{
			AggFnOID: 6289, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6286, AggFinalFn: 3269, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// jsonb_object_agg_strict
		{
			AggFnOID: 6288, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6285, AggFinalFn: 3269, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// jsonb_object_agg_unique_strict
		{
			AggFnOID: 6290, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6287, AggFinalFn: 3269, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// percentile_disc(float8,anyelement)
		{
			AggFnOID: 3972, AggKind: 'o', AggNumDirectArgs: 1,
			AggTransFn: 3970, AggFinalFn: 3973, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: true, AggMFinalExtra: false,
			AggFinalModify: 's', AggMFinalModify: 's',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// percentile_cont(float8,float8)
		{
			AggFnOID: 3974, AggKind: 'o', AggNumDirectArgs: 1,
			AggTransFn: 3970, AggFinalFn: 3975, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 's', AggMFinalModify: 's',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// percentile_cont(float8,interval)
		{
			AggFnOID: 3976, AggKind: 'o', AggNumDirectArgs: 1,
			AggTransFn: 3970, AggFinalFn: 3977, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 's', AggMFinalModify: 's',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// percentile_disc(_float8,anyelement)
		{
			AggFnOID: 3978, AggKind: 'o', AggNumDirectArgs: 1,
			AggTransFn: 3970, AggFinalFn: 3979, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: true, AggMFinalExtra: false,
			AggFinalModify: 's', AggMFinalModify: 's',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// percentile_cont(_float8,float8)
		{
			AggFnOID: 3980, AggKind: 'o', AggNumDirectArgs: 1,
			AggTransFn: 3970, AggFinalFn: 3981, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 's', AggMFinalModify: 's',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// percentile_cont(_float8,interval)
		{
			AggFnOID: 3982, AggKind: 'o', AggNumDirectArgs: 1,
			AggTransFn: 3970, AggFinalFn: 3983, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 's', AggMFinalModify: 's',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// mode
		{
			AggFnOID: 3984, AggKind: 'o', AggNumDirectArgs: 0,
			AggTransFn: 3970, AggFinalFn: 3985, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: true, AggMFinalExtra: false,
			AggFinalModify: 's', AggMFinalModify: 's',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// rank(any)
		{
			AggFnOID: 3986, AggKind: 'h', AggNumDirectArgs: 1,
			AggTransFn: 3971, AggFinalFn: 3987, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: true, AggMFinalExtra: false,
			AggFinalModify: 'w', AggMFinalModify: 'w',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// percent_rank(any)
		{
			AggFnOID: 3988, AggKind: 'h', AggNumDirectArgs: 1,
			AggTransFn: 3971, AggFinalFn: 3989, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: true, AggMFinalExtra: false,
			AggFinalModify: 'w', AggMFinalModify: 'w',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// cume_dist(any)
		{
			AggFnOID: 3990, AggKind: 'h', AggNumDirectArgs: 1,
			AggTransFn: 3971, AggFinalFn: 3991, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: true, AggMFinalExtra: false,
			AggFinalModify: 'w', AggMFinalModify: 'w',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// dense_rank(any)
		{
			AggFnOID: 3992, AggKind: 'h', AggNumDirectArgs: 1,
			AggTransFn: 3971, AggFinalFn: 3993, AggCombineFn: 0,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: true, AggMFinalExtra: false,
			AggFinalModify: 'w', AggMFinalModify: 'w',
			AggSortOp: 0, AggTransType: 2281,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
		// any_value(anyelement)
		{
			AggFnOID: 6291, AggKind: 'n', AggNumDirectArgs: 0,
			AggTransFn: 6292, AggFinalFn: 0, AggCombineFn: 6292,
			AggSerialFn: 0, AggDeserialFn: 0,
			AggMTransFn: 0, AggMInvTransFn: 0, AggMFinalFn: 0,
			AggFinalExtra: false, AggMFinalExtra: false,
			AggFinalModify: 'r', AggMFinalModify: 'r',
			AggSortOp: 0, AggTransType: 2283,
			AggTransSpace: 0, AggMTransType: 0, AggMTransSpace: 0,
		},
	}
}

// bootstrapPgAggregateTuples writes all 161 pg_aggregate rows to
// base/{1,5}/2600. The aggfnoid column doubles as the row's logical key
// (pg_aggregate has no separate 'oid' column — the PKEY is aggfnoid).
// Returns a map keyed by aggfnoid OID for index seeding.
func bootstrapPgAggregateTuples(dataDir string) (map[uint32]heapTID, error) {
	cols := pgAggregateColDefs()
	entries := pgAggregateInitialEntries()
	rows := make([]executor.Row, len(entries))
	for i, e := range entries {
		rows[i] = pgAggregateRow(e)
	}
	rawTIDs, err := writeMultiPageHeapRows(dataDir, "2600", cols, rows)
	if err != nil {
		return nil, fmt.Errorf("bootstrapPgAggregateTuples: %w", err)
	}
	tidMap := make(map[uint32]heapTID, len(entries))
	for i, e := range entries {
		tidMap[e.AggFnOID] = rawTIDs[i]
	}
	return tidMap, nil
}

