// Code generated by cmd/gen-pg-type-data/main.go; DO NOT EDIT.
package initdb

// pgTypeAllEntries returns all PG18 base type entries from pg_type.dat
// plus auto-generated array peer entries. Includes 193 entries total.
func pgTypeAllEntries() []pgTypeEntry {
	return []pgTypeEntry{
		{OID: 16, Name: "bool", Len: 1, ByVal: true, Type: 'b', Category: 'B', Align: 'c', Storage: 'p', Input: 1242, Output: 1243, Receive: 2436, Send: 2437},
		{OID: 17, Name: "bytea", Len: -1, ByVal: false, Type: 'b', Category: 'U', Align: 'i', Storage: 'x', Input: 1244, Output: 31, Receive: 2412, Send: 2413},
		{OID: 18, Name: "char", Len: 1, ByVal: true, Type: 'b', Category: 'Z', Align: 'c', Storage: 'p', Input: 1245, Output: 33, Receive: 2434, Send: 2435},
		{OID: 19, Name: "name", Len: 64, ByVal: false, Type: 'b', Category: 'S', Align: 'c', Storage: 'p', Input: 34, Output: 35, Receive: 2422, Send: 2423},
		{OID: 20, Name: "int8", Len: 8, ByVal: true, Type: 'b', Category: 'N', Align: 'd', Storage: 'p', Input: 460, Output: 461, Receive: 2408, Send: 2409},
		{OID: 21, Name: "int2", Len: 2, ByVal: true, Type: 'b', Category: 'N', Align: 's', Storage: 'p', Input: 38, Output: 39, Receive: 2404, Send: 2405},
		{OID: 22, Name: "int2vector", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'p', Input: 40, Output: 41, Receive: 2410, Send: 2411},
		{OID: 23, Name: "int4", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 42, Output: 43, Receive: 2406, Send: 2407},
		{OID: 24, Name: "regproc", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 44, Output: 45, Receive: 2444, Send: 2445},
		{OID: 25, Name: "text", Len: -1, ByVal: false, Type: 'b', Category: 'S', Align: 'i', Storage: 'x', Input: 46, Output: 47, Receive: 2414, Send: 2415},
		{OID: 26, Name: "oid", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 1798, Output: 1799, Receive: 2418, Send: 2419},
		{OID: 27, Name: "tid", Len: 6, ByVal: false, Type: 'b', Category: 'U', Align: 's', Storage: 'p', Input: 48, Output: 49, Receive: 2438, Send: 2439},
		{OID: 28, Name: "xid", Len: 4, ByVal: true, Type: 'b', Category: 'U', Align: 'i', Storage: 'p', Input: 50, Output: 51, Receive: 2440, Send: 2441},
		{OID: 29, Name: "cid", Len: 4, ByVal: true, Type: 'b', Category: 'U', Align: 'i', Storage: 'p', Input: 52, Output: 53, Receive: 2442, Send: 2443},
		{OID: 30, Name: "oidvector", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'p', Input: 54, Output: 55, Receive: 2420, Send: 2421},
		{OID: 32, Name: "pg_ddl_command", Len: 8, ByVal: true, Type: 'p', Category: 'P', Align: 'd', Storage: 'p', Input: 86, Output: 87, Receive: 88, Send: 90},
		{OID: 71, Name: "pg_type", Len: -1, ByVal: false, Type: 'c', Category: 'C', Align: 'd', Storage: 'x', Input: 2290, Output: 2291, Receive: 2402, Send: 2403},
		{OID: 75, Name: "pg_attribute", Len: -1, ByVal: false, Type: 'c', Category: 'C', Align: 'd', Storage: 'x', Input: 2290, Output: 2291, Receive: 2402, Send: 2403},
		{OID: 81, Name: "pg_proc", Len: -1, ByVal: false, Type: 'c', Category: 'C', Align: 'd', Storage: 'x', Input: 2290, Output: 2291, Receive: 2402, Send: 2403},
		{OID: 83, Name: "pg_class", Len: -1, ByVal: false, Type: 'c', Category: 'C', Align: 'd', Storage: 'x', Input: 2290, Output: 2291, Receive: 2402, Send: 2403},
		{OID: 114, Name: "json", Len: -1, ByVal: false, Type: 'b', Category: 'U', Align: 'i', Storage: 'x', Input: 321, Output: 322, Receive: 323, Send: 324},
		{OID: 142, Name: "xml", Len: -1, ByVal: false, Type: 'b', Category: 'U', Align: 'i', Storage: 'x', Input: 2893, Output: 2894, Receive: 2898, Send: 2899},
		{OID: 143, Name: "_xml", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 194, Name: "pg_node_tree", Len: -1, ByVal: false, Type: 'b', Category: 'Z', Align: 'i', Storage: 'x', Input: 195, Output: 196, Receive: 197, Send: 198},
		{OID: 199, Name: "_json", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 210, Name: "_pg_type", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 269, Name: "table_am_handler", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 267, Output: 268, Receive: 0, Send: 0},
		{OID: 270, Name: "_pg_attribute", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 271, Name: "_xid8", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 272, Name: "_pg_proc", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 273, Name: "_pg_class", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 325, Name: "index_am_handler", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 326, Output: 327, Receive: 0, Send: 0},
		{OID: 600, Name: "point", Len: 16, ByVal: false, Type: 'b', Category: 'G', Align: 'd', Storage: 'p', Input: 117, Output: 118, Receive: 2428, Send: 2429},
		{OID: 601, Name: "lseg", Len: 32, ByVal: false, Type: 'b', Category: 'G', Align: 'd', Storage: 'p', Input: 119, Output: 120, Receive: 2480, Send: 2481},
		{OID: 602, Name: "path", Len: -1, ByVal: false, Type: 'b', Category: 'G', Align: 'd', Storage: 'x', Input: 121, Output: 122, Receive: 2482, Send: 2483},
		{OID: 603, Name: "box", Len: 32, ByVal: false, Type: 'b', Category: 'G', Align: 'd', Storage: 'p', Input: 123, Output: 124, Receive: 2484, Send: 2485},
		{OID: 604, Name: "polygon", Len: -1, ByVal: false, Type: 'b', Category: 'G', Align: 'd', Storage: 'x', Input: 347, Output: 348, Receive: 2486, Send: 2487},
		{OID: 628, Name: "line", Len: 24, ByVal: false, Type: 'b', Category: 'G', Align: 'd', Storage: 'p', Input: 1490, Output: 1491, Receive: 2488, Send: 2489},
		{OID: 629, Name: "_line", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 650, Name: "cidr", Len: -1, ByVal: false, Type: 'b', Category: 'I', Align: 'i', Storage: 'm', Input: 1267, Output: 1427, Receive: 2498, Send: 2499},
		{OID: 651, Name: "_cidr", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 700, Name: "float4", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 200, Output: 201, Receive: 2424, Send: 2425},
		{OID: 701, Name: "float8", Len: 8, ByVal: true, Type: 'b', Category: 'N', Align: 'd', Storage: 'p', Input: 214, Output: 215, Receive: 2426, Send: 2427},
		{OID: 705, Name: "unknown", Len: -2, ByVal: false, Type: 'p', Category: 'X', Align: 'c', Storage: 'p', Input: 109, Output: 110, Receive: 2416, Send: 2417},
		{OID: 718, Name: "circle", Len: 24, ByVal: false, Type: 'b', Category: 'G', Align: 'd', Storage: 'p', Input: 1450, Output: 1451, Receive: 2490, Send: 2491},
		{OID: 719, Name: "_circle", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 774, Name: "macaddr8", Len: 8, ByVal: false, Type: 'b', Category: 'U', Align: 'i', Storage: 'p', Input: 4110, Output: 4111, Receive: 3446, Send: 3447},
		{OID: 775, Name: "_macaddr8", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 790, Name: "money", Len: 8, ByVal: true, Type: 'b', Category: 'N', Align: 'd', Storage: 'p', Input: 886, Output: 887, Receive: 2492, Send: 2493},
		{OID: 791, Name: "_money", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 829, Name: "macaddr", Len: 6, ByVal: false, Type: 'b', Category: 'U', Align: 'i', Storage: 'p', Input: 436, Output: 437, Receive: 2494, Send: 2495},
		{OID: 869, Name: "inet", Len: -1, ByVal: false, Type: 'b', Category: 'I', Align: 'i', Storage: 'm', Input: 910, Output: 911, Receive: 2496, Send: 2497},
		{OID: 1000, Name: "_bool", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1001, Name: "_bytea", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1002, Name: "_char", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1003, Name: "_name", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1005, Name: "_int2", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1006, Name: "_int2vector", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1007, Name: "_int4", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1008, Name: "_regproc", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1009, Name: "_text", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1010, Name: "_tid", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1011, Name: "_xid", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1012, Name: "_cid", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1013, Name: "_oidvector", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1014, Name: "_bpchar", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1015, Name: "_varchar", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1016, Name: "_int8", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1017, Name: "_point", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1018, Name: "_lseg", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1019, Name: "_path", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1020, Name: "_box", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1021, Name: "_float4", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1022, Name: "_float8", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1027, Name: "_polygon", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1028, Name: "_oid", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1033, Name: "aclitem", Len: 16, ByVal: false, Type: 'b', Category: 'U', Align: 'd', Storage: 'p', Input: 1031, Output: 1032, Receive: 0, Send: 0},
		{OID: 1034, Name: "_aclitem", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1040, Name: "_macaddr", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1041, Name: "_inet", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1042, Name: "bpchar", Len: -1, ByVal: false, Type: 'b', Category: 'S', Align: 'i', Storage: 'x', Input: 1044, Output: 1045, Receive: 2430, Send: 2431},
		{OID: 1043, Name: "varchar", Len: -1, ByVal: false, Type: 'b', Category: 'S', Align: 'i', Storage: 'x', Input: 1046, Output: 1047, Receive: 2432, Send: 2433},
		{OID: 1082, Name: "date", Len: 4, ByVal: true, Type: 'b', Category: 'D', Align: 'i', Storage: 'p', Input: 1084, Output: 1085, Receive: 2468, Send: 2469},
		{OID: 1083, Name: "time", Len: 8, ByVal: true, Type: 'b', Category: 'D', Align: 'd', Storage: 'p', Input: 1143, Output: 1144, Receive: 2470, Send: 2471},
		{OID: 1114, Name: "timestamp", Len: 8, ByVal: true, Type: 'b', Category: 'D', Align: 'd', Storage: 'p', Input: 1312, Output: 1313, Receive: 2474, Send: 2475},
		{OID: 1115, Name: "_timestamp", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1182, Name: "_date", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1183, Name: "_time", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1184, Name: "timestamptz", Len: 8, ByVal: true, Type: 'b', Category: 'D', Align: 'd', Storage: 'p', Input: 1150, Output: 1151, Receive: 2476, Send: 2477},
		{OID: 1185, Name: "_timestamptz", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1186, Name: "interval", Len: 16, ByVal: false, Type: 'b', Category: 'T', Align: 'd', Storage: 'p', Input: 1160, Output: 1161, Receive: 2478, Send: 2479},
		{OID: 1187, Name: "_interval", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1231, Name: "_numeric", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1263, Name: "_cstring", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1266, Name: "timetz", Len: 12, ByVal: false, Type: 'b', Category: 'D', Align: 'd', Storage: 'p', Input: 1350, Output: 1351, Receive: 2472, Send: 2473},
		{OID: 1270, Name: "_timetz", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1560, Name: "bit", Len: -1, ByVal: false, Type: 'b', Category: 'V', Align: 'i', Storage: 'x', Input: 1564, Output: 1565, Receive: 2456, Send: 2457},
		{OID: 1561, Name: "_bit", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1562, Name: "varbit", Len: -1, ByVal: false, Type: 'b', Category: 'V', Align: 'i', Storage: 'x', Input: 1579, Output: 1580, Receive: 2458, Send: 2459},
		{OID: 1563, Name: "_varbit", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 1700, Name: "numeric", Len: -1, ByVal: false, Type: 'b', Category: 'N', Align: 'i', Storage: 'm', Input: 1701, Output: 1702, Receive: 2460, Send: 2461},
		{OID: 1790, Name: "refcursor", Len: -1, ByVal: false, Type: 'b', Category: 'U', Align: 'i', Storage: 'x', Input: 46, Output: 47, Receive: 2414, Send: 2415},
		{OID: 2201, Name: "_refcursor", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 2202, Name: "regprocedure", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 2212, Output: 2213, Receive: 2446, Send: 2447},
		{OID: 2203, Name: "regoper", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 2214, Output: 2215, Receive: 2448, Send: 2449},
		{OID: 2204, Name: "regoperator", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 2216, Output: 2217, Receive: 2450, Send: 2451},
		{OID: 2205, Name: "regclass", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 2218, Output: 2219, Receive: 2452, Send: 2453},
		{OID: 2206, Name: "regtype", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 2220, Output: 2221, Receive: 2454, Send: 2455},
		{OID: 2207, Name: "_regprocedure", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 2208, Name: "_regoper", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 2209, Name: "_regoperator", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 2210, Name: "_regclass", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 2211, Name: "_regtype", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 2249, Name: "record", Len: -1, ByVal: false, Type: 'p', Category: 'P', Align: 'd', Storage: 'x', Input: 2290, Output: 2291, Receive: 2402, Send: 2403},
		{OID: 2275, Name: "cstring", Len: -2, ByVal: false, Type: 'p', Category: 'P', Align: 'c', Storage: 'p', Input: 2292, Output: 2293, Receive: 2500, Send: 2501},
		{OID: 2276, Name: "any", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 2294, Output: 2295, Receive: 0, Send: 0},
		{OID: 2277, Name: "anyarray", Len: -1, ByVal: false, Type: 'p', Category: 'P', Align: 'd', Storage: 'x', Input: 2296, Output: 2297, Receive: 2502, Send: 2503},
		{OID: 2278, Name: "void", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 2298, Output: 2299, Receive: 3120, Send: 3121},
		{OID: 2279, Name: "trigger", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 2300, Output: 2301, Receive: 0, Send: 0},
		{OID: 2280, Name: "language_handler", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 2302, Output: 2303, Receive: 0, Send: 0},
		{OID: 2281, Name: "internal", Len: 8, ByVal: true, Type: 'p', Category: 'P', Align: 'd', Storage: 'p', Input: 2304, Output: 2305, Receive: 0, Send: 0},
		{OID: 2283, Name: "anyelement", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 2312, Output: 2313, Receive: 0, Send: 0},
		{OID: 2287, Name: "_record", Len: -1, ByVal: false, Type: 'p', Category: 'P', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 2776, Name: "anynonarray", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 2777, Output: 2778, Receive: 0, Send: 0},
		{OID: 2949, Name: "_txid_snapshot", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 2950, Name: "uuid", Len: 16, ByVal: false, Type: 'b', Category: 'U', Align: 'c', Storage: 'p', Input: 2952, Output: 2953, Receive: 2961, Send: 2962},
		{OID: 2951, Name: "_uuid", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 2970, Name: "txid_snapshot", Len: -1, ByVal: false, Type: 'b', Category: 'U', Align: 'd', Storage: 'x', Input: 2939, Output: 2940, Receive: 2941, Send: 2942},
		{OID: 3115, Name: "fdw_handler", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 3116, Output: 3117, Receive: 0, Send: 0},
		{OID: 3220, Name: "pg_lsn", Len: 8, ByVal: true, Type: 'b', Category: 'U', Align: 'd', Storage: 'p', Input: 3229, Output: 3230, Receive: 3238, Send: 3239},
		{OID: 3221, Name: "_pg_lsn", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3310, Name: "tsm_handler", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 3311, Output: 3312, Receive: 0, Send: 0},
		{OID: 3361, Name: "pg_ndistinct", Len: -1, ByVal: false, Type: 'b', Category: 'Z', Align: 'i', Storage: 'x', Input: 3355, Output: 3356, Receive: 3357, Send: 3358},
		{OID: 3402, Name: "pg_dependencies", Len: -1, ByVal: false, Type: 'b', Category: 'Z', Align: 'i', Storage: 'x', Input: 3404, Output: 3405, Receive: 3406, Send: 3407},
		{OID: 3500, Name: "anyenum", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 3504, Output: 3505, Receive: 0, Send: 0},
		{OID: 3614, Name: "tsvector", Len: -1, ByVal: false, Type: 'b', Category: 'U', Align: 'i', Storage: 'x', Input: 3610, Output: 3611, Receive: 3639, Send: 3638},
		{OID: 3615, Name: "tsquery", Len: -1, ByVal: false, Type: 'b', Category: 'U', Align: 'i', Storage: 'p', Input: 3612, Output: 3613, Receive: 3641, Send: 3640},
		{OID: 3642, Name: "gtsvector", Len: -1, ByVal: false, Type: 'b', Category: 'U', Align: 'i', Storage: 'p', Input: 3646, Output: 3647, Receive: 0, Send: 0},
		{OID: 3643, Name: "_tsvector", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3644, Name: "_gtsvector", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3645, Name: "_tsquery", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3734, Name: "regconfig", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 3736, Output: 3737, Receive: 3738, Send: 3739},
		{OID: 3735, Name: "_regconfig", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3769, Name: "regdictionary", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 3771, Output: 3772, Receive: 3773, Send: 3774},
		{OID: 3770, Name: "_regdictionary", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3802, Name: "jsonb", Len: -1, ByVal: false, Type: 'b', Category: 'U', Align: 'i', Storage: 'x', Input: 3806, Output: 3804, Receive: 3805, Send: 3803},
		{OID: 3807, Name: "_jsonb", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3831, Name: "anyrange", Len: -1, ByVal: false, Type: 'p', Category: 'P', Align: 'd', Storage: 'x', Input: 3832, Output: 3833, Receive: 0, Send: 0},
		{OID: 3838, Name: "event_trigger", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 3594, Output: 3595, Receive: 0, Send: 0},
		{OID: 3904, Name: "int4range", Len: -1, ByVal: false, Type: 'r', Category: 'R', Align: 'i', Storage: 'x', Input: 3834, Output: 3835, Receive: 3836, Send: 3837},
		{OID: 3905, Name: "_int4range", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3906, Name: "numrange", Len: -1, ByVal: false, Type: 'r', Category: 'R', Align: 'i', Storage: 'x', Input: 3834, Output: 3835, Receive: 3836, Send: 3837},
		{OID: 3907, Name: "_numrange", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3908, Name: "tsrange", Len: -1, ByVal: false, Type: 'r', Category: 'R', Align: 'd', Storage: 'x', Input: 3834, Output: 3835, Receive: 3836, Send: 3837},
		{OID: 3909, Name: "_tsrange", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3910, Name: "tstzrange", Len: -1, ByVal: false, Type: 'r', Category: 'R', Align: 'd', Storage: 'x', Input: 3834, Output: 3835, Receive: 3836, Send: 3837},
		{OID: 3911, Name: "_tstzrange", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3912, Name: "daterange", Len: -1, ByVal: false, Type: 'r', Category: 'R', Align: 'i', Storage: 'x', Input: 3834, Output: 3835, Receive: 3836, Send: 3837},
		{OID: 3913, Name: "_daterange", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 3926, Name: "int8range", Len: -1, ByVal: false, Type: 'r', Category: 'R', Align: 'd', Storage: 'x', Input: 3834, Output: 3835, Receive: 3836, Send: 3837},
		{OID: 3927, Name: "_int8range", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 4072, Name: "jsonpath", Len: -1, ByVal: false, Type: 'b', Category: 'U', Align: 'i', Storage: 'x', Input: 4001, Output: 4003, Receive: 4002, Send: 4004},
		{OID: 4073, Name: "_jsonpath", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 4089, Name: "regnamespace", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 4084, Output: 4085, Receive: 4087, Send: 4088},
		{OID: 4090, Name: "_regnamespace", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 4096, Name: "regrole", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 4098, Output: 4092, Receive: 4094, Send: 4095},
		{OID: 4097, Name: "_regrole", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 4191, Name: "regcollation", Len: 4, ByVal: true, Type: 'b', Category: 'N', Align: 'i', Storage: 'p', Input: 4193, Output: 4194, Receive: 4196, Send: 4197},
		{OID: 4192, Name: "_regcollation", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 4451, Name: "int4multirange", Len: -1, ByVal: false, Type: 'm', Category: 'R', Align: 'i', Storage: 'x', Input: 4231, Output: 4232, Receive: 4233, Send: 4234},
		{OID: 4532, Name: "nummultirange", Len: -1, ByVal: false, Type: 'm', Category: 'R', Align: 'i', Storage: 'x', Input: 4231, Output: 4232, Receive: 4233, Send: 4234},
		{OID: 4533, Name: "tsmultirange", Len: -1, ByVal: false, Type: 'm', Category: 'R', Align: 'd', Storage: 'x', Input: 4231, Output: 4232, Receive: 4233, Send: 4234},
		{OID: 4534, Name: "tstzmultirange", Len: -1, ByVal: false, Type: 'm', Category: 'R', Align: 'd', Storage: 'x', Input: 4231, Output: 4232, Receive: 4233, Send: 4234},
		{OID: 4535, Name: "datemultirange", Len: -1, ByVal: false, Type: 'm', Category: 'R', Align: 'i', Storage: 'x', Input: 4231, Output: 4232, Receive: 4233, Send: 4234},
		{OID: 4536, Name: "int8multirange", Len: -1, ByVal: false, Type: 'm', Category: 'R', Align: 'd', Storage: 'x', Input: 4231, Output: 4232, Receive: 4233, Send: 4234},
		{OID: 4537, Name: "anymultirange", Len: -1, ByVal: false, Type: 'p', Category: 'P', Align: 'd', Storage: 'x', Input: 4229, Output: 4230, Receive: 0, Send: 0},
		{OID: 4538, Name: "anycompatiblemultirange", Len: -1, ByVal: false, Type: 'p', Category: 'P', Align: 'd', Storage: 'x', Input: 4226, Output: 4227, Receive: 0, Send: 0},
		{OID: 4600, Name: "pg_brin_bloom_summary", Len: -1, ByVal: false, Type: 'b', Category: 'Z', Align: 'i', Storage: 'x', Input: 4596, Output: 4597, Receive: 4598, Send: 4599},
		{OID: 4601, Name: "pg_brin_minmax_multi_summary", Len: -1, ByVal: false, Type: 'b', Category: 'Z', Align: 'i', Storage: 'x', Input: 4638, Output: 4639, Receive: 4640, Send: 4641},
		{OID: 5017, Name: "pg_mcv_list", Len: -1, ByVal: false, Type: 'b', Category: 'Z', Align: 'i', Storage: 'x', Input: 5018, Output: 5019, Receive: 5020, Send: 5021},
		{OID: 5038, Name: "pg_snapshot", Len: -1, ByVal: false, Type: 'b', Category: 'U', Align: 'd', Storage: 'x', Input: 5055, Output: 5056, Receive: 5057, Send: 5058},
		{OID: 5039, Name: "_pg_snapshot", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 5069, Name: "xid8", Len: 8, ByVal: true, Type: 'b', Category: 'U', Align: 'd', Storage: 'p', Input: 5070, Output: 5081, Receive: 5082, Send: 5083},
		{OID: 5077, Name: "anycompatible", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 5086, Output: 5087, Receive: 0, Send: 0},
		{OID: 5078, Name: "anycompatiblearray", Len: -1, ByVal: false, Type: 'p', Category: 'P', Align: 'd', Storage: 'x', Input: 5088, Output: 5089, Receive: 5090, Send: 5091},
		{OID: 5079, Name: "anycompatiblenonarray", Len: 4, ByVal: true, Type: 'p', Category: 'P', Align: 'i', Storage: 'p', Input: 5092, Output: 5093, Receive: 0, Send: 0},
		{OID: 5080, Name: "anycompatiblerange", Len: -1, ByVal: false, Type: 'p', Category: 'P', Align: 'd', Storage: 'x', Input: 5094, Output: 5095, Receive: 0, Send: 0},
		{OID: 6150, Name: "_int4multirange", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 6151, Name: "_nummultirange", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 6152, Name: "_tsmultirange", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 6153, Name: "_tstzmultirange", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 6155, Name: "_datemultirange", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'i', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
		{OID: 6157, Name: "_int8multirange", Len: -1, ByVal: false, Type: 'b', Category: 'A', Align: 'd', Storage: 'x', Input: 750, Output: 751, Receive: 2400, Send: 2401},
	}
}

// pgTypeGeneratedElemArraySubscript maps a pg_type OID to its
// {typelem, typarray, typsubscript} triple, derived from pg_type.dat the way
// genbki derives it (see cmd/gen-pg-type-data). initdb.pgTypeRow reads it for
// every heap row; OIDs that are not in pg_type.dat at all are covered by the
// hand-written overlay in pg_type_bootstrap.go.
var pgTypeGeneratedElemArraySubscript = map[uint32][3]uint32{
	16: {0, 1000, 0}, // bool
	17: {0, 1001, 0}, // bytea
	18: {0, 1002, 0}, // char
	19: {18, 1003, 6180}, // name
	20: {0, 1016, 0}, // int8
	21: {0, 1005, 0}, // int2
	22: {21, 1006, 6179}, // int2vector
	23: {0, 1007, 0}, // int4
	24: {0, 1008, 0}, // regproc
	25: {0, 1009, 0}, // text
	26: {0, 1028, 0}, // oid
	27: {0, 1010, 0}, // tid
	28: {0, 1011, 0}, // xid
	29: {0, 1012, 0}, // cid
	30: {26, 1013, 6179}, // oidvector
	32: {0, 0, 0}, // pg_ddl_command
	71: {0, 210, 0}, // pg_type
	75: {0, 270, 0}, // pg_attribute
	81: {0, 272, 0}, // pg_proc
	83: {0, 273, 0}, // pg_class
	114: {0, 199, 0}, // json
	142: {0, 143, 0}, // xml
	143: {142, 0, 6179}, // _xml
	194: {0, 0, 0}, // pg_node_tree
	199: {114, 0, 6179}, // _json
	210: {71, 0, 6179}, // _pg_type
	269: {0, 0, 0}, // table_am_handler
	270: {75, 0, 6179}, // _pg_attribute
	271: {5069, 0, 6179}, // _xid8
	272: {81, 0, 6179}, // _pg_proc
	273: {83, 0, 6179}, // _pg_class
	325: {0, 0, 0}, // index_am_handler
	600: {701, 1017, 6180}, // point
	601: {600, 1018, 6180}, // lseg
	602: {0, 1019, 0}, // path
	603: {600, 1020, 6180}, // box
	604: {0, 1027, 0}, // polygon
	628: {701, 629, 6180}, // line
	629: {628, 0, 6179}, // _line
	650: {0, 651, 0}, // cidr
	651: {650, 0, 6179}, // _cidr
	700: {0, 1021, 0}, // float4
	701: {0, 1022, 0}, // float8
	705: {0, 0, 0}, // unknown
	718: {0, 719, 0}, // circle
	719: {718, 0, 6179}, // _circle
	774: {0, 775, 0}, // macaddr8
	775: {774, 0, 6179}, // _macaddr8
	790: {0, 791, 0}, // money
	791: {790, 0, 6179}, // _money
	829: {0, 1040, 0}, // macaddr
	869: {0, 1041, 0}, // inet
	1000: {16, 0, 6179}, // _bool
	1001: {17, 0, 6179}, // _bytea
	1002: {18, 0, 6179}, // _char
	1003: {19, 0, 6179}, // _name
	1005: {21, 0, 6179}, // _int2
	1006: {22, 0, 6179}, // _int2vector
	1007: {23, 0, 6179}, // _int4
	1008: {24, 0, 6179}, // _regproc
	1009: {25, 0, 6179}, // _text
	1010: {27, 0, 6179}, // _tid
	1011: {28, 0, 6179}, // _xid
	1012: {29, 0, 6179}, // _cid
	1013: {30, 0, 6179}, // _oidvector
	1014: {1042, 0, 6179}, // _bpchar
	1015: {1043, 0, 6179}, // _varchar
	1016: {20, 0, 6179}, // _int8
	1017: {600, 0, 6179}, // _point
	1018: {601, 0, 6179}, // _lseg
	1019: {602, 0, 6179}, // _path
	1020: {603, 0, 6179}, // _box
	1021: {700, 0, 6179}, // _float4
	1022: {701, 0, 6179}, // _float8
	1027: {604, 0, 6179}, // _polygon
	1028: {26, 0, 6179}, // _oid
	1033: {0, 1034, 0}, // aclitem
	1034: {1033, 0, 6179}, // _aclitem
	1040: {829, 0, 6179}, // _macaddr
	1041: {869, 0, 6179}, // _inet
	1042: {0, 1014, 0}, // bpchar
	1043: {0, 1015, 0}, // varchar
	1082: {0, 1182, 0}, // date
	1083: {0, 1183, 0}, // time
	1114: {0, 1115, 0}, // timestamp
	1115: {1114, 0, 6179}, // _timestamp
	1182: {1082, 0, 6179}, // _date
	1183: {1083, 0, 6179}, // _time
	1184: {0, 1185, 0}, // timestamptz
	1185: {1184, 0, 6179}, // _timestamptz
	1186: {0, 1187, 0}, // interval
	1187: {1186, 0, 6179}, // _interval
	1231: {1700, 0, 6179}, // _numeric
	1263: {2275, 0, 6179}, // _cstring
	1266: {0, 1270, 0}, // timetz
	1270: {1266, 0, 6179}, // _timetz
	1560: {0, 1561, 0}, // bit
	1561: {1560, 0, 6179}, // _bit
	1562: {0, 1563, 0}, // varbit
	1563: {1562, 0, 6179}, // _varbit
	1700: {0, 1231, 0}, // numeric
	1790: {0, 2201, 0}, // refcursor
	2201: {1790, 0, 6179}, // _refcursor
	2202: {0, 2207, 0}, // regprocedure
	2203: {0, 2208, 0}, // regoper
	2204: {0, 2209, 0}, // regoperator
	2205: {0, 2210, 0}, // regclass
	2206: {0, 2211, 0}, // regtype
	2207: {2202, 0, 6179}, // _regprocedure
	2208: {2203, 0, 6179}, // _regoper
	2209: {2204, 0, 6179}, // _regoperator
	2210: {2205, 0, 6179}, // _regclass
	2211: {2206, 0, 6179}, // _regtype
	2249: {0, 0, 0}, // record
	2275: {0, 1263, 0}, // cstring
	2276: {0, 0, 0}, // any
	2277: {0, 0, 0}, // anyarray
	2278: {0, 0, 0}, // void
	2279: {0, 0, 0}, // trigger
	2280: {0, 0, 0}, // language_handler
	2281: {0, 0, 0}, // internal
	2283: {0, 0, 0}, // anyelement
	2287: {2249, 0, 6179}, // _record
	2776: {0, 0, 0}, // anynonarray
	2949: {2970, 0, 6179}, // _txid_snapshot
	2950: {0, 2951, 0}, // uuid
	2951: {2950, 0, 6179}, // _uuid
	2970: {0, 2949, 0}, // txid_snapshot
	3115: {0, 0, 0}, // fdw_handler
	3220: {0, 3221, 0}, // pg_lsn
	3221: {3220, 0, 6179}, // _pg_lsn
	3310: {0, 0, 0}, // tsm_handler
	3361: {0, 0, 0}, // pg_ndistinct
	3402: {0, 0, 0}, // pg_dependencies
	3500: {0, 0, 0}, // anyenum
	3614: {0, 3643, 0}, // tsvector
	3615: {0, 3645, 0}, // tsquery
	3642: {0, 3644, 0}, // gtsvector
	3643: {3614, 0, 6179}, // _tsvector
	3644: {3642, 0, 6179}, // _gtsvector
	3645: {3615, 0, 6179}, // _tsquery
	3734: {0, 3735, 0}, // regconfig
	3735: {3734, 0, 6179}, // _regconfig
	3769: {0, 3770, 0}, // regdictionary
	3770: {3769, 0, 6179}, // _regdictionary
	3802: {0, 3807, 6098}, // jsonb
	3807: {3802, 0, 6179}, // _jsonb
	3831: {0, 0, 0}, // anyrange
	3838: {0, 0, 0}, // event_trigger
	3904: {0, 3905, 0}, // int4range
	3905: {3904, 0, 6179}, // _int4range
	3906: {0, 3907, 0}, // numrange
	3907: {3906, 0, 6179}, // _numrange
	3908: {0, 3909, 0}, // tsrange
	3909: {3908, 0, 6179}, // _tsrange
	3910: {0, 3911, 0}, // tstzrange
	3911: {3910, 0, 6179}, // _tstzrange
	3912: {0, 3913, 0}, // daterange
	3913: {3912, 0, 6179}, // _daterange
	3926: {0, 3927, 0}, // int8range
	3927: {3926, 0, 6179}, // _int8range
	4072: {0, 4073, 0}, // jsonpath
	4073: {4072, 0, 6179}, // _jsonpath
	4089: {0, 4090, 0}, // regnamespace
	4090: {4089, 0, 6179}, // _regnamespace
	4096: {0, 4097, 0}, // regrole
	4097: {4096, 0, 6179}, // _regrole
	4191: {0, 4192, 0}, // regcollation
	4192: {4191, 0, 6179}, // _regcollation
	4451: {0, 6150, 0}, // int4multirange
	4532: {0, 6151, 0}, // nummultirange
	4533: {0, 6152, 0}, // tsmultirange
	4534: {0, 6153, 0}, // tstzmultirange
	4535: {0, 6155, 0}, // datemultirange
	4536: {0, 6157, 0}, // int8multirange
	4537: {0, 0, 0}, // anymultirange
	4538: {0, 0, 0}, // anycompatiblemultirange
	4600: {0, 0, 0}, // pg_brin_bloom_summary
	4601: {0, 0, 0}, // pg_brin_minmax_multi_summary
	5017: {0, 0, 0}, // pg_mcv_list
	5038: {0, 5039, 0}, // pg_snapshot
	5039: {5038, 0, 6179}, // _pg_snapshot
	5069: {0, 271, 0}, // xid8
	5077: {0, 0, 0}, // anycompatible
	5078: {0, 0, 0}, // anycompatiblearray
	5079: {0, 0, 0}, // anycompatiblenonarray
	5080: {0, 0, 0}, // anycompatiblerange
	6150: {4451, 0, 6179}, // _int4multirange
	6151: {4532, 0, 6179}, // _nummultirange
	6152: {4533, 0, 6179}, // _tsmultirange
	6153: {4534, 0, 6179}, // _tstzmultirange
	6155: {4535, 0, 6179}, // _datemultirange
	6157: {4536, 0, 6179}, // _int8multirange
}
