package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"
)

// suiteAgg accumulates the per-suite status breakdown derived from the
// per-spec inventory CSV. It is the source of truth for the generated
// markdown — the inventory CSV (docs/test-port/postgres-oracle-target-inventory.csv)
// is hand/loop-maintained at per-spec granularity and must NOT be rewritten
// by this tool.
type suiteAgg struct {
	suiteID  string
	kind     string
	total    int
	pass     int
	failed   int
	notTried int
	excluded int
	port     int
	defer_   int
	example  string
}

// loadInventory parses the per-spec inventory CSV and aggregates rows by
// suite_id, preserving first-seen order. Required columns: suite_id, kind,
// item_path, status.
func loadInventory(csvPath string) ([]*suiteAgg, error) {
	f, err := os.Open(csvPath)
	if err != nil {
		return nil, fmt.Errorf("open csv %q: %w", csvPath, err)
	}
	defer f.Close()

	r := csv.NewReader(f)
	header, err := r.Read()
	if err != nil {
		return nil, fmt.Errorf("read csv header: %w", err)
	}

	colIndex := func(name string) int {
		for i, h := range header {
			if h == name {
				return i
			}
		}
		return -1
	}
	suiteIdx := colIndex("suite_id")
	kindIdx := colIndex("kind")
	itemPathIdx := colIndex("item_path")
	statusIdx := colIndex("status")
	passReqIdx := colIndex("pass_required")
	if suiteIdx < 0 || kindIdx < 0 || itemPathIdx < 0 || statusIdx < 0 || passReqIdx < 0 {
		return nil, fmt.Errorf("csv missing required columns (suite_id, kind, item_path, status, pass_required)")
	}

	byID := make(map[string]*suiteAgg)
	var order []*suiteAgg
	maxIdx := suiteIdx
	for _, i := range []int{kindIdx, itemPathIdx, statusIdx, passReqIdx} {
		if i > maxIdx {
			maxIdx = i
		}
	}

	for {
		row, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("read csv row: %w", err)
		}
		if maxIdx >= len(row) {
			continue
		}
		id := row[suiteIdx]
		agg, ok := byID[id]
		if !ok {
			agg = &suiteAgg{suiteID: id, kind: row[kindIdx], example: row[itemPathIdx]}
			byID[id] = agg
			order = append(order, agg)
		}
		agg.total++
		switch row[statusIdx] {
		case "pass":
			agg.pass++
		case "failed":
			agg.failed++
		case "not-tried":
			agg.notTried++
		case "excluded":
			agg.excluded++
		case "port":
			agg.port++
			// A ported TAP test with pass_required=yes is a currently-passing
			// Go test (docs/test-port/README.md: "port: Ported TAP test; must
			// always pass"), so it counts as passing here too, on top of the
			// governance "port" bucket above. This intentionally breaks the
			// old invariant that the status columns sum to total for the
			// *-tap suites — see the note emitted alongside the table.
			if row[passReqIdx] == "yes" {
				agg.pass++
			}
		case "defer":
			agg.defer_++
		}
	}
	return order, nil
}

func main() {
	var (
		repoRoot = flag.String("repo-root", ".", "path to repository root")
		csvPath  = flag.String("csv", "docs/test-port/postgres-oracle-target-inventory.csv", "path to per-spec inventory CSV (relative to repo root)")
		outMD    = flag.String("out-md", "docs/test-port/postgres-oracle-target-inventory.md", "output markdown path (relative to repo root)")
	)
	flag.Parse()

	root, err := filepath.Abs(*repoRoot)
	if err != nil {
		fail("resolve repo root", err)
	}
	csvAbs := resolve(root, *csvPath)
	mdAbs := resolve(root, *outMD)

	suites, err := loadInventory(csvAbs)
	if err != nil {
		fail("load inventory csv", err)
	}

	if err := os.MkdirAll(filepath.Dir(mdAbs), 0o755); err != nil {
		fail("mkdir markdown dir", err)
	}
	md, err := os.Create(mdAbs)
	if err != nil {
		fail("create markdown", err)
	}
	defer md.Close()

	var g struct {
		total, pass, failed, notTried, excluded, port, defer_ int
	}
	for _, s := range suites {
		g.total += s.total
		g.pass += s.pass
		g.failed += s.failed
		g.notTried += s.notTried
		g.excluded += s.excluded
		g.port += s.port
		g.defer_ += s.defer_
	}

	// pass_rate excludes excluded-status rows from its denominator, and
	// excludes modules-suites/contrib-suites entirely (Makefile-level defer
	// roll-ups, not individually tracked pass/fail cases) from both their
	// own row and the overall total.
	rateExcluded := func(suiteID string) bool {
		return suiteID == "modules-suites" || suiteID == "contrib-suites"
	}
	passRate := func(pass, denom int) string {
		if denom <= 0 {
			return "n/a"
		}
		return fmt.Sprintf("%.1f%%", 100*float64(pass)/float64(denom))
	}
	var sumPass, sumDenom int
	for _, s := range suites {
		if rateExcluded(s.suiteID) {
			continue
		}
		sumPass += s.pass
		sumDenom += s.total - s.excluded
	}

	fmt.Fprintln(md, "# PostgreSQL Oracle Migration Target Inventory")
	fmt.Fprintln(md)
	fmt.Fprintln(md, "Generated by `go run ./cmd/gen-oracle-inventory --repo-root .`.")
	fmt.Fprintf(md, "Generated at: %s\n\n", time.Now().Format(time.RFC3339))
	fmt.Fprintln(md, "This is the canonical M0060 target inventory used for governance and reporting.")
	fmt.Fprintln(md, "Per-suite status counts are derived from `docs/test-port/postgres-oracle-target-inventory.csv`")
	fmt.Fprintln(md, "(the authoritative per-spec inventory); this tool only renders that CSV and never rewrites it.")
	fmt.Fprintln(md)
	fmt.Fprintln(md, "Notes on the columns below:")
	fmt.Fprintln(md, "- For the `*-tap` suites (`recovery-tap`, `subscription-tap`, `client-tools-tap`), a row with")
	fmt.Fprintln(md, "  `status=port, pass_required=yes` (a ported TAP test that must always pass) is counted under")
	fmt.Fprintln(md, "  BOTH `port` and `pass` — so for those three suites the status columns no longer sum to `total`;")
	fmt.Fprintln(md, "  that is expected, not a rendering bug.")
	fmt.Fprintln(md, "- `pass_rate` = `pass / (total - excluded)`, i.e. `excluded`-status rows are dropped from the")
	fmt.Fprintln(md, "  denominator.")
	fmt.Fprintln(md, "- `modules-suites` and `contrib-suites` are excluded from `pass_rate` entirely — both their own")
	fmt.Fprintln(md, "  row (shown as `—`) and the overall total's rate — because they are Makefile-level `defer`")
	fmt.Fprintln(md, "  roll-ups (one row per feature directory), not individually tracked pass/fail cases.")
	fmt.Fprintln(md)
	fmt.Fprintln(md, "| suite_id | kind | total | pass | failed | not-tried | excluded | port | defer | pass_rate | example |")
	fmt.Fprintln(md, "| -------- | ---- | ----: | ---: | -----: | --------: | -------: | ---: | ----: | --------: | ------- |")
	for _, s := range suites {
		rate := "—"
		if !rateExcluded(s.suiteID) {
			rate = passRate(s.pass, s.total-s.excluded)
		}
		fmt.Fprintf(md, "| %s | %s | %d | %d | %d | %d | %d | %d | %d | %s | `%s` |\n",
			s.suiteID, s.kind, s.total, s.pass, s.failed, s.notTried, s.excluded, s.port, s.defer_, rate, s.example)
	}
	fmt.Fprintf(md, "| **total** | | **%d** | **%d** | **%d** | **%d** | **%d** | **%d** | **%d** | **%s** | |\n",
		g.total, g.pass, g.failed, g.notTried, g.excluded, g.port, g.defer_, passRate(sumPass, sumDenom))
	fmt.Fprintln(md)
	fmt.Fprintln(md, "`total`'s `pass_rate` is `pass / (total - excluded)` summed over every suite above EXCEPT")
	fmt.Fprintln(md, "`modules-suites` and `contrib-suites` (see the notes above the table).")
}

// resolve returns path unchanged when absolute, otherwise joins it onto root.
func resolve(root, path string) string {
	if filepath.IsAbs(path) {
		return path
	}
	return filepath.Join(root, path)
}

func fail(where string, err error) {
	fmt.Fprintf(os.Stderr, "gen-oracle-inventory: %s: %v\n", where, err)
	os.Exit(1)
}
