package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/goopg/goopg/internal/testport/framework"
)

func main() {
	var (
		repoRoot = flag.String("repo-root", ".", "path to repository root")
		outMD    = flag.String("out-md", "docs/test-port/postgres-oracle-target-inventory.md", "output markdown path")
		outCSV   = flag.String("out-csv", "docs/test-port/postgres-oracle-target-inventory.csv", "output csv path")
	)
	flag.Parse()

	root, err := filepath.Abs(*repoRoot)
	if err != nil {
		fail("resolve repo root", err)
	}
	rows, err := framework.BuildSuiteInventory(root)
	if err != nil {
		fail("build inventory", err)
	}

	if err := os.MkdirAll(filepath.Dir(*outCSV), 0o755); err != nil {
		fail("mkdir csv dir", err)
	}
	csvFile, err := os.Create(*outCSV)
	if err != nil {
		fail("create csv", err)
	}
	defer csvFile.Close()
	cw := csv.NewWriter(csvFile)
	_ = cw.Write([]string{"suite_id", "upstream_pattern", "kind", "count", "example"})
	for _, r := range rows {
		_ = cw.Write([]string{r.SuiteID, r.UpstreamPattern, r.Kind, fmt.Sprintf("%d", r.Count), r.Example})
	}
	cw.Flush()
	if err := cw.Error(); err != nil {
		fail("write csv", err)
	}

	if err := os.MkdirAll(filepath.Dir(*outMD), 0o755); err != nil {
		fail("mkdir markdown dir", err)
	}
	md, err := os.Create(*outMD)
	if err != nil {
		fail("create markdown", err)
	}
	defer md.Close()

	fmt.Fprintln(md, "# PostgreSQL Oracle Migration Target Inventory")
	fmt.Fprintln(md)
	fmt.Fprintln(md, "Generated by `go run ./cmd/gen-oracle-inventory --repo-root .`.")
	fmt.Fprintf(md, "Generated at: %s\n\n", time.Now().Format(time.RFC3339))
	fmt.Fprintln(md, "This is the canonical M0060 target inventory used for governance and reporting.")
	fmt.Fprintln(md)
	fmt.Fprintln(md, "| suite_id | upstream_pattern | kind | count | example |")
	fmt.Fprintln(md, "| -------- | ---------------- | ---- | ----: | ------- |")
	for _, r := range rows {
		fmt.Fprintf(md, "| %s | `%s` | %s | %d | `%s` |\n", r.SuiteID, r.UpstreamPattern, r.Kind, r.Count, r.Example)
	}
}

func fail(where string, err error) {
	fmt.Fprintf(os.Stderr, "gen-oracle-inventory: %s: %v\n", where, err)
	os.Exit(1)
}
